### ISSUE TITLE
LoadWith joins with invalid key

### ISSUE THREAD

**Issue by stsrki** [linq2db/linq2db#2614] opened 2020-11-11 08:59 UTC
Hi, I stumbled upon serious issues with association join generating the invalid join key from child to parent model. I have created a small repro project with all the same models that I use. Available at https://github.com/stsrki/L2DBAssocicationIssue

Also, the create table scripts are also available.

**Query:**

```
using ( var db = new Database( context ) )
{
    var query = db.GetTable<Invoice>()
        .Where( x => x.Id == 37 );

    query = query
        .LoadWith( x => x.MarketCurrency )
        .LoadWith( x => x.ChargedCurrency )
        .LoadWith( x => x.InvoiceCurrency )
        .LoadWith( x => x.DiscountCurrency )
        .LoadWith( x => x.InvoiceItems )
            .ThenLoad( x => x.MarketCurrency )
        .LoadWith( x => x.InvoiceItems )
            .ThenLoad( x => x.ChargedCurrency )
        .LoadWith( x => x.InvoiceItems )
            .ThenLoad( x => x.InvoiceCurrency );

    var invoice = query.FirstOrDefault();
}
```

**Generates**

```
exec sp_executesql N'SELECT
	[lw_Invoice].[InvoiceId],
	[detail].[InvoiceItemId],
	[detail].[InvoiceId],
	[detail].[ProductName],
	[detail].[ProductVersion],
	[detail].[LicenseName],
	[detail].[Quantity],
	[detail].[TaxRate],
	[detail].[MarketCurrencyId],
	[detail].[MarketPrice],
	[detail].[MarketDiscount],
	[detail].[MarketSubtotal],
	[detail].[MarketTax],
	[detail].[MarketTotal],
	[detail].[ChargedCurrencyId],
	[detail].[ChargedPrice],
	[detail].[ChargedDiscount],
	[detail].[ChargedSubtotal],
	[detail].[ChargedTax],
	[detail].[ChargedTotal],
	[detail].[InvoiceCurrencyId],
	[detail].[InvoicePrice],
	[detail].[InvoiceDiscount],
	[detail].[InvoiceSubtotal],
	[detail].[InvoiceTax],
	[detail].[InvoiceTotal],
	[a_MarketCurrency].[CurrencyId],
	[a_MarketCurrency].[Iso3],
	[a_MarketCurrency].[Name],
	[a_MarketCurrency].[Symbol],
	[a_MarketCurrency].[Unit],
	[a_ChargedCurrency].[CurrencyId],
	[a_ChargedCurrency].[Iso3],
	[a_ChargedCurrency].[Name],
	[a_ChargedCurrency].[Symbol],
	[a_ChargedCurrency].[Unit],
	[a_InvoiceCurrency].[CurrencyId],
	[a_InvoiceCurrency].[Iso3],
	[a_InvoiceCurrency].[Name],
	[a_InvoiceCurrency].[Symbol],
	[a_InvoiceCurrency].[Unit]
FROM
	(
		SELECT DISTINCT
			[t1].[InvoiceId]
		FROM
			(
				SELECT TOP (@take)
					[x].[InvoiceId]
				FROM
					[Financial].[Invoice] [x]
				WHERE
					[x].[InvoiceId] = 37
			) [t1]
	) [lw_Invoice]
		INNER JOIN [Financial].[InvoiceItem] [detail] ON [lw_Invoice].[InvoiceId] = [detail].[InvoiceItemId]
		INNER JOIN [Common].[Currency] [a_InvoiceCurrency] ON [detail].[InvoiceCurrencyId] = [a_InvoiceCurrency].[CurrencyId]
		INNER JOIN [Common].[Currency] [a_ChargedCurrency] ON [detail].[ChargedCurrencyId] = [a_ChargedCurrency].[CurrencyId]
		INNER JOIN [Common].[Currency] [a_MarketCurrency] ON [detail].[MarketCurrencyId] = [a_MarketCurrency].[CurrencyId]
',N'@take int',@take=1
```

**and**

```
exec sp_executesql N'SELECT TOP (@take)
	[x].[InvoiceId],
	[x].[OrderId],
	[x].[InvoiceDate],
	[x].[InvoiceNumber],
	[x].[InvoiceNumberFull],
	[x].[CancellationInvoiceId],
	[x].[CancellationDate],
	[x].[OfficeSpaceNumber],
	[x].[PaymentDeviceNumber],
	[x].[PaymentType],
	[x].[CustomerType],
	[x].[CustomerEmail],
	[x].[CustomerFirstName],
	[x].[CustomerLastName],
	[x].[CustomerCompany],
	[x].[CustomerAddress],
	[x].[CustomerAddress2],
	[x].[CustomerCity],
	[x].[CustomerZip],
	[x].[CustomerCountry],
	[x].[CustomerVat],
	[x].[CustomerOib],
	[x].[CustomerReverseCharge],
	[x].[SellerName],
	[x].[SellerAddress],
	[x].[SellerAddress2],
	[x].[SellerCity],
	[x].[SellerZip],
	[x].[SellerCountry],
	[x].[SellerWeb],
	[x].[SellerVat],
	[x].[DiscountType],
	[x].[DiscountValue],
	[x].[DiscountReferenceType],
	[x].[DiscountCurrencyId],
	[x].[MarketCurrencyId],
	[x].[MarketExchangeDate],
	[x].[MarketExchangeRate],
	[x].[MarketSubtotal],
	[x].[MarketDiscount],
	[x].[MarketTax],
	[x].[MarketTotal],
	[x].[ChargedCurrencyId],
	[x].[ChargedExchangeDate],
	[x].[ChargedExchangeRate],
	[x].[ChargedSubtotal],
	[x].[ChargedDiscount],
	[x].[ChargedTax],
	[x].[ChargedTotal],
	[x].[InvoiceCurrencyId],
	[x].[InvoiceExchangeDate],
	[x].[InvoiceExchangeRate],
	[x].[InvoiceSubtotal],
	[x].[InvoiceDiscount],
	[x].[InvoiceTax],
	[x].[InvoiceTotal],
	[x].[ExchangeRateDifference],
	[x].[FiscalizationId],
	[x].[Zki],
	[x].[Jir],
	[x].[IssuerName],
	[x].[IssuerOib],
	[a_MarketCurrency].[CurrencyId],
	[a_MarketCurrency].[Iso3],
	[a_MarketCurrency].[Name],
	[a_MarketCurrency].[Symbol],
	[a_MarketCurrency].[Unit],
	[a_ChargedCurrency].[CurrencyId],
	[a_ChargedCurrency].[Iso3],
	[a_ChargedCurrency].[Name],
	[a_ChargedCurrency].[Symbol],
	[a_ChargedCurrency].[Unit],
	[a_InvoiceCurrency].[CurrencyId],
	[a_InvoiceCurrency].[Iso3],
	[a_InvoiceCurrency].[Name],
	[a_InvoiceCurrency].[Symbol],
	[a_InvoiceCurrency].[Unit],
	[a_DiscountCurrency].[CurrencyId],
	[a_DiscountCurrency].[Iso3],
	[a_DiscountCurrency].[Name],
	[a_DiscountCurrency].[Symbol],
	[a_DiscountCurrency].[Unit]
FROM
	[Financial].[Invoice] [x]
		INNER JOIN [Common].[Currency] [a_MarketCurrency] ON [x].[MarketCurrencyId] = [a_MarketCurrency].[CurrencyId]
		INNER JOIN [Common].[Currency] [a_ChargedCurrency] ON [x].[ChargedCurrencyId] = [a_ChargedCurrency].[CurrencyId]
		INNER JOIN [Common].[Currency] [a_InvoiceCurrency] ON [x].[InvoiceCurrencyId] = [a_InvoiceCurrency].[CurrencyId]
		LEFT JOIN [Common].[Currency] [a_DiscountCurrency] ON [x].[DiscountCurrencyId] = [a_DiscountCurrency].[CurrencyId]
WHERE
	[x].[InvoiceId] = 37
',N'@take int',@take=1
```

**Problem**

In the first generated query you can see 

```
INNER JOIN [Financial].[InvoiceItem] [detail] ON [lw_Invoice].[InvoiceId] = [detail].[InvoiceItemId]
```

and it should be

```
INNER JOIN [Financial].[InvoiceItem] [detail] ON [lw_Invoice].[InvoiceId] = [detail].[InvoiceId]
```

**Comment by sdanyliv** [comment] 2020-11-11 09:44
Duplicate of #2615

**Closed by sdanyliv** 2020-11-11 09:44 UTC
