### ISSUE TITLE
System.InvalidOperationException at Classes generation

### ISSUE THREAD

**Issue by YXMagnuMXY** [linq2db/linq2db#1320] opened 2018-09-20 06:15 UTC
Hi there!

I have an error(System.InvalidOperationException) on generation of the Classes, and the error is in the file LinqToDB.ttinclude:

```c#
p.Type = p.ProcParameters.Single(pr => pr.IsResult).ParameterType;
```
Can somebody help me with this please?

**Comment by YXMagnuMXY** [comment] 2018-09-20 06:17
![image](https://user-images.githubusercontent.com/33696606/45799370-ef9dd180-bcb5-11e8-8dae-90095dbbd55e.png)

**Comment by MaceWindu** [comment] 2018-09-20 11:43
Well, for one of functions linq2db wasn't able to identify return parameter.
To fix it in linq2db we need to know details, which we asked in issue template like linq2db version, database. Also function source code (without body, just signature definition) will help a lot.

As workaround you can remove this function in your tt template from Procedures collection before it used for model generation.

**Comment by YXMagnuMXY** [comment] 2018-09-20 12:01
### Environment details
linq2db version: 2.2.0
Database Server: PostgreSQL 10
Database Provider: Npgsql 4.0.3
Operating system: Windows 10 x64
Framework version: NET Framework 4.7.2

Now I have another problem.
Now I updated to 2.3.0, and the t4 file is not executing at all... I'm pressing CTRL+S, and nothing.

**Comment by MaceWindu** [comment] 2018-09-21 12:35
Could you provide failing function/procedure definition? Postgresql procedures model is pretty complex and without failing code it will be hard to reproduce and fix.

**Comment by YXMagnuMXY** [comment] 2018-09-21 14:39
I fixed the problem... I asked a friend to provide the .tools folder from his solution, because my linq2db.t4models didn't want to add npgsql and other dlls in that folder. After that the generation works, BUT, there are too many changes in the new 2.3.0 version.
The types changed. For example - Time without timezone from database was a string in classes, now is TimeSpan in classes.
Or other - Timespan without timezone from database was DateTime in classes, now is Object.

Where can we see those changes, and what should we expect next?
Those are too changes that can affect the procedures that we made in our code with the generated classes...

**Comment by MaceWindu** [comment] 2018-09-21 15:00
Don't think it is 2.3 related. Types support improvements for postgresql was a part of 2.0 release (https://github.com/linq2db/linq2db/wiki/Release-Notes-2.0.0#other-changes-and-fixes-8).

If you were using linq2db.t4models, it explains it, because we shipped this package with 2.x support only recently.

If you need old types, you can configure them using MappingSchema.

**Comment by MaceWindu** [comment] 2018-09-21 15:01
Closing it as it looks like you used pre-2.3 t4 templates with 2.3 linq2db and it is not supported scenario.

**Closed by MaceWindu** 2018-09-21 15:01 UTC

**Comment by MaceWindu** [comment] 2018-10-01 12:06
I've created separate issue for object-typed properties
