### ISSUE TITLE
 ORA-00904: "DATEDIFF": invalid identifier

### ISSUE THREAD

**Issue by slartus** [linq2db/linq2db#2654] opened 2020-11-23 06:55 UTC
### Exception

>  Exception: Oracle.ManagedDataAccess.Client.OracleException
Message  : ORA-00904: "DATEDIFF": invalid identifier
   в OracleInternal.ServiceObjects.OracleConnectionImpl.VerifyExecution(Int32& cursorId, Boolean bThrowArrayBindRelatedErrors, SqlStatementType sqlStatementType, Int32 arrayBindCount, OracleException& exceptionForArrayBindDML, Boolean& hasMoreRowsInDB, Boolean bFirstIterationDone)
   в OracleInternal.ServiceObjects.OracleCommandImpl.VerifyExecution(OracleConnectionImpl connectionImpl, Int32& cursorId, Boolean bThrowArrayBindRelatedErrors, OracleException& exceptionForArrayBindDML, Boolean& hasMoreRowsInDB, Boolean bFirstIterationDone)
   в OracleInternal.ServiceObjects.OracleCommandImpl.ExecuteReader(String commandText, OracleParameterCollection paramColl, CommandType commandType, OracleConnectionImpl connectionImpl, OracleDataReaderImpl& rdrImpl, Int32 longFetchSize, Int64 clientInitialLOBFS, OracleDependencyImpl orclDependencyImpl, Int64[] scnForExecution, Int64[]& scnFromExecution, OracleParameterCollection& bindByPositionParamColl, Boolean& bBindParamPresent, Int64& internalInitialLOBFS, OracleException& exceptionForArrayBindDML, OracleConnection connection, OracleLogicalTransaction& oracleLogicalTransaction, IEnumerable`1 adrianParsedStmt, Boolean isDescribeOnly, Boolean isFromEF)
   в Oracle.ManagedDataAccess.Client.OracleCommand.ExecuteReader(Boolean requery, Boolean fillRequest, CommandBehavior behavior)
   в Oracle.ManagedDataAccess.Client.OracleCommand.ExecuteDbDataReader(CommandBehavior behavior)
   в System.Data.Common.DbCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)

### Steps to reproduce
```
create table LINQ2DB_TEST
(
    ID    NUMBER not null
        constraint LINQ2DB_TEST_PK
            primary key,
    TEST1 VARCHAR2(20),
    TEST2 NUMBER,
    DATE1 DATE   not null
)
/
```
```c#
public class Db: DataConnection
    {
        public ITable<TestTable> TestTable => this.GetTable<TestTable>();

        public Db(string connectionString):base(ProviderName.OracleManaged, connectionString)
        {
        }       
    }

    [Table("LINQ2DB_TEST")]
    public class TestTable
    {
        [Column("ID"), PrimaryKey, NotNull]
        public long Id { get; set; } 

        [Column("TEST1")]
        public string Test1 { get; set; }

        [Column("TEST2")]
        public long Test2 { get; set; }

        [Column("DATE1")]
        public DateTime Date1 { get; set; }
    }
```

```c#
using (var db = new Db(connectionString))
{
     var query = (from item in db.TestTable select item)
                        .Where(i => Sql.DateDiff(Sql.DateParts.Minute, DateTime.Now, i.Date1) > 2);

    var items = await query.ToListAsync();
}
```

### Environment details
linq2db version: *3.1.6*
Database Server: *Oracle 19.0.0.0.0*
Database Provider: *?*
Operating system: *?*
.NET Framework: *4.7.2*, *.net core 3.1*

**Comment by MaceWindu** [comment] 2020-11-23 08:15
Duplicate of #2564

This is already implemented and will be released with next version

**Closed by MaceWindu** 2020-11-23 08:15 UTC
