### ISSUE TITLE
Invalid merge statement generated for InsertOrUpdate with Oracle

### ISSUE THREAD

**Issue by Lexey** [linq2db/linq2db#732] opened 2017-06-14 14:39 UTC
I have the following table defined:

```c#
    [Table("Currency")]
    public class Currency
    {
        /// <summary>The length of the CurrencyCode</summary>
        public const int CurrencyCodeLength = 3;


        /// <summary>Currency code</summary>
        /// <example>RUB</example>
        /// <example>USD</example>
        [Column(DataType = DataType.Char, Length = CurrencyCodeLength), PrimaryKey, LinqToDB.Mapping.NotNull]
        public string Code { get; set; }
    }
```
And I am trying to perform the following operation on it:
```c#
                dataAccess.GetTable<DbCurrency>()
                        .InsertOrUpdate(() => new DbCurrency { Code = currencyCode }, _ => new DbCurrency {});
```
So, it is just an "insert if not exists".

The following sql statement is being generated:
```sql
MERGE INTO pfe.Currency t1
USING (SELECT :currencyCode AS Code FROM SYS.DUAL) s ON
(
	t1.Code = s.Code
)
WHEN MATCHED THEN
	UPDATE 
	SET

WHEN NOT MATCHED THEN
	INSERT
	(
		Code
	)
	VALUES
	(
		:currencyCode
	)
```
And it is obviously invalid.

### Environment details
linq2db version: *1.8.2*  
Database Server: *Oracle 11g*  
Database Provider: *Oracle.Managed*  
Operating system: *Windows 7*  
Framework version: *.NET Framework 4.6.2*

**Comment by ili** [comment] 2017-06-21 05:05
@MaceWindu can you look at this?

**Comment by MaceWindu** [comment] 2017-06-21 11:44
This is duplicate of https://github.com/linq2db/linq2db/issues/100.
I will try to address it this week

**Closed** 2017-06-24 13:28 UTC
Labels: bug, sql
