### ISSUE TITLE
Bool filters MSSQL transformation

### ISSUE THREAD

**Issue by arwyl** [linq2db/linq2db#1662] opened 2019-03-26 12:56 UTC
Queries with filters like !x.SomeBoolProperty are transformed to sql like "1 <> [x].[SomeBoolProperty]" and not "0 = [x].[SomeBoolProperty]".
Maybe it is done for cases "null or false", but when property has [Column(CanBeNull = false), NotNull] attributes if's still the same.

That may not seem as a big deal, but sometimes MS SQL server doesn't use indexes, when it sees something like "1 <> [x].[SomeBoolProperty]". I cannot figure why, but on two servers 
(both has Microsoft SQL Server 2016 (SP2-CU6) (KB4488536) - 13.0.5292.0 (X64), one has production DB, the other has it's yesterday backup) the same query is planned differently (index is used on test server, not used on prod server)

Is it possible to change the way !x.SomeBoolProperty is transformed to SQL to "0 = [x].[SomeBoolProperty]" for bool properties?

### Environment details
linq2db version: *2.6.4
Database Server: *Microsoft SQL Server 2016 (SP2-CU6) (KB4488536) - 13.0.5292.0 (X64)*
Operating system: *Windows 10*
Framework version: *.NET Framework 4.6.2*

**Comment by sdanyliv** [comment] 2019-03-26 13:00
@arwyl, it is always reproducible?

**Comment by arwyl** [comment] 2019-03-26 13:03
@sdanyliv right now on one server - yes. On the other (right now) - not reproduced at all. The servers are identical..

**Comment by sdanyliv** [comment] 2019-03-26 13:05
I mean generated query `1 <> [x].[SomeBoolProperty]`. I'm asking because we did several fixes in this area several months ago.

**Comment by arwyl** [comment] 2019-03-26 13:06
yes, that is always reproducible with 2.6.4

**Comment by arwyl** [comment] 2019-03-27 07:44
UPD: the right index isn't being used on test server either
there was a recently created index on test server with similar name so I mistaken it for the correct index
so "1 <> [x].[SomeBoolProperty]" never uses index

**Comment by SaltyDH** [comment] 2019-05-18 11:15
I'm seeing this as well with a DeletedField == false && Id > 1 expression.

https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/Linq/Builder/ExpressionBuilder.SqlBuilder.cs#L2762

Is capturing the DeleteField == false comparison as a Expression.Not

This is then 'optimized' in the call to InvertOperator where the Equals operator is inverted to NotEqual.

https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/SqlProvider/BasicSqlOptimizer.cs#L1002

I don't immediately see the situations when a check against b == false in the ExpressionBuilder.SqlBuilder becomes necessary when the ExpressionType is 'Equal'

**Comment by MaceWindu** [comment] 2020-04-08 22:11
Duplicate of #845

**Comment by MaceWindu** [comment] 2024-06-19 09:39
Was fixed long time ago in `3.0.0-rc.2`

**Closed by MaceWindu** 2024-06-19 09:39 UTC
Labels: area: linq, type: bug, status: has-tests
