### ISSUE TITLE
InsertWithOutputIntoAsync exception Linq2db 5.3.2

### ISSUE THREAD

**Issue by zharonar** [linq2db/linq2db#4329] opened 2023-10-27 21:18 UTC
Hello there,

We're experiencing an issue with method `InsertWithOutputIntoAsync`.

We're just having basic usage where we need insert of Order then Insert into OrderLog.

We have our fn OutInsertedInto mapping to output table via reflection. Fields in OrderLog are the same as Order Table.

But we tried also mapping by hand new OrderLog() { fields = order Fields ... } etc... Same exception and stack trace...
```
Exception message: Object initializer expected for insert statement.
Stack trace:    at LinqToDB.Linq.Builder.UpdateBuilder.BuildSetterWithContext(ExpressionBuilder builder, BuildInfo buildInfo, LambdaExpression setter, IBuildContext into, List`1 items, IBuildContext[] sequences)
   at LinqToDB.Linq.Builder.InsertBuilder.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.Build[T]()
   at LinqToDB.Linq.Query`1.CreateQuery(ExpressionTreeOptimizationContext optimizationContext, ParametersContext parametersContext, IDataContext dataContext, Expression expr)
   at LinqToDB.Linq.Query`1.GetQuery(IDataContext dataContext, Expression& expr, Boolean& dependsOnParameters)
   at LinqToDB.Linq.ExpressionQuery`1.GetQuery(Expression& expression, Boolean cache, Boolean& dependsOnParameters)
   at LinqToDB.Linq.ExpressionQuery`1.<LinqToDB-Async-IQueryProviderAsync-ExecuteAsync>d__15`1.MoveNext()

```

### Steps to reproduce

Basic usage, give Target, Setter, Output Table and Expression.

```c#
var order = new Order() {
 //fields
};

var result = await ITable.InsertWithOutputIntoAsync(
        ITable,
        f => order,
        DB.GetTable<OrderLog>(),
        DB.OutInsertedInto<Order, OrderLog>((inserted) => new OrderLog()))
    .ContinueWith(f =>
    {
        if (f.IsFaulted)
            throw new ApplicationException(f.Exception!.Message, f.Exception!);
        if (f.Result == null)
            throw new ApplicationException(
                $"Issue occured with Order insert for: {order.Name}");

        return order;
    });
```

### Environment details

`Linq To DB` version: *5.3.2*

Database (with version): *SQL Server 2019*

ADO.NET Provider (with version): *System.Data.SqlClient 4.8.5*

Operating system: *Windows 10*

.NET Version: *.NET 6*

**Comment by viceroypenguin** [comment] 2023-10-27 21:58
Can you share your code using this:
> But we tried also mapping by hand new OrderLog() { fields = order Fields ... } etc... Same exception and stack trace...

**Comment by zharonar** [comment] 2023-10-30 10:05
> Can you share your code using this:
> 
> > But we tried also mapping by hand new OrderLog() { fields = order Fields ... } etc... Same exception and stack trace...

Basically instead of our expression method, just do the following, manually set fields from Order to the OrderLog

```c#
var order = new Order() {
                    CreatedBy = f.CreatedBy,
                    UpdatedBy = f.UpdatedBy,
                    OrderState = f.OrderState,
                    VehicleColor = f.VehicleColor,
                    VehicleIntro = f.VehicleIntro,
                    VehicleName = f.VehicleName
};

        var result= await ITable.InsertWithOutputIntoAsync(
                ITable,
                f => order,
                DB.GetTable<OrderLog>(),
                f => new OrderLog()
                {
                    CreatedBy = f.CreatedBy,
                    UpdatedBy = f.UpdatedBy,
                    OrderState = f.OrderState,
                    VehicleColor = f.VehicleColor,
                    VehicleIntro = f.VehicleIntro,
                    VehicleName = f.VehicleName
                })
            .ContinueWith(f =>
            {
                if (f.IsFaulted)
                    throw new ApplicationException(f.Exception!.Message, f.Exception!);
                if (f.Result == null)
                    throw new ApplicationException(
                        $"Issue occured with Order insert for: {order.VehicleName}");

                return order;
            });
```

**Comment by viceroypenguin** [comment] 2023-10-30 13:21
@zharonar  I apologize, I got focused on the wrong thing. The problem is your statement `f => order`. This will not work - that particular parameter will also only work with a `new{}` expression. It must be `f => new Order { ... }`, or a similarly created expression. 

However, I should warn you about this particular construction. The way it will work is to translate to something like:
```sql
insert Order
output inserted.xxx
into OrderLog
select @p1, @p2, @p3
from Order
```

Notice that even though you are providing values, it will select the entire table for `Order` and attempt to insert a new record for every record in `Order`. The construction I use for the above is:
```cs
new[] { order }.AsQueryable(DB)
  .InsertWithOutputIntoAsync(
    ITable,
    o => new Order { ... },
    DB.GetTable<OrderLog>(),
    o => new OrderLog { ... });
```

If you want to abstract each of the `o => ` into `DB`, that's fine, just know that they must be `o => new Record {...}` for both.

One last thing: I would recommend you research [Temporal Tables](https://learn.microsoft.com/en-us/sql/relational-databases/tables/temporal-tables?view=sql-server-ver16). The advantage with these is that you will get these log entries automatically without having to do an `insert output `.

**Comment by croban** [comment] 2023-10-30 18:00
@viceroypenguin 

> Notice that even though you are providing values, it will select the entire table for Order and attempt to insert a new record for every record in Order. The construction I use for the above is:

this part is for me not clear, because it will select only inserted rows (1,n) and not the whole table right?!

**Comment by viceroypenguin** [comment] 2023-10-30 18:03
> @viceroypenguin
> 
> > Notice that even though you are providing values, it will select the entire table for Order and attempt to insert a new record for every record in Order. The construction I use for the above is:
> 
> this part is for me not clear, because it will select only inserted rows (1,n) and not the whole table right?!

the `OutputInto` will only select the inserted rows, that's correct. however, the `Insert` will select all rows from `Table` and attempt to re-insert them, according to the projection provided. If you want to insert only one row, you have to give it a single row using the construction I provided.

Specifically, `IQueryable<T>.Insert()` will attempt to insert _all rows_ from the `IQueryable<T>`, so doing `context.Table.Insert(context.Table)` will attempt to select all rows from `Table` as the source for the `insert` statement, effectively:
```sql
insert Table
select *
from Table
```

**Comment by zharonar** [comment] 2023-10-30 22:27
> @zharonar I apologize, I got focused on the wrong thing. The problem is your statement `f => order`. This will not work - that particular parameter will also only work with a `new{}` expression. It must be `f => new Order { ... }`, or a similarly created expression.
>

Tried expression with new statement and it works!

**Comment by viceroypenguin** [comment] 2023-10-31 13:09
Glad you got it working! I'm going to close this now as it is no longer an issue. Please feel free to reopen if something else comes up on this topic.

**Closed by viceroypenguin** 2023-10-31 13:09 UTC
