### ISSUE TITLE
Sqlite not converting DateTime to Int64

### ISSUE THREAD

**Issue by CumpsD** [linq2db/linq2db#4038] opened 2023-03-20 20:16 UTC
Trying to migrate from 3.5.2 to 3.6.0 (on our way to 5.1.0)

We have a query which looks like this:

```csharp
var row = await connection.GetTable<SnapshotRow>()
    .Where(r =>
        r.PersistenceId == persistenceId &&
        r.SequenceNumber <= sequenceNr &&
        r.Created <= timestamp)
    .OrderByDescending(t => t.SequenceNumber)
    .FirstOrDefaultAsync();
```

Where Created is:
```csharp
[Column(DataType = DataType.DateTime2)]
public DateTime Created { get; set; }
```

But mapped with:
```csharp
builder
    .Member(r => r.Created)
    .HasDataType(DataType.Int64)
    .HasConversion(
        r => r.Ticks,
        r => new DateTime(r));
```

In 3.5.2, the query which got generated looked like:

```sql
SELECT
	[r].[persistence_id],
	[r].[sequence_number],
	[r].[created],
	[r].[snapshot],
	[r].[manifest],
	[r].[serializer_id]
FROM
	[snapshot] [r]
WHERE
	[r].[persistence_id] = @persistenceId AND [r].[sequence_number] <= @sequenceNr AND
	[r].[created] <= @timestamp_1
ORDER BY
	[r].[sequence_number] DESC
LIMIT @take
```

But in 3.6.0 it looks like:
```sql
SELECT
	[r].[persistence_id],
	[r].[sequence_number],
	[r].[created],
	[r].[snapshot],
	[r].[manifest],
	[r].[serializer_id]
FROM
	[snapshot] [r]
WHERE
	[r].[persistence_id] = @persistenceId AND [r].[sequence_number] <= @sequenceNr AND
	DateTime([r].[created]) <= DateTime(@timestamp_1)
ORDER BY
	[r].[sequence_number] DESC
LIMIT @take
```

Something seems to have happened to `DateTime([r].[created]) <= DateTime(@timestamp_1)` while the only thing that has changed is bumping from 3.5.2 to 3.6.0. It is as if the conversion is ignored?

**Comment by jogibear9988** [comment] 2023-03-20 20:40
Here is also a conversion, why the wrapping is there, and a link to the issue where it was introduced: https://github.com/linq2db/linq2db/issues/2432


But I don't know, why it now happens with your version change, and if it is intended.

Does it produce an error on your side?

**Comment by jogibear9988** [comment] 2023-03-20 20:41
Sqlite stores DateTimes only as strings, and comparisons could be wrong without the wrapping

**Comment by CumpsD** [comment] 2023-03-20 20:44
We are not storing the datetime, but the Ticks (`long`), there are no strings in the database, only numbers

Yes, it causes a problem, not an error, but it doesn't return data anymore.

There is more research here: https://github.com/akkadotnet/Akka.Persistence.Sql/pull/163#issuecomment-1475507465

This image shows a query which should return results (and which did in versions before 3.6.0) but now returns null:

![image](https://user-images.githubusercontent.com/1201644/226461469-97def3b7-8dcf-461e-a295-a9576294403d.png)

**Comment by CumpsD** [comment] 2023-03-20 20:45
Thanks for https://github.com/linq2db/linq2db/issues/2432, I will have a look

**Comment by MaceWindu** [comment] 2023-05-06 12:11
Duplicate of #2432

**Closed by MaceWindu** 2023-05-06 12:11 UTC
