### ISSUE TITLE
linq2db >3.1.6 uses packages >= 5.0.0 when targeting .NETCoreApp 2.1, .NETCoreApp 3.1, .NETStandard 2.0, .NETStandard 2.1

### ISSUE THREAD

**Issue by CodeZombieCH** [linq2db/linq2db#2976] opened 2021-04-29 21:34 UTC
When targeting
- .NETCoreApp 2.1
- .NETCoreApp 3.1
- .NETStandard 2.0
- .NETStandard 2.1
 
until version **3.1.6** linq2db referenced
- Microsoft.Bcl.AsyncInterfaces (>= **1.1.1**)
- System.ComponentModel.Annotations (>= **4.7.0**)

Starting with the next version **3.2.0**, this was changed to
- Microsoft.Bcl.AsyncInterfaces (>= **5.0.0**)
- System.ComponentModel.Annotations (>= **5.0.0**)

From my understanding using packages like *System.ComponentModel.Annotations* with versions >=5.0.0 might work with target frameworks <5.0.0 but are not guaranteed to do so. In our code base with mainly *.NETCoreApp 3.1* and *.NETStandard 2.0* projects we try to avoid using packages with versions >=5.0.0 for that reason. The dependency upgrade introduced in 3.2.0 breaks our NuGet package references, as we have projects with a direct reference to System.ComponentModel.Annotations 4.7.0 and an indirect references to System.ComponentModel.Annotations 5.0.0 caused by the latest linq2db.

Is there any reason for this change? I checked the [changelog for v3.2.0](https://github.com/linq2db/linq2db/wiki/releases-and-roadmap#release-320) but could not find any information about this change.

It looks like this package upgrade was already an issue before (see https://github.com/linq2db/linq2db/pull/2877/commits/23da8c97b29e66516077958bc32452537949b826), but was only fixed for *.NETCoreApp 3.1*:

### linq2db v3.1.6 (https://www.nuget.org/packages/linq2db/3.1.6)

.NETCoreApp 2.1

 - **Microsoft.Bcl.AsyncInterfaces (>= 1.1.1)**
 - **System.ComponentModel.Annotations (>= 4.7.0)**
 - System.Data.DataSetExtensions (>= 4.5.0)

.NETCoreApp 3.1

 - **System.ComponentModel.Annotations (>= 4.7.0)**

.NETStandard 2.0

 - **Microsoft.Bcl.AsyncInterfaces (>= 1.1.1)**
 - Microsoft.CSharp (>= 4.7.0)
 - **System.ComponentModel.Annotations (>= 4.7.0)**
 - System.Data.DataSetExtensions (>= 4.5.0)

.NETStandard 2.1

 - Microsoft.CSharp (>= 4.7.0)
 - **System.ComponentModel.Annotations (>= 4.7.0)**

### linq2db v3.2.0 (https://www.nuget.org/packages/linq2db/3.2.0)

.NETCoreApp 2.1
 - **Microsoft.Bcl.AsyncInterfaces (>= 5.0.0)**
 - **System.ComponentModel.Annotations (>= 5.0.0)**
 - System.Data.DataSetExtensions (>= 4.5.0)

.NETCoreApp 3.1
 - **System.ComponentModel.Annotations (>= 5.0.0)**

.NETStandard 2.0
 - **Microsoft.Bcl.AsyncInterfaces (>= 5.0.0)**
 - Microsoft.CSharp (>= 4.7.0)
 - **System.ComponentModel.Annotations (>= 5.0.0)**
 - System.Data.DataSetExtensions (>= 4.5.0)

.NETStandard 2.1
 - Microsoft.CSharp (>= 4.7.0)
 - **System.ComponentModel.Annotations (>= 5.0.0)**

### Environment details
linq2db version: >3.2.0
Database Server: -
Database Provider: -
Operating system: -
.NET Framework: .NETCoreApp 2.1, .NETCoreApp 3.1, .NETStandard 2.0, .NETStandard 2.1

**Comment by MaceWindu** [comment] 2021-04-30 08:59
I don't see reason to downgrade them as package upgrades based on supported target frameworks, not on numbers in version field.

Downgrade of `System.ComponentModel.Annotations` is separate case as issue it fixes caused by hardcoded dependencies in Azure Functions runtime.

**Comment by MaceWindu** [comment] 2021-05-10 08:45
Closing for now. If you can provide scenario where it doesn't work, we could reconcider it.

**Closed by MaceWindu** 2021-05-10 08:45 UTC
