### ISSUE TITLE
PostgreSQL: Syntaxerror using Limit

### ISSUE THREAD

**Issue by jogibear9988** [linq2db/linq2db#2754] opened 2021-01-02 11:23 UTC
we use following c# code:

                        var deleted = (from dispatcherMessageBuffer in databaseSession.Query<DispatcherMessageBufferDTO>(_plantId)
                            where dispatcherMessageBuffer.CreatedTimeStamp < olderThan
                                  && dispatcherMessageBuffer.Dispatcher == dispatcherBufferNumberDTO.Dispatcher
                                  && dispatcherMessageBuffer.MessageNumber < dispatcherBufferNumberDTO.MessageNumber
                            select dispatcherMessageBuffer).Take(chunkSize).Delete();

this creates following query:

	DELETE FROM
		MFCV2_DispatcherMessagesBuffer x
	WHERE
		x.PlantId = :plantID AND
		x.CreatedTimeStamp < :olderThan AND
		x.Dispatcher = :Dispatcher AND
		x.MessageNumber < :MessageNumber
	LIMIT :take

wich raises this exception:

        Npgsql.PostgresException: "42601: Syntaxfehler bei »LIMIT«"

I found this in stackoverflow:

https://stackoverflow.com/questions/5170546/how-do-i-delete-a-fixed-number-of-rows-with-sorting-in-postgresql

PostgreSQL doesn't allow ordering or limits in its delete syntax, ....

**Comment by MaceWindu** [comment] 2021-01-02 11:31
Duplicate of #2549

**Closed by MaceWindu** 2021-01-02 11:31 UTC

**Comment by jogibear9988** [comment] 2021-01-02 12:28
@MaceWindu sorry I din't see that issue (and also forgot to search...)
