### ISSUE TITLE
Linq2db v3.x - Combined OrderBy has different order

### ISSUE THREAD

**Issue by jogibear9988** [linq2db/linq2db#2378] opened 2020-07-28 20:07 UTC
We had following linq query:

                var qryUnsorted =
                    from tt in s.Query<TextTranslationDTO>()
                    select tt;

                
               var qrySorted1 = from tt in qryUnsorted
                    orderby (from l in s.Query<LanguageDTO>()
                        where l.AlternativeLanguageID == tt.LanguageId // 1. Order by
                        select l.LanguageID).Count()
                    select tt;

                
                var qrySorted2 = from tt in qrySorted1
                                 join t in s.Query<TextDTO>() on tt.TextId equals t.Id
                                 orderby t.ServerOnlyText // 2. Order by
                                 select tt;

                var translation = qrySorted2.Select(tt => tt.Text).FirstOrDefault();
                var qryString = s.LastQuery();

This Generates following query in linq2db 3.x:

	SELECT TOP (@take)
		[tt].[Text]
	FROM
		[Common_Translation_TextTrans] [tt]
			INNER JOIN [Common_Translation_Texts] [t] ON [tt].[TextId] = [t].[Id]
	ORDER BY
		(
			SELECT
				Count(*)
			FROM
				[Common_Language] [l]
			WHERE
				[l].[AlternativeLanguageID] = [tt].[LanguageId]
		),
		[t].[ServerOnlyText]

but in linq2db 2.x the orderbys where switched

**Comment by jogibear9988** [comment] 2020-07-28 20:41
I've now tried to reproduce it like this:

			using (var db = GetDataContext(context))
			{
				var localQuery =
					from p in db.Parent
					orderby p.Value1
					select p;

				var dbQuery =
					from p in localQuery
					orderby p.ParentID
					select p;

				var l = dbQuery.ToList();

				var sql = ((DataConnection)db).LastQuery;
				
			}

but it only generates one order by (ParentId).

**Comment by jogibear9988** [comment] 2020-07-28 20:43
Should it generate two orderbys?
As linq is lazy, so I think linq2objects also only sorts by ParentId

**Comment by sdanyliv** [comment] 2020-07-28 20:58
Only latest one is matter. `ThenBy´ is a continuous ordering. OrderBy overrides previous ordering.

**Comment by jogibear9988** [comment] 2020-07-28 21:02
@sdanyliv but first query generates two order by's
and in v2.x the order is different

**Comment by jogibear9988** [comment] 2020-07-28 21:07
In bltoolkit we also allowed multiple orderbys without IOrderedEnumerable:

https://github.com/igor-tkachev/bltoolkit/issues/309

**Comment by sdanyliv** [comment] 2020-07-28 21:12
I’m personally think that is wrong, missed second order by condition. We have to investigate that it is standard or our feature.
Agree that switching order by position may be caused by 3.0 changes or can be broken by query optimization. Will check, i also do not like regressions and i know code which may cause such effect.

**Comment by exileDev** [comment] 2020-08-05 13:14
Also, ordering fields are duplicated independently of  `Linq.DoNotClearOrderBys` configuration value. :cry:
```
using (var db = GetDataContext(context))
{
	var firstOrder =
		from p in db.Parent
		orderby p.ParentID
		select p;

	var secondOrder =
		from p in firstOrder
		join pp in db.Parent on p.Value1 equals pp.Value1
		orderby pp.ParentID
		select p;

	var selectQuery = secondOrder.GetSelectQuery();
	Assert.That(selectQuery.OrderBy.Items.Count, Is.EqualTo(1));
}
```

SQL:
```
-- SqlServer.2008
SELECT
	[p].[ParentID],
	[p].[Value1]
FROM
	[Parent] [p]
		INNER JOIN [Parent] [pp] ON ([p].[Value1] IS NULL AND [pp].[Value1] IS NULL OR [p].[Value1] = [pp].[Value1])
ORDER BY
	[p].[ParentID],
	[pp].[ParentID]

```

**Comment by sdanyliv** [comment] 2020-08-05 13:23
@exileDev, i know what happened here. I've already fixed order items position, but looks like continuous ordering was here from the start. It is happened by subquery optimization and do not deal with `Linq.DoNotClearOrderBys`.

**Comment by exileDev** [comment] 2020-08-05 14:12
@sdanyliv Do I need to create a new issue? It is a very critically bug for us, and I accept your fix doesn't relate to a duplicating fields problem in "order by" clause. I ran a test on the `issue/2378` branch with the same result

**Comment by sdanyliv** [comment] 2020-08-05 14:39
So, problem that fields are duplicated? If it is an issue, i can fix that easily.
Anyway you can try to remove previous order by function `RemoveOrderBy`
```cs
firstOrder = firstOrder.RemoveOrderBy();
```

**Comment by exileDev** [comment] 2020-08-06 05:46
@sdanyliv Exactly. Exactly. In these cases, a DB engine throws SqlException. In 2.x versions, everything worked fine.

**Comment by sdanyliv** [comment] 2020-08-06 05:59
Will fix that. Probably i have improved subquery optimization and two order by was merged.

**Closed** 2020-08-08 09:08 UTC
