### ISSUE TITLE
Error with group clause

### ISSUE THREAD

**Issue by evanogainen** [linq2db/linq2db#1198] opened 2018-06-20 12:52 UTC
I'm porting our application from Linq To SQL and have been working around the differences, but have run into a blocking issue. I'm simply trying to group some results and get a count of where certain columns have certain values, but I get the error below.
This seems simple and I was under the impression linq2db should be able to handle this.
Please advise.

Thanks,
Andi Gordon

Exception message:

```
'i.Status' cannot be converted to SQL.
```

Stack trace:

```
   at LinqToDB.Linq.Builder.SelectContext.GetMemberExpression(MemberInfo member, Boolean add, Type type, Expression sourceExpression) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\SelectContext.cs:line 1161
   at LinqToDB.Linq.Builder.SelectContext.ConvertToSql(Expression expression, Int32 level, ConvertFlags flags) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\SelectContext.cs:line 342
   at LinqToDB.Linq.Builder.SelectContext.ConvertToIndexInternal(Expression expression, Int32 level, ConvertFlags flags) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\SelectContext.cs:line 554
   at LinqToDB.Linq.Builder.SelectContext.ConvertToIndex(Expression expression, Int32 level, ConvertFlags flags) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\SelectContext.cs:line 430
   at LinqToDB.Linq.Builder.SubQueryContext.ConvertToSql(Expression expression, Int32 level, ConvertFlags flags) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\SubQueryContext.cs:line 100
   at LinqToDB.Linq.Builder.SubQueryContext.ConvertToIndex(Expression expression, Int32 level, ConvertFlags flags) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\SubQueryContext.cs:line 110
   at LinqToDB.Linq.Builder.SubQueryContext.ConvertToSql(Expression expression, Int32 level, ConvertFlags flags) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\SubQueryContext.cs:line 100
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertToSql(IBuildContext context, Expression expression, Boolean unwrap) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\ExpressionBuilder.SqlBuilder.cs:line 844
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertCompare(IBuildContext context, ExpressionType nodeType, Expression left, Expression right) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\ExpressionBuilder.SqlBuilder.cs:line 1574
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertPredicate(IBuildContext context, Expression expression) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\ExpressionBuilder.SqlBuilder.cs:line 1356
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSearchCondition(IBuildContext context, Expression expression, List`1 conditions) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\ExpressionBuilder.SqlBuilder.cs:line 2515
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildWhere(IBuildContext parent, IBuildContext sequence, LambdaExpression condition, Boolean checkForSubQuery, Boolean enforceHaving) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\ExpressionBuilder.SqlBuilder.cs:line 48
   at LinqToDB.Linq.Builder.WhereBuilder.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\WhereBuilder.cs:line 23
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\ExpressionBuilder.cs:line 175
   at LinqToDB.Linq.Builder.CountBuilder.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\CountBuilder.cs:line 21
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\ExpressionBuilder.cs:line 175
   at LinqToDB.Linq.Builder.ExpressionBuilder.GetSubQuery(IBuildContext context, MethodCallExpression expr) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\ExpressionBuilder.SqlBuilder.cs:line 232
   at LinqToDB.Linq.Builder.ExpressionBuilder.GetSubQueryContext(IBuildContext context, MethodCallExpression expr) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\ExpressionBuilder.QueryBuilder.cs:line 310
   at LinqToDB.Linq.Builder.ExpressionBuilder.GetSubQueryExpression(IBuildContext context, MethodCallExpression expr, Boolean enforceServerSide) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\ExpressionBuilder.QueryBuilder.cs:line 327
   at LinqToDB.Linq.Builder.ExpressionBuilder.TransformExpression(IBuildContext context, Expression expr, Boolean enforceServerSide) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\ExpressionBuilder.QueryBuilder.cs:line 260
   at LinqToDB.Linq.Builder.ExpressionBuilder.<>c__DisplayClass74_0.<BuildExpression>b__0(Expression expr) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\ExpressionBuilder.QueryBuilder.cs:line 49
   at LinqToDB.Expressions.Extensions.Transform(Expression expr, Func`2 func) in C:\projects\linq2db\Source\LinqToDB\Expressions\Extensions.cs:line 1354
   at LinqToDB.Expressions.Extensions.Transform2[T](IEnumerable`1 source, Func`2 func) in C:\projects\linq2db\Source\LinqToDB\Expressions\Extensions.cs:line 1337
   at LinqToDB.Expressions.Extensions.Transform(Expression expr, Func`2 func) in C:\projects\linq2db\Source\LinqToDB\Expressions\Extensions.cs:line 1553
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildExpression(IBuildContext context, Expression expression, Boolean enforceServerSide) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\ExpressionBuilder.QueryBuilder.cs:line 50
   at LinqToDB.Linq.Builder.SelectContext.BuildExpression(Expression expression, Int32 level, Boolean enforceServerSide) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\SelectContext.cs:line 112
   at LinqToDB.Linq.Builder.SelectContext.BuildQuery[T](Query`1 query, ParameterExpression queryParameter) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\SelectContext.cs:line 65
   at LinqToDB.Linq.Builder.FirstSingleBuilder.FirstSingleContext.BuildQuery[T](Query`1 query, ParameterExpression queryParameter) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\FirstSingleBuilder.cs:line 105
   at LinqToDB.Linq.Builder.ExpressionBuilder.Build[T]() in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\ExpressionBuilder.cs:line 161
   at LinqToDB.Linq.Query`1.CreateQuery(IDataContext dataContext, Expression expr) in C:\projects\linq2db\Source\LinqToDB\Linq\Query.cs:line 276
   at LinqToDB.Linq.Query`1.GetQuery(IDataContext dataContext, Expression& expr) in C:\projects\linq2db\Source\LinqToDB\Linq\Query.cs:line 229
   at LinqToDB.Linq.ExpressionQuery`1.GetQuery(Expression& expression, Boolean cache) in C:\projects\linq2db\Source\LinqToDB\Linq\ExpressionQuery.cs:line 83
   at LinqToDB.Linq.ExpressionQuery`1.System.Linq.IQueryProvider.Execute[TResult](Expression expression) in C:\projects\linq2db\Source\LinqToDB\Linq\ExpressionQuery.cs:line 152
   at NewPortal.GlobalFeatures.Tasks.TaskOverview.DeployTaskInformationSummaryHeader.LoadSummary() in C:\Verismic\Projects\cms\NewPortal\GlobalFeatures\Tasks\NetDiscover\TaskOverview\DeployTaskInformationSummaryHeader.cs:line 132
   at NewPortal.GlobalFeatures.Tasks.TaskOverview.DeployTaskInformationSummaryHeader.TaskInformation_Load(Object sender, EventArgs e) in C:\Verismic\Projects\cms\NewPortal\GlobalFeatures\Tasks\NetDiscover\TaskOverview\DeployTaskInformationSummaryHeader.cs:line 93
   at Wisej.Web.UserControl.OnCreateControl()
   at Wisej.Base.ControlBase.CreateControlInternal()
   at Wisej.Base.ControlBase.CreateControl()
   at Wisej.Web.Control.CreateControl()
   at Wisej.Web.Control.ControlCollection.Add(Control child)
   at NewPortal.GlobalFeatures.Tasks.TaskOverview.TaskInformationSummary.LoadSummary() in C:\Verismic\Projects\cms\NewPortal\GlobalFeatures\Tasks\NetDiscover\TaskOverview\TaskInformationSummary.cs:line 221
   at NewPortal.GlobalFeatures.Tasks.TaskOverview.TaskInformationSummary.TaskInformation_Load(Object sender, EventArgs e) in C:\Verismic\Projects\cms\NewPortal\GlobalFeatures\Tasks\NetDiscover\TaskOverview\TaskInformationSummary.cs:line 94
   at NewPortal.HostedSubPanel.OnLoad(EventArgs e) in C:\Verismic\Projects\cms\NewPortal\Layouts\HostedSubPanel.cs:line 226
   at Wisej.Web.UserControl.OnCreateControl()
   at Wisej.Base.ControlBase.CreateControlInternal()
   at Wisej.Base.ControlBase.CreateControl()
   at Wisej.Web.Control.CreateControl()
   at Wisej.Web.Control.ControlCollection.Add(Control child)
   at NewPortal.HostedSplitBlade.DockToPanel(HostedSubPanel newPanel, Panel targetPanel) in C:\Verismic\Projects\cms\NewPortal\Layouts\HostedSplitBlade.cs:line 223
   at NewPortal.HostedSplitBlade.ChangePage(HostedSubPanel newPanel) in C:\Verismic\Projects\cms\NewPortal\Layouts\HostedSplitBlade.cs:line 158
   at NewPortal.GlobalFeatures.Tasks.TaskOverview.TaskInformation.<TaskInformation_BackgroundLoad>b__9_1(Object obj, EventArgs args) in C:\Verismic\Projects\cms\NewPortal\GlobalFeatures\Tasks\NetDiscover\TaskOverview\TaskInformation.cs:line 58
   at NewPortal.HostedSplitNavBlade.Mb_Click(Object sender, EventArgs e) in C:\Verismic\Projects\cms\NewPortal\Layouts\HostedSplitNavBlade.cs:line 226
   at NewPortal.HostedSplitNavBlade.SetDefaultSection() in C:\Verismic\Projects\cms\NewPortal\Layouts\HostedSplitNavBlade.cs:line 209
   at NewPortal.HostedBlade.HostedBlade_Appear(Object sender, EventArgs e) in C:\Verismic\Projects\cms\NewPortal\Layouts\HostedBlade.cs:line 673
```

### Steps to reproduce

```
create table MyTable (
    ID int IDENTITY(1,1) NOT NULL,
    MyOtherID INT NOT NULL,
    Status INT NOT NULL
)
```
This code is run where context is my datamodel
Even in this simple case it doesn't like the "i.Status"

```c#
var stats = (from t in context.MyTable
                             where t.MyOtherId == 12
                             group t by 1 into g
                             select new
                             {
                                 MyGroupedCount = g.Count(i => i.Status == 3),
                             }).FirstOrDefault();

```

### Environment details
linq2db version: *2.0.0*  
Database Server: *Azure SQLServer*  
Operating system: *E.g. Windows 10*  
Framework version: *.NET Framework 4.6.2*

**Comment by sdanyliv** [comment] 2018-06-20 13:14
@evanogainen, it is a known limitation and we have to find time to fix that.

BUT, you can rewrite your query in the following two ways:

#### Using existing functionality of `COUNT(expression)` function. 
You do not need grouping here.
```cs
var stats = (from t in context.MyTable
                             where t.MyOtherId == 12
                             select new
                             {
                                 MyGroupedCount = Sql.Ext.Count(i => i.Status == 3 ? 1 : null)
                             }).FirstOrDefault();
```
#### Using grouping:
```cs
var stats = (from t in context.MyTable
                             where t.MyOtherId == 12
                             group t by GroupBy.None into g
                             select new
                             {
                                 MyGroupedCount = g.CountExt(i => i.Status == 3 ? 1 : null),
                             }).FirstOrDefault();
```

**Comment by evanogainen** [comment] 2018-06-20 13:45
Thanks for your quick response.
I will try these suggestions. I have some far more complex examples, but hopefully I can work around them with this for now.

**Comment by sdanyliv** [comment] 2018-06-20 13:53
@evanogainen, don't forget that linq2db supports [Window Functions](https://linq2db.github.io/articles/sql/Window-Functions-%28Analytic-Functions%29.html), which can speedup some queries dramatically.

**Comment by sdanyliv** [comment] 2018-06-20 17:05
Duplicate of #1078

**Comment by MaceWindu** [comment] 2020-04-10 14:46
Fixed at least in v3

**Closed by MaceWindu** 2020-04-10 14:46 UTC
Labels: status: has-tests, type: bug
