### ISSUE TITLE
PostgreSQL Test Problem Associations with Concat/Union or other Set operations are not supported. (v3.3.0)

### ISSUE THREAD

**Issue by sasukevita** [linq2db/linq2db#2966] opened 2021-04-22 03:55 UTC
<details>
<summary>Model</summary>

```C#

	[Table(Schema="Member", Name="Table")]
	public partial class Table
	{
		[PrimaryKey, NotNull    ] public int      Id       { get; set; } // integer
		[Column,     NotNull    ] public DateTime Date     { get; set; } // date
		[Column,     NotNull    ] public TimeSpan Time     { get; set; } // time without time zone
		[Column,        Nullable] public int?     StatusId { get; set; } // integer

		#region Associations

		/// <summary>
		/// FK_Table_TableStatus
		/// </summary>
		[Association(ThisKey="StatusId", OtherKey="StatusId", CanBeNull=true, Relationship=LinqToDB.Mapping.Relationship.ManyToOne, KeyName="FK_Table_TableStatus", BackReferenceName="Table")]
		public TableStatus TableStatus { get; set; }

		#endregion
	}
	
	[Table(Schema="Member", Name="TableStatus")]
	public partial class TableStatus
	{
		[PrimaryKey, NotNull] public int    StatusId   { get; set; } // integer
		[Column,     NotNull] public string StatusName { get; set; } // character varying

		#region Associations

		/// <summary>
		/// FK_Table_TableStatus_BackReference
		/// </summary>
		[Association(ThisKey="StatusId", OtherKey="StatusId", CanBeNull=true, Relationship=LinqToDB.Mapping.Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<Table> Table { get; set; }

		#endregion
	}
```
</details>
Sample test using 0 row data

Test:
```C#
            IQueryable<Table> query = null;
            int[] Ids = new[] { 1, 2 };
            foreach (int Id in Ids)
            {
                var q = from x in db.Table
                        where x.Id == Id
                        select x;
                if (query == null)
                {
                    query = q;
                }
                else
                {
                    query = query.Concat(q);
                }
            }

            var query2 = (from x in query
                          select new
                          {
                              Id = x.Id,
                          });
            query2.ToArray();//Works

            var query3 = (from x in query
                          select new
                          {
                              Id = x.Id,
                              StatusName = x.TableStatus.StatusName,
                          });
            query3.ToArray();//LinqToDB.LinqToDBException: 'Associations with Concat/Union or other Set operations are not supported.'
```

### Environment details
linq2db version: 3.3.0
Database: PostgreSQL 12.1
.NET Framework: 4.7.2

**Comment by sdanyliv** [comment] 2021-04-22 04:20
What is wrong with error message?  You cannot use associations after concat.

**Comment by sasukevita** [comment] 2021-04-22 04:29
im migrating my code from ef to linq2db, is there way for me to resolve this?

**Comment by sdanyliv** [comment] 2021-04-22 04:38
Include StatusName earlier into each Concat projection. Or make manual join to TableStatus.
It is known limitation and i hope i can solve it in the nearest future.

**Comment by sasukevita** [comment] 2021-04-22 07:25
> 
> 
> Include StatusName earlier into each Concat projection. Or make manual join to TableStatus.
> It is known limitation and i hope i can solve it in the nearest future.

thanks it worked for temporary fix
```C#

            var query3 = (from x in query
                          join y in db.TableStatus on x.StatusId equals y.StatusId
                          select new
                          {
                              Id = x.Id,
                              StatusName = y.StatusName,
                          });
            query3.ToArray();//Works
```

**Comment by MaceWindu** [comment] 2021-11-23 14:28
Duplicate of #2461

**Closed by MaceWindu** 2021-11-23 14:28 UTC
Labels: area: set
