### ISSUE TITLE
Error during model generation: Null or empty full-text predicate. 

### ISSUE THREAD

**Issue by n9** [linq2db/linq2db#761] opened 2017-07-04 15:36 UTC
I've tried to generate model by SqlServer template. It generates:

```C#
		#region Table Functions

		#region FooFunction

// Use 'GenerateProcedureErrors=false' to disable errors.
#error Null or empty full-text predicate.

		#endregion

		#endregion
```

The `FooFunction` is a table valued function:

```SQL
CREATE FUNCTION [dbo].[FooFunction]
(
    @term nvarchar(4000)
)
RETURNS TABLE
AS
RETURN SELECT * FROM FREETEXTTABLE(FooTable, *, @term);
```

According to the error, it looks like that generator invokes the `FooFunction` during building the model.

### Environment details
linq2db version: *1.8.2*  
Database Server: *SQL Server 2014*  
Operating system: *Windows 10*  
Framework version: *.NET Framework 4.7*

**Comment by sdanyliv** [comment] 2017-10-06 12:38
It is duplicate of #449

**Comment by MaceWindu** [comment] 2019-02-16 13:45
Duplicate of #449

Please use referenced issue to track it

**Comment by MaceWindu** [comment] 2019-02-16 13:46
Duplicate of #449

**Closed by MaceWindu** 2019-02-16 13:45 UTC
Labels: area: T4, type: bug
