### ISSUE TITLE
Generating Postgres DbContext from TT fails after adding linq2db.MySql

### ISSUE THREAD

**Issue by MeNoln** [linq2db/linq2db#2486] opened 2020-09-14 16:50 UTC
I have .tt file which generates db context from my postgresql database.
```
<#@ template language="C#" debug="True" hostSpecific="True"                            #>
<#@ output extension=".generated.cs"                                                   #>
<#@ include file="$(LinqToDBT4PostgreSQLTemplatesDirectory)LinqToDB.PostgreSQL.Tools.ttinclude" #>
<#@ include file="$(LinqToDBT4PostgreSQLTemplatesDirectory)PluralizationService.ttinclude"      #>
<# //@ include file="$(ProjectDir)LinqToDB.Templates\LinqToDB.PostgreSQL.Tools.ttinclude" #>
<# //@ include file="$(ProjectDir)LinqToDB.Templates\PluralizationService.ttinclude"      #>
<#

	NamespaceName = "Sample.Persistence";
	DataContextName = "ApplicationContext";
	GenerateConstructors = false;
	GenerateDataTypes = true;
	GenerateLengthProperty = false;
	GeneratePrecisionProperty = false;
	GenerateScaleProperty = false;
	GenerateBackReferences = false;

	LoadPostgreSQLMetadata("localhost", "5432", "mydb", "postgres", "1234");
	
	GenerateModel();
#>
```

.csproj 
```
<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="linq2db" Version="3.1.0" />
        <PackageReference Include="linq2db.AspNet" Version="3.1.0" />
        <PackageReference Include="linq2db.PostgreSQL" Version="3.1.0" />
        <PackageReference Include="Npgsql" Version="4.1.4" />
    </ItemGroup>

    <ItemGroup>
      <None Update="file.tt">
        <Generator>TextTemplatingFileGenerator</Generator>
        <LastGenOutput>statistics.generated.cs</LastGenOutput>
      </None>
    </ItemGroup>

    <ItemGroup>
      <Compile Update="context.generated.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>statistics.tt</DependentUpon>
      </Compile>
    </ItemGroup>

</Project>

```
### Exception I've got after this step
```
 System.InvalidOperationException: Cannot load assembly Npgsql
   в LinqToDB.DataProvider.PostgreSQL.NpgsqlProviderAdapter.GetInstance()
   в LinqToDB.DataProvider.PostgreSQL.PostgreSQLDataProvider..ctor(String name, PostgreSQLVersion version)
   в LinqToDB.DataProvider.PostgreSQL.PostgreSQLTools.<>c.<.cctor>b__19_0()
   в System.Lazy`1.CreateValue()
--- End of stack trace ---
   в System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   в System.Lazy`1.get_Value()
   в LinqToDB.DataProvider.PostgreSQL.PostgreSQLTools.GetDataProvider(PostgreSQLVersion version)
   в LinqToDB.DataProvider.PostgreSQL.PostgreSQLTools.CreateDataConnection(String connectionString, PostgreSQLVersion version)
   at Microsoft.VisualStudio.TextTemplating8CB405D03067BD3A63A71FD24F3E83DF68800789EEFC678B7C292660E21C62F36524C392FCF4FE7970BD969A732F8F9A12DF788F17BF70BCBCEC71A3B734FD08.GeneratedTextTransformation.GetPostgreSQLConnection(String connectionString) at C:\Users\PC\.nuget\packages\linq2db.postgresql\3.1.0\build\..\contentFiles\any\any\LinqToDB.Templates\LinqToDB.PostgreSQL.ttinclude:line 130
   at Microsoft.VisualStudio.TextTemplating8CB405D03067BD3A63A71FD24F3E83DF68800789EEFC678B7C292660E21C62F36524C392FCF4FE7970BD969A732F8F9A12DF788F17BF70BCBCEC71A3B734FD08.GeneratedTextTransformation.GetPostgreSQLConnection(String server, String port, String database, String uid, String password) в C:\Users\PC\.nuget\packages\linq2db.postgresql\3.1.0\build\..\contentFiles\any\any\LinqToDB.Templates\LinqToDB.PostgreSQL.ttinclude:at 135
   at Microsoft.VisualStudio.TextTemplating8CB405D03067BD3A63A71FD24F3E83DF68800789EEFC678B7C292660E21C62F36524C392FCF4FE7970BD969A732F8F9A12DF788F17BF70BCBCEC71A3B734FD08.GeneratedTextTransformation.LoadPostgreSQLMetadata(String server, String port, String database, String uid, String password) в C:\Users\PC\.nuget\packages\linq2db.postgresql\3.1.0\build\..\contentFiles\any\any\LinqToDB.Templates\LinqToDB.PostgreSQL.ttinclude:at 146
   at Microsoft.VisualStudio.TextTemplating8CB405D03067BD3A63A71FD24F3E83DF68800789EEFC678B7C292660E21C62F36524C392FCF4FE7970BD969A732F8F9A12DF788F17BF70BCBCEC71A3B734FD08.GeneratedTextTransformation.TransformText() at C:\projects\Sample.Persistence\context.tt:line 48		C:\Users\PC\.nuget\packages\linq2db.postgresql\3.1.0\build\..\contentFiles\any\any\LinqToDB.Templates\LinqToDB.PostgreSQL.ttinclude	130	

```

### Steps to reproduce
1. Create tt file to generate context from simple PostgresSQL database.
2. Add following packages:
```
<PackageReference Include="linq2db" Version="3.1.0" />
<PackageReference Include="linq2db.AspNet" Version="3.1.0" />
<PackageReference Include="linq2db.PostgreSQL" Version="3.1.0" />
<PackageReference Include="Npgsql" Version="4.1.4" />
```
3. Generate db context.
4. Add `linq2db.MySql 3.1.0` 
5. Re-generate context from .tt file

**Comment by MaceWindu** [comment] 2020-09-15 07:34
duplicate of #2485

**Closed by MaceWindu** 2020-09-15 07:34 UTC
