### ISSUE TITLE
GroupBy - not supported exception

### ISSUE THREAD

**Issue by integral-llc** [linq2db/linq2db#672] opened 2017-05-21 02:33 UTC
Given such a LINQ query 
```cs
IQueryable<GFDDataModels.Stone> stones;
stones = from s in _dataContext.Stone where s.Enabled == true select s;

stones = from s in stones
              where !s.Name.StartsWith("level - ") && s.ImageFullUrl.Length > 0
              group s by s.Name
              into sG
              select sG.First();

var list = stones.ToList();
```
it fails with the exception.
`"The method or operation is not implemented."`

Stack Trace:
```
   at LinqToDB.Linq.Builder.GroupByBuilder.GroupByContext.ConvertToSql(Expression expression, Int32 level, ConvertFlags flags) in c:\projects\linq2db\Source\Linq\Builder\GroupByBuilder.cs:line 520
   at LinqToDB.Linq.Builder.SelectContext.<>c__DisplayClass21.<ConvertToSql>b__13(IBuildContext ctx, Expression ex, Int32 l) in c:\projects\linq2db\Source\Linq\Builder\SelectContext.cs:line 284
   at LinqToDB.Linq.Builder.SelectContext.ProcessScalar[T](Expression expression, Int32 level, Func`4 action, Func`1 defaultAction) in c:\projects\linq2db\Source\Linq\Builder\SelectContext.cs:line 890
   at LinqToDB.Linq.Builder.SelectContext.ConvertToSql(Expression expression, Int32 level, ConvertFlags flags) in c:\projects\linq2db\Source\Linq\Builder\SelectContext.cs:line 281
   at LinqToDB.Linq.Builder.SelectContext.<>c__DisplayClass21.<ConvertToSql>b__13(IBuildContext ctx, Expression ex, Int32 l) in c:\projects\linq2db\Source\Linq\Builder\SelectContext.cs:line 284
   at LinqToDB.Linq.Builder.SelectContext.ProcessScalar[T](Expression expression, Int32 level, Func`4 action, Func`1 defaultAction) in c:\projects\linq2db\Source\Linq\Builder\SelectContext.cs:line 917
   at LinqToDB.Linq.Builder.SelectContext.ConvertToSql(Expression expression, Int32 level, ConvertFlags flags) in c:\projects\linq2db\Source\Linq\Builder\SelectContext.cs:line 281
   at LinqToDB.Linq.Builder.ExpressionContext.ConvertToSql(Expression expression, Int32 level, ConvertFlags flags) in c:\projects\linq2db\Source\Linq\Builder\ExpressionContext.cs:line 48
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertToSql(IBuildContext context, Expression expression, Boolean unwrap) in c:\projects\linq2db\Source\Linq\Builder\ExpressionBuilder.SqlBuilder.cs:line 823
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertExpressions(IBuildContext context, Expression expression, ConvertFlags queryConvertFlag) in c:\projects\linq2db\Source\Linq\Builder\ExpressionBuilder.SqlBuilder.cs:line 619
   at LinqToDB.Linq.Builder.OrderByBuilder.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo) in c:\projects\linq2db\Source\Linq\Builder\OrderByBuilder.cs:line 49
   at LinqToDB.Linq.Builder.MethodCallBuilder.BuildSequence(ExpressionBuilder builder, BuildInfo buildInfo) in c:\projects\linq2db\Source\Linq\Builder\MethodCallBuilder.cs:line 22
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo) in c:\projects\linq2db\Source\Linq\Builder\ExpressionBuilder.cs:line 177
   at LinqToDB.Linq.Builder.CountBuilder.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo) in c:\projects\linq2db\Source\Linq\Builder\CountBuilder.cs:line 21
   at LinqToDB.Linq.Builder.MethodCallBuilder.BuildSequence(ExpressionBuilder builder, BuildInfo buildInfo) in c:\projects\linq2db\Source\Linq\Builder\MethodCallBuilder.cs:line 22
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo) in c:\projects\linq2db\Source\Linq\Builder\ExpressionBuilder.cs:line 177
   at LinqToDB.Linq.Builder.ExpressionBuilder.Build[T]() in c:\projects\linq2db\Source\Linq\Builder\ExpressionBuilder.cs:line 148
   at LinqToDB.Linq.Query`1.GetQuery(IDataContextInfo dataContextInfo, Expression expr) in c:\projects\linq2db\Source\Linq\Query.cs:line 165
   at LinqToDB.Linq.ExpressionQuery`1.GetQuery(Expression expression, Boolean cache) in c:\projects\linq2db\Source\Linq\ExpressionQuery.cs:line 89
   at LinqToDB.Linq.ExpressionQuery`1.System.Linq.IQueryProvider.Execute[TResult](Expression expression) in c:\projects\linq2db\Source\Linq\ExpressionQuery.cs:line 142
   at System.Linq.Queryable.Count[TSource](IQueryable`1 source)
   at GFD.DB.BL.Stone.GetMaterial(Int32 fabricatorId, String name, String tag, Int32 page, Int32 perPage) in D:\QuoteGranite\src\Main\gfd\GFD.DB\BL\Stone.BL.cs:line 105
   at gfd.Controllers.Api.QuoteCountertopsController.<>c__DisplayClass4_0.<GetMaterial>b__0(GFDDataContext context, AuthModel auth, IDependencyResolver depRes) in D:\QuoteGranite\src\Main\gfd\gfd\Controllers\Api\QuoteCountertopsController.cs:line 87
   at gfd.Controllers.Api.BaseApiController.Do(Func`4 a) in D:\QuoteGranite\src\Main\gfd\gfd\Controllers\Api\BaseApiController.cs:line 146
```

**Comment by integral-llc** [comment] 2017-05-21 02:34
Forgot tp say, the same query works beautifully in EntittyFramework  which generates such a SQL

`
SELECT [t3].[test], [t3].[Id], [t3].[Name], [t3].[Enabled], [t3].[Created], [t3].[Modified], [t3].[CreatedBy_id], [t3].[ModifiedBy_id], [t3].[Tags], [t3].[Description], [t3].[ImageUrl], [t3].[ImageFullUrl], [t3].[Aliases], [t3].[LongDescription]
FROM (
    SELECT [t0].[Name]
    FROM [Stone] AS [t0]
    WHERE (NOT ([t0].[Name] LIKE @p0)) AND (LEN([t0].[ImageFullUrl]) > @p1) AND ([t0].[Enabled] = @p2)
    GROUP BY [t0].[Name]
    ) AS [t1]
OUTER APPLY (
    SELECT TOP (1) 1 AS [test], [t2].[Id], [t2].[Name], [t2].[Enabled], [t2].[Created], [t2].[Modified], [t2].[CreatedBy_id], [t2].[ModifiedBy_id], [t2].[Tags], [t2].[Description], [t2].[ImageUrl], [t2].[ImageFullUrl], [t2].[Aliases], [t2].[LongDescription]
    FROM [Stone] AS [t2]
    WHERE ([t1].[Name] = [t2].[Name]) AND (NOT ([t2].[Name] LIKE @p3)) AND (LEN([t2].[ImageFullUrl]) > @p1) AND ([t2].[Enabled] = @p2)
    ) AS [t3]
ORDER BY [t3].[Name]
`

**Comment by sdanyliv** [comment] 2017-05-22 14:38
@integral-llc, i can not reproduce. Please post GFDDataModels.Stone class definition and maybe parent classes.

**Comment by integral-llc** [comment] 2017-05-22 17:19
Here it is. I've also tried in LinqPad with latest Linq2Db driver and got the same issue. 
`
	[Table(Schema="dbo", Name="Stone")]
	public partial class Stone
	{
		[PrimaryKey, Identity   ] public int             Id              { get; set; } // int
		[Column,     NotNull    ] public string          Name            { get; set; } // nvarchar(256)
		[Column,        Nullable] public bool?           Enabled         { get; set; } // bit
		[Column,        Nullable] public DateTimeOffset? Created         { get; set; } // datetimeoffset(7)
		[Column,        Nullable] public DateTimeOffset? Modified        { get; set; } // datetimeoffset(7)
		[Column,        Nullable] public int?            CreatedBy_id    { get; set; } // int
		[Column,        Nullable] public int?            ModifiedBy_id   { get; set; } // int
		[Column,        Nullable] public string          Tags            { get; set; } // nvarchar(512)
		[Column,        Nullable] public string          Description     { get; set; } // nvarchar(512)
		[Column,        Nullable] public string          ImageUrl        { get; set; } // nvarchar(255)
		[Column,        Nullable] public string          ImageFullUrl    { get; set; } // nvarchar(255)
		[Column,        Nullable] public string          Aliases         { get; set; } // nvarchar(1024)
		[Column,        Nullable] public string          LongDescription { get; set; } // nvarchar(2048)
}
`

**Comment by sdanyliv** [comment] 2017-05-23 14:43
@integral-llc, i can not reproduce exception, but!
Yes it is not trivial for our Expression parser and optimizer. I suggest to rewrite this query in more optimal way for SQL Server
```c#
IQueryable<Stone> stones;
stones = from s in db.GetTable<Stone>() where s.Enabled == true select s;
var names = (from s in stones
	where !s.Name.StartsWith("level - ") && s.ImageFullUrl.Length > 0
	orderby s.Name
	select s.Name).Take(1);

stones = from s in stones
	join n in names on s.Name equals n
	select s;

var list = stones.ToList();
```
It produces the following query:
```sql
SELECT
	[s].[Id],
	[s].[Name],
	[s].[Enabled],
	[s].[Created],
	[s].[Modified],
	[s].[CreatedBy_id],
	[s].[ModifiedBy_id],
	[s].[Tags],
	[s].[Description],
	[s].[ImageUrl],
	[s].[ImageFullUrl],
	[s].[Aliases],
	[s].[LongDescription]
FROM
	[dbo].[Stone] [s]
		INNER JOIN (
			SELECT TOP (1)
				[t1].[Name] as [Name1]
			FROM
				[dbo].[Stone] [t1]
			WHERE
				[t1].[Enabled] = 1 AND [t1].[Name] NOT LIKE N'level - %' AND
				Len([t1].[ImageFullUrl]) > 0
			ORDER BY
				[t1].[Name]
		) [n] ON [s].[Name] = [n].[Name1]
WHERE
	[s].[Enabled] = 1
```

**Comment by MaceWindu** [comment] 2020-02-07 09:35
retested in #1945. There is no crash, but also we produce multiple queries now due to group by implementation limitations. Something to improve in post3.0 releases

**Comment by MaceWindu** [comment] 2020-03-25 13:26
retest needed

**Comment by MaceWindu** [comment] 2020-03-25 15:34
No changes for groupby behavior yet

**Comment by MaceWindu** [comment] 2020-04-07 19:36
I'm going to close it, as original issue fixed, and requirement to set `GuardGrouping = false` is valid with current implementation

**Closed by MaceWindu** 2020-04-07 19:36 UTC
Labels: area: linq, epic: eager-load, status: has-tests, type: bug
