### ISSUE TITLE
Linq2Db is trying to do rollback on "invalid" MySQL connection

### ISSUE THREAD

**Issue by erikfroseth** [linq2db/linq2db#1991] opened 2019-11-28 17:21 UTC
Hi,

When certain error happens inside a MySQL transaction, it seems like Linq2Db tries to do a rollback on an invalid connection. It throws the following exception: 

> Connection must be valid and open to rollback transaction

I'm not 100% sure what the correct behavior is here, but the exception seems odd. Here is a reproducible case:

```
# Set up a test schema/table.
CREATE SCHEMA test123;
USE test123;
CREATE TABLE my_table (column INTEGER);
```
```
  public class Program
  {
    [Table("my_table")]
    public class MyTable
    {
      [Column("column")]
      public int Column { get; set; }
    }

    public class Model : DataConnection
    {
      public Model(string connectionString)
        : base(new LinqToDB.DataProvider.MySql.MySqlDataProvider(),
            connectionString)
      { }
      public ITable<MyTable> TheTable { get { return GetTable<MyTable>(); } }
    }

    private static string GetConnectionString()
    {
      var connstring = new MySql.Data.MySqlClient.MySqlConnectionStringBuilder();
      connstring.UserID = "yourusername";
      connstring.Server = "yourserver";
      connstring.Database = "test123";
      connstring.Password = "yourpassword";
      connstring.DefaultCommandTimeout = 5;
      return connstring.ConnectionString;
    }

    static void RunTest()
    {
      var lockTablesSignal = new AutoResetEvent(false);
      var thread1 = new Thread(() =>
      {
        using (var connection = new Model(GetConnectionString()))
        {
          connection.Execute("LOCK TABLE my_table WRITE;");

          // Signal the other thread that it can start.
          lockTablesSignal.Set();
          Thread.Sleep(TimeSpan.FromSeconds(10));
        }
      });

      var thread2 = new Thread(() =>
      {
        try
        {
          using (var connection = new Model(GetConnectionString()))
          using (var transaction = connection.BeginTransaction())
          {
            var data = connection.TheTable.ToList();
          }
        }
        catch (Exception ex)
        {
          // Observe the exception here!
        }
      });

      thread1.Start();

      // Wait for the signal from thread 1 before launching thread 2.
      lockTablesSignal.WaitOne();
      thread2.Start();

      thread1.Join();
      thread2.Join();
    }


    static void Main(string[] args)
    {
      RunTest();
    }
```

**Comment by MaceWindu** [comment] 2019-11-29 08:22
If I understand it correctly, there is nothing wrong with linq2db behavior. You have transaction scope, defined by `using` and on exit from this scope we rollback uncommited transaction despite of exit reason - normal execution flow or exception.

If we wan't to change this behavior we have two options and I don't really like both of them:
- detect that transaction is not alive anymore and don't call rollback. There is no ADO.NET or provider-specific API to detect it and even if it will be, it could require roundtrip to database, so it doesn't make any sense to do it.
- catch exception from rollback and.... what next? we cannot just swallow it like nothing happend

I've re-read your question again - maybe this specific case could be detected by checking Connection.State property, but still I don't see a reason to change current behavior - if connection is broken, it means something wrong happened and throwing exception on rollback to indicate it (with actually good error message from provider) looks like proper behavior to me.

**Comment by erikfroseth** [comment] 2019-11-29 08:41
I agree that there is nothing wrong per se going on here. I just noticed that if I use the mysql connector directly instead of using linq2db, I don't get the samme exception. It seems like they are, like you mentioned, checking the Connection.State property before rollback. This is a snippet from their implementation of Disposing (found here: https://github.com/mysql/mysql-connector-net/blob/6.9/Source/MySql.Data/transaction.cs ):

```
  if ((conn != null && conn.State == ConnectionState.Open || conn.SoftClosed) && open)
          Rollback();
```

Does it make sense to do something similar before calling rollback in linq2db?

**Comment by MaceWindu** [comment] 2019-11-29 09:29
Probably we can do it for non-explicit rollback call from transaction dispose, but I need to think about it - it is kind of a breaking change.

**Comment by MaceWindu** [comment] 2022-12-07 11:57
duplicate of #3863 (probably)

**Closed by MaceWindu** 2022-12-07 11:57 UTC
Labels: type: discussion
