### ISSUE TITLE
Linq2DB adding unnecessary statements to query when grouping by two parts of a date.

### ISSUE THREAD

**Issue by dimensional-difficulties** [linq2db/linq2db#644] opened 2017-04-27 19:32 UTC
I am trying to generate a query that gets the number of entries with dates that occur within each given month. The SQL form of the query I wish to generate goes like this:

```sql
SELECT
DatePart(Year, [t1].[StartTime]) as Year,
DatePart(Month, [t1].[StartTime]) as Month,
Count(*) as 'Visits',
Sum([t1].[PageCount]) as 'Total Pageviews'
FROM
[MyDatabase] [t1]
GROUP BY
DatePart(Year, [t1].[StartTime]),
DatePart(Month, [t1].[StartTime])
```
I tried the following Linq2DB code:

```cs
var query = from table in dataContext.MyDataContext(tablePath)
group table by new { table.StartTime.Year, table.StartTime.Month} into grp
select new { Month = grp.Key.Month, Year = grp.Key.Year,
TotalVisitors =   grp.Count(), 
TotalPageviews = grp.Sum(table2 => table2.PageCount) };
```
but the SQL query being generated by this is

```sql
--  SqlServer.2008  --
SELECT
[t1].[StartTime],
Count(*) as [c1],
Sum([t1].[PageCount]) as [c2]
FROM
[MyDatabase] [t1]
GROUP BY
DatePart(Year, [t1].[StartTime]),
DatePart(Month, [t1].[StartTime]),
[t1].[StartTime]
```
Why is [t1].[StartTime] rather than the month or year? And why is it grouping by that extra [t1].[StartTime] at the end? How do I generate the SQL query I have above using Linq2DB?

**Comment by MaceWindu** [comment] 2017-04-27 19:44
Looks like a bug. As a workaround while it is not fixed you can use Sql.ExpressionAttribute like this:

```
[Sql.Expression("YEAR({0})", PreferServerSide = true)]
public static int ByYear(DateTime date)
{
        return date.Year;
}
```

**Comment by sdanyliv** [comment] 2017-04-28 10:38
It is a long standing bug. We also have two disabled unit tests GroupByDate1, and GroupByDate2.
I've tried to fix (3 days!) this but without success. It is a part of ExpressionBuilder class - it is full of workarounds in implementation.
Same issues here #621, #264

**Comment by dimensional-difficulties** [comment] 2017-04-28 13:23
Thank you very much.  I assume I can also use 
        [Sql.Expression("MONTH({0})", PreferServerSide = true)]
        public static int ByMonth(DateTime date)
        {
            return date.Month;
        }

I am having a bit of trouble using both of these in a .GroupBy statement though...

**Comment by sdanyliv** [comment] 2017-04-28 13:32
@dimensional-difficulties, i have another solution. It works but not so clear as expected
Use function `Sql.AsSql`
```cs
var query = from table in dataContext.MyDataContext(tablePath)
group table by new { table.StartTime.Year, table.StartTime.Month} into grp
select new { Month = Sql.AsSql(grp.Key.Month), Year = Sql.AsSql(grp.Key.Year),
TotalVisitors =   grp.Count(), 
TotalPageviews = grp.Sum(table2 => table2.PageCount) };
```

**Comment by sdanyliv** [comment] 2017-04-28 15:30
Duplicate of #264

**Closed by sdanyliv** 2017-04-28 15:30 UTC
