### ISSUE TITLE
FromSqlScalar - parameters in  FormattableString not set

### ISSUE THREAD

**Issue by HypeillingerChillinger** [linq2db/linq2db#3782] opened 2022-09-22 07:26 UTC
The statement written for ``` FromSqlScalar``` in a ```FormattableString``` is not created correctly

```c#
FormattableString statement = $"SELECT IIF(EXISTS(SELECT + FROM [INFORMATION_SCHEMA].[TABLES] [x] WHERE [x].[TABLE_NAME] = '{MyStringConstants.MyTableNameStringConstant}'),1,0)";

var tableExists = await context.FromSqlScalar<bool>(statement).AnyAsync();
```
The query returns zero since the ```MyTableNameStringConstant``` string is not resolved correctly.

The parameters are not replaced correctly. Found it out by looking at the query history in the database because (other bug)

```c#
context.InlineParameters = true; 
```
throws an exception for this statement.

**Comment by MaceWindu** [comment] 2024-07-21 16:30
There are some issues with this example, but probably not one you had.
Would be nice to have proper SQL as your statement is not correct (e.g. `SELECT + FROM`).

**Comment by HypeillingerChillinger** [comment] 2024-08-04 11:13
Ok tried to simplify the query.

We want to use
```public static IQueryable<TEntity> FromSqlScalar<TEntity>(this IDataContext dataContext, [SqlFormattableComparer] FormattableString sql)```

```c#
using var context2 = ContextFactory.Create();

context2.InlineParameters = true;

FormattableString statement = $"SELECT * FROM INFORMATION_SCHEMA.TABLES x WHERE x.TABLE_NAME = '{Bla.MyTableNameStringConstant}'";

// crashes here 
var tableExists = await context2.FromSqlScalar<bool>(statement).AnyAsync();

var sdf = context2.LastQuery;



Postgres
Linq2DbVersion 5.4.1

**Comment by MaceWindu** [comment] 2024-08-04 12:12
linq2db process FormattableString parameters and convert `{Bla.MyTableNameStringConstant}` to string parameter/literal automatically, you don't need to add extra quotes as it will result in invalid SQL `''file''`

**Comment by HypeillingerChillinger** [comment] 2024-08-04 12:31
Cannot convert value 'System.Object[]: System.Object[]' to type 'System.Boolean'

With your advice

**Comment by MaceWindu** [comment] 2024-08-04 12:35
Hmm, sounds like same as #2779 which is strange as you use `FromSqlScalar`, not `FromSql`

**Comment by MaceWindu** [comment] 2024-11-14 15:00
DUplicate of #3782

**Closed by MaceWindu** 2024-11-14 15:00 UTC
Labels: type: bug, status: has-tests
