### ISSUE TITLE
PostgreSQL connection leak

### ISSUE THREAD

**Issue by breakingthings** [linq2db/linq2db#251] opened 2015-08-17 10:35 UTC
Seems that the connection leak problem is back with 1.0.7.2. When pooling is enabled subquery connections are not released. Haven't had time to debug it properly but it seems to me the problem is somewhere in QueryContext. Thanks in advance. I'll try to debug when time is available.

**Comment by igor-tkachev** [comment] 2015-08-20 02:34
Cant reproduce.

**Comment by breakingthings** [comment] 2015-08-28 12:05
Hi,

I tried debugging but I'm quite lost here. Semes like npgsql connection clones itself somehow without using DataConnection constructor or Clone method. The offending query is here

 LinqToDB.Common.Configuration.Linq.AllowMultipleQuery = true;
                using (var db = new Db())
                {
                    var result = db.GetTable<Application>()
                        .LoadWith(x => x.Admission)
                        .LoadWith(x => x.User)
                        .LoadWith(x => x.Admission.Institution)
                        .LoadWith(x => x.Admission.MinimumRequiredEhisLevel)
                        .LoadWith(x => x.ApplicationStatus)
                        .LoadWith(x => x.Admission.StudyLevelGroup)
                        .LoadWith(x => x.Admission.AdmissionStatus)
                        .LoadWith(x => x.StudyForm)
                        .Where(x => (userId == null || x.UserId == userId) &&
                            x.Archived == null && x.Id == id)
                        .Select(app => new
                        {
                            Application = app,
                            CandidateApplicationExams = db.GetTable<CandidateApplicationExam>()
                                .Where(y => y.ApplicationId == app.Id && y.Archived == null),
                            ApplicationFormSettings = db.GetTable<ApplicationFormSettings>()
                                .Where(y => y.AdmissionId == app.AdmissionId && y.Archived == null)
                        }).FirstOrDefault();

                    Application application = result.Application;
                    application.CandidateApplicationExams = new List<CandidateApplicationExam>();
                    foreach (var appExam in result.CandidateApplicationExams)
                    {
                        var candidateApplicationExam = db.GetTable<CandidateApplicationExam>()
                                .LoadWith(x => x.AdmissionExamSchedule)
                        .FirstOrDefault(x => x.Id == appExam.Id && x.Archived == null);
                        application.CandidateApplicationExams.Add(candidateApplicationExam);
                    }

                    application.ApplicationFormSettings = new List<ApplicationFormSettings>();
                    foreach (var appFormSettings in result.ApplicationFormSettings)
                    {
                        var applicationFormSetting = db.GetTable<ApplicationFormSettings>()
                                .LoadWith(x => x.FormField)
                        .FirstOrDefault(x => x.Id == appFormSettings.Id && x.Archived == null);
                        application.ApplicationFormSettings.Add(applicationFormSetting);
                    }

                    return application;
                }

after returning  from this method I have 1 connection leak.

**Comment by breakingthings** [comment] 2015-08-30 06:40
Hi again - the source of the problem seems to be that disposed DataConnection object is still being used which creates new connection in "Connection" property (Line 485) 
 if (_connection == null)
      _connection = DataProvider.CreateConnection(ConnectionString);

Pooling has nothing to do with this problem - my bad.

I can easily get exception with following patch http://pastebin.com/xKdRYaim
which throws exception when Connection property of disposed object is accessed.

**Comment by sdanyliv** [comment] 2017-02-27 20:10
@breakingthings, it is because ofcurrent implementation of LoadWith. It is not designed like in EF, when you enumerate record additional queries are executed. When connection is closed it may have undefined behaviour.

**Closed by sdanyliv** 2017-02-27 20:10 UTC
