### ISSUE TITLE
How to insert multiple entities with child items?

### ISSUE THREAD

**Issue by unacceptablepepper** [linq2db/linq2db#2893] opened 2021-03-15 21:40 UTC
Similar to https://github.com/linq2db/linq2db/issues/2864 

How I can insert multiple parent entities that have child items?
I have a list of parent entities and each have nested list of child items.

`BulkCopy` don't return back new ids. `InsertIntoWithOutput` require to create/insert date to temp table before insert.

Is it possible to insert multiple parent entities in single request and get back primary keys for new rows?

Thank you

**Comment by sdanyliv** [comment] 2021-03-16 09:17
For postgresql `InsertWithOutput` is not supported. So probably you have to insert all master records one-by-one and retrieve generated Ids via `InsertWithIdentity` method.

**Comment by MaceWindu** [comment] 2024-07-16 17:29
Duplicate of #2960

**Closed by MaceWindu** 2024-07-16 17:29 UTC
