### ISSUE TITLE
SqlCeSqlOptimizer with SqlTableType.Expression destroys table alias and causes NRE

### ISSUE THREAD

**Issue by detoxhby** [linq2db/linq2db#700] opened 2017-05-31 21:07 UTC
Using UpdatableQuery with SqlCe provider on any source that is a `SqlTableType.Expression` ( for ex.: `table.With("TABLOCK")`) causes table alias reset to `$` ... and finally a nullref exception when building the actual update expression where alias is null.

The root of the problem lies inside `SqlCeSqlOptimizer.Finalize()`
```cs
case QueryType.Update :
	selectQuery = GetAlternativeUpdate(selectQuery);
```

The selectQuery before this call contains the correct t1 alias, but at the end of `GetAlternativeUpdate()` there is a `selectQuery.From.Tables[0].Alias = "$";` --> this is fine as we need to remove alias for UPDATE queries but for this specific case we always need the alias caused by LINQ build of With.

---

Using normal SqlServer provider works correctly.

**Comment by ili** [comment] 2017-06-02 05:30
@detoxhby can you please provide minimal sample?

**Comment by detoxhby** [comment] 2017-06-02 13:12
@ili yes, probably today or tomorrow

**Comment by ili** [comment] 2017-06-02 13:19
@detoxhby that would be great if today, we are planning to release 1.8.1 tomorrow, so may be we can include the fix

**Comment by ili** [comment] 2017-06-02 14:08
It looks like i'v reproduced the issue and fixed in #704

**Comment by detoxhby** [comment] 2017-06-02 15:10
@ili Seems good! (gonna test it out tonight asap I can)

**Comment by detoxhby** [comment] 2017-06-02 16:06
@ili Just tested it and works correctly, thanks!

**Closed** 2017-06-03 05:12 UTC
Labels: bug, linq
