### ISSUE TITLE
Unable to write to JSON column in postgresql, but can read value.

### ISSUE THREAD

**Issue by exocom** [linq2db/linq2db#432] opened 2016-09-10 19:29 UTC
We've run into an issue where we are unable to write to a postgresql JSON column. Might be related to #363 and #313. The Npgsql library says that it has support for json, but we're not able to locate where the bug actually occurs.

The good news is that we can read the value as a string just fine.

Here is an example of our code

``` c#
[Table]
public class People
{
   [PrimaryKey, Identity]
   public int Id { get; set; }

  [Column]
  public string Pets { get; set; }
}

...

using (var db = new PostGresDbContext())
{
  var person = db.People.FirstOrDefault();

  person.Pets == "[{}]"; // true

  person.Pets = JsonConvert.SerializeObject(new {Name = "Fluffy", Type = "Dog" });

  db.Update(person);  // {"42804: column \"pets\" is of type json but expression is of type text"}
}
```

Also tried using attributes combinations below, but none worked.

``` c#
[Column(DbType = "json")]
[Column(DataType = DataType.Text)]
[Column(DbType = "json", DataType = DataType.Text)]
```

**Comment by ronnyek** [comment] 2017-03-08 23:54
I'm pretty certain this is because internally providers switch on the DataType and return the native types for the database. Currently there are no Json/Jsonb types, so it defaults to text/string. 

I'm in the process of creating unit tests for a pull request I've got that would handle this functionality... and hope to have it checked in this evening (as to whether or not I'll get linq2db maintainer support, that will remain to be seen)

**Comment by ronnyek** [comment] 2017-03-09 05:20
#586 Pending approval

**Comment by ili** [comment] 2017-03-09 09:01
#586 merged

**Comment by ronnyek** [comment] 2017-03-12 03:10
@ili, after running through some trials I noticed even with the new data types, conversions (and the sql builder additions you added after) I am still having problems... I built a test in my repository that maybe you can take a look at and tell me why it still wont insert. Looks like I can use column attributes to set DataType, as well as use it in the parameter converter. But at the time its executing sql, for whatever reason its using undefined type.

https://github.com/ronnyek/linq2db/commit/8e7c34dadedf745f88047b90649f73cba1716d7e

**Comment by jogibear9988** [comment] 2017-03-12 06:03
see also https://github.com/linq2db/linq2db/issues/533

I've already looked at this! Problem is, at the Place where we build the Parameter for the insert, we don't have the information any more (we convert the Converter to a lambda wich returns the value). We need to change that Code.

For look, my problem could be solved using DbNull instead of null, so I stopped looking!

**Comment by ronnyek** [comment] 2017-03-12 06:21
Hrmm... with that test, I've got it returning DbNull.Value, and the json types arent null when inserting. I just dont understand enough where that actual conversion is happening (or in this case apparently not). I've been tracing through this code for quite some time.

**Comment by ronnyek** [comment] 2017-03-12 06:57
Could we wrap up converters in a ConverterDescriptor or something, so that where we access the converter itself we wrap the converter with the compiled lambda and information about it?

**Comment by ili** [comment] 2017-04-06 12:41
@ronnyek 
Does the problem is still actual? If yes please make PR with test reproducing the case

**Comment by ili** [comment] 2017-05-18 14:10
Closing for now, if still an issue, please make PR reproducing the problem (better with fix :)))

**Closed by ili** 2017-05-18 14:10 UTC
Labels: discussion, expecting answer
