### ISSUE TITLE
No Primary Key Defined

### ISSUE THREAD

**Issue by merthsoft** [linq2db/linq2db#405] opened 2016-07-23 22:34 UTC
Let's say I've got the following tabe:

```sql
CREATE TABLE `TriviaScores` (
  `UserId` bigint(20) unsigned NOT NULL,
  `UserName` text CHARACTER SET latin1 NOT NULL,
  `TotalScore` bigint(20) unsigned NOT NULL.
  `RoundScore` bigint(20) unsigned NOT NULL,
  PRIMARY KEY (`UserId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```

When I do a db.Update with a TrivisScore object that I created, I get the following error:

> An exception of type 'LinqToDB.Linq.LinqException' occurred in linq2db.dll but was not handled in user code
> 
> Additional information: There are no fields to update in the type 'TriviaScores'. No PK is defined or all fields are keys.

And this is the generated class:

```cs
[Table("TriviaScores")]
public partial class TriviaScore
{
    [Column, NotNull] public ulong  UserId     { get; set; } // bigint(20) unsigned
    [Column, NotNull] public string UserName   { get; set; } // text
    [Column, NotNull] public ulong  TotalScore { get; set; } // bigint(20) unsigned
    [Column, NotNull] public ulong  RoundScore { get; set; } // bigint(20) unsigned
}
```

Why is it not putting the `PrimaryKey` Attribute on UserId despite the `PRIMARY KEY (`UserId`)`?

**Comment by rechkalov** [comment] 2016-07-25 10:56
Looks like 
> No PK is defined or all fields are keys.

relates to lin2db schema, rather than to sql schema. Try to set PK in your TriviaScore type:

```c#
[Table("TriviaScores")]
public partial class TriviaScore
{
    [Column, NotNull, PrimaryKey] public ulong  UserId     { get; set; } // bigint(20) unsigned
    [Column, NotNull] public string UserName   { get; set; } // text
    [Column, NotNull] public ulong  TotalScore { get; set; } // bigint(20) unsigned
    [Column, NotNull] public ulong  RoundScore { get; set; } // bigint(20) unsigned
}
```

**Comment by merthsoft** [comment] 2016-07-25 16:47
Yes, but that's auto-generated from the template file. I don't want to have to specify that for every table each time I generate it.

**Comment by rechkalov** [comment] 2016-07-26 03:55
Sorry, I did not notice it.

**Comment by ili** [comment] 2017-04-02 08:39
@merthsoft i'v checked it with latest release and problem is not reproduced

* MySQL 5.5.28
* MySql.Data.6.9.9
* linq2db.1.7.6

What MySQL server and provider version you are using?

**Comment by ili** [comment] 2017-05-18 14:01
Closing, will reopen on additional info

**Comment by moosemanf** [comment] 2018-01-23 11:43
I have similiar topic regarding update, but I work with Firebird. 
My autogenerated template file looks like this:
`
[Table("DP")]

	public partial class DP
	{
		[PrimaryKey, NotNull    ] public int       SELF_ID    { get; set; } // integer
		[Column,        Nullable] public int?      MANDANT_ID { get; set; } // integer
		[Column,        Nullable] public int?      ORGDATA_ID { get; set; } // integer
		[Column,        Nullable] public DateTime? VALIDFROM  { get; set; } // timestamp
		[Column,        Nullable] public byte[]    XML        { get; set; } // blob`

and still there is "No PK is defined or all fields are keys"

**Comment by sdanyliv** [comment] 2018-01-23 12:26
@moosemanf, please provide with execution code. Thanks.

**Comment by moosemanf** [comment] 2018-01-23 12:58
I tried different things within the update(), I hope I'm not on the wrong path here, thx for helping!

    binding1 = new BindingSource();
      using (var dba = new ZcDatenbank30DB())
            {
                var qa =
                from a in dba.DPs
                select a;

                binding1.DataSource = qa.ToList();
                dataGridView1.DataSource = binding1;
            ....
       //...then in Save-Button
    binding1.EndEdit();
                using (var dba = new ZcDatenbank30DB())
                {
                    dba.Update(binding1);
                }

**Comment by sdanyliv** [comment] 2018-01-23 16:27
It should not work. We do not support bindings. You have to update items by itself.
dba.Update requires Entity, not Binding class.

**Comment by sdanyliv** [comment] 2018-01-23 17:19
I suggest to store array somewhere and, when you need save data, you have to iterate through this array and update items individually.
Of course you have to know somehow which items are changed.

**Comment by moosemanf** [comment] 2018-01-24 06:49
sounds like a plan, thx appreciate it!

**Comment by MaceWindu** [comment] 2018-04-07 12:58
Closing answered/non-actionable issues. Feel free to reopen/continue discussion if it wasn't anwsered.

**Closed by MaceWindu** 2018-04-07 12:58 UTC
Labels: T4, bug, expecting answer

**Comment by naf2000** [comment] 2021-02-17 18:56
I'm generate classes from DB with LinqToDB.Firebird. 
But primary key field  generated to property with [PrimaryKey, NotNull] attributes, but without Identity attribute. Why?
Table:
`CREATE TABLE "Items" (
    "ItemID"  BIGINT NOT NULL,
    "Name"    VARCHAR(100) NOT NULL
);ALTER TABLE "Items" ADD CONSTRAINT "PK_Items" PRIMARY KEY ("ItemID");`

**Comment by sdanyliv** [comment] 2021-02-17 21:28
@naf2000, I do not see Identity column definition here. How we have to understand that this is identity column?
