### ISSUE TITLE
Enable TOP in subqueries for MS-SQL

### ISSUE THREAD

**Issue by Shane32** [linq2db/linq2db#2282] opened 2020-06-18 15:13 UTC
When using the MS SQL Server 2017 data provider, `FirstOrDefault()` in a subquery does not translate to `SELECT TOP 1` in the produced SQL, generating a slightly more complex execution plan.

### Steps to reproduce

I am executing code as follows:
```csharp
var provider = new SqlServerDataProvider(ProviderName.SqlServer, SqlServerVersion.v2017);
var db = new DataContext(provider, Configuration.GetConnectionString("testdb"));
var categories = db.GetTable<Category>();
var productCategories = db.GetTable<Product_Category_Mapping>();
var products = db.GetTable<Product>();
var test4 =
    from product in products
    select new {
        Product = product,
        Category = (
            from cat in categories
            join pcat in productCategories on cat.Id equals pcat.CategoryId
            where pcat.ProductId == product.Id
            select new { cat.Id, cat.Name }).FirstOrDefault()
    };
var test4ret = await test4.Take(10).ToListAsync();
```

With these classes:
```csharp
class Product
{
    public int Id { get; set; }
    public string Name { get; set; }

}
class Product_Category_Mapping
{
    public int Id { get; set; }
    public int ProductId { get; set; }
    public int CategoryId { get; set; }
    public bool IsFeaturedProduct { get; set; }
    public bool DisplayOrder { get; set; }
}
class Category
{
    public int Id { get; set; }
    public string Name { get; set; }
    public int ParentCategoryId { get; set; }
}
```

Produced SQL:
```sql
DECLARE @take Int -- Int32
SET     @take = 10
DECLARE @take_1 Int -- Int32
SET     @take_1 = 1

SELECT TOP (@take)
        [product_1].[Id],
        [product_1].[Name],
        [t2].[Id],
        [t2].[Name],
        [t2].[is_empty]
FROM
        [Product] [product_1]
                OUTER APPLY (
                        SELECT
                                [t1].[Id],
                                [t1].[Name],
                                [t1].[is_empty]
                        FROM
                                (
                                        SELECT
                                                [cat].[Id],
                                                [cat].[Name],
                                                1 as [is_empty],
                                                ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) as [RN]
                                        FROM
                                                [Category] [cat]
                                                        INNER JOIN [Product_Category_Mapping] [pcat] ON [cat].[Id] = [pcat].[CategoryId]
                                        WHERE
                                                [pcat].[ProductId] = [product_1].[Id]
                                ) [t1]
                        WHERE
                                [t1].[RN] <= @take_1
                ) [t2]
```

Expected SQL:
```sql
DECLARE @take Int -- Int32
SET     @take = 10
DECLARE @take_1 Int -- Int32
SET     @take_1 = 1

SELECT TOP (@take)
        [product_1].[Id],
        [product_1].[Name],
        [t2].[Id],
        [t2].[Name],
        [t2].[is_empty]
FROM
        [Product] [product_1]
                OUTER APPLY (
                        SELECT TOP (@take_1)
                                [t1].[Id],
                                [t1].[Name],
                                [t1].[is_empty]
                        FROM
                                (
                                        SELECT
                                                [cat].[Id],
                                                [cat].[Name],
                                                1 as [is_empty]
                                        FROM
                                                [Category] [cat]
                                                        INNER JOIN [Product_Category_Mapping] [pcat] ON [cat].[Id] = [pcat].[CategoryId]
                                        WHERE
                                                [pcat].[ProductId] = [product_1].[Id]
                                ) [t1]
                ) [t2]
```
Or possibly this: (which produces an identical execution plan)
```sql
DECLARE @take Int -- Int32
SET     @take = 10
DECLARE @take_1 Int -- Int32
SET     @take_1 = 1

SELECT TOP (@take)
        [product_1].[Id],
        [product_1].[Name],
        [t1].[Id],
        [t1].[Name],
        [t1].[is_empty]
FROM
        [Product] [product_1]
                OUTER APPLY (
                        SELECT TOP (@take_1)
                                [cat].[Id],
                                [cat].[Name],
                                1 as [is_empty]
                        FROM
                                [Category] [cat]
                                        INNER JOIN [Product_Category_Mapping] [pcat] ON [cat].[Id] = [pcat].[CategoryId]
                        WHERE
                                [pcat].[ProductId] = [product_1].[Id]
                ) [t1]
```

Here is the differences in the actual execution plan with the produced SQL vs the expected SQL: (acutal on top, expected on bottom)
![image](https://user-images.githubusercontent.com/6377684/85036049-de674a80-b151-11ea-9926-07775568f1f3.png)

### Environment details
linq2db version: 3.0.0-rc.1
Database Server: Microsoft Azure SQL Database
Database Provider: SqlServer v2017
Operating system: Windows 10 Pro 1909
.NET Framework: .Net Core 3.1

**Comment by sdanyliv** [comment] 2020-06-18 15:23
Confirmed bug. Will be fixed in next release.
Looks like we have used logic from SQL Server 2012 dialect, which do not support such query, so we replaced TOP 1 with Window function.

**Comment by sdanyliv** [comment] 2020-06-18 15:29
@Shane32, maybe you want to help project and fix it yourself? :)
This part introduces problem in derived SqlServer2017SqlOptimizer:
https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/DataProvider/SqlServer/SqlServer2012SqlOptimizer.cs#L23-L24

**Comment by Shane32** [comment] 2020-06-18 15:34
Yes, I would be glad to if I can.  Knowing nothing of the codebase, (and only starting to use linq2db for a total of 3 days now!), your pointing me to the right direction definitely helps.  I will take a look as I have time, and if I can figure it out, issue a PR.

**Comment by Shane32** [comment] 2020-06-19 10:23
@sdanyliv Is there a particular test/query that is the reason this code was added in the first place?  My oldest server is running SQL Server 2012, and I created a test database within it set to compatibility mode 90 (SQL Server 2005), and it still executes queries like this one just fine:

```sql
DECLARE @take Int -- Int32
SET     @take = 10
DECLARE @take_1 Int -- Int32
SET     @take_1 = 1

SELECT TOP (@take)
  Products.Name,
  Color2 = (SELECT TOP (@take_1) Colors.ColorName FROM Colors),
  [t2].ColorName
FROM
  Products
  OUTER APPLY (
    SELECT TOP (@take_1)
      Colors.ColorName
    FROM
      Colors
    WHERE
      Colors.ProductId = Products.Id
  ) [t2]
```

It also executes queries with OFFSET and FETCH like this just fine, as long as there is an ORDER BY (even if the order by value is a constant):
```sql
DECLARE @take Int -- Int32
SET     @take = 10
DECLARE @take_1 Int -- Int32
SET     @take_1 = 1

SELECT
  Products.Name,
  Color2 = (SELECT Colors.ColorName FROM Colors ORDER BY 1 OFFSET 1 ROWS FETCH NEXT 1 ROWS ONLY),
  [t2].ColorName
FROM
  Products
  OUTER APPLY (
    SELECT
      Colors.ColorName
    FROM
      Colors
    WHERE
      Colors.ProductId = Products.Id
	ORDER BY 1
	OFFSET 1 ROWS FETCH NEXT 1 ROWS ONLY
  ) [t2]
ORDER BY Products.Id
OFFSET 1 ROWS
FETCH NEXT 1 ROWS ONLY
```

Note that OFFSET and FETCH were not available in 2008, but only available in 2012 and later. See: https://docs.microsoft.com/en-us/sql/t-sql/queries/select-order-by-clause-transact-sql?view=sql-server-ver15

Also, TOP is supported in 2000 - see documentation here:
https://www.microsoft.com/en-us/download/details.aspx?id=51958

And ROW_NUMBER is supported in 2005 - see documentation here:
https://docs.microsoft.com/en-us/previous-versions/sql/sql-server-2005/ms186734(v=sql.90)

Looking briefly at `SqlServer2008SqlOptimizer.CorrectRootSkip`, it would seem that someone already wrote code to patch the fact that a skip operation needs an orderby clause.  The code never executes with the `SqlServer2008SqlOptimizer` because `ReplaceTakeSkipWithRowNumber` takes precedence and removes the take/skip operations altogether.  It's only useful in the `SqlServer2012SqlOptimizer` which only converts subqueries to use `ROW_NUMBER()`.

It would seem the proper fix would be:
* Prevent queries and subqueries with Skip in 2000 (as OFFSET and ROW_NUMBER are both unsupported)
* Only apply ReplaceTakeSkipWithRowNumber for 2005 and 2008 versions, and only when skip != null, for both root and subqueries (since TOP works fine in SQL Server 2000 and later)
* Add an ORDER BY parameter for all versions when skip != null and order is unspecified.  This should not perform any worse than using ROW_NUMBER, since ROW_NUMBER also needs an ORDER BY clause
* Remove `SqlServer2008SqlOptimizer.CorrectRootSkip`

**Comment by sdanyliv** [comment] 2020-06-19 10:35
> @sdanyliv Is there a particular test/query that is the reason this code was added in the first place? My oldest server is running SQL Server 2012, and I created a test database within it set to compatibility mode 90 (SQL Server 2005)

I really don't remember, if you remove correction code, several tests should fail.
Copy `DataProviders.json` to `UserDataProviders.json`
Then add `"SqlServer.2017"` here
https://github.com/linq2db/linq2db/blob/master/Tests/DataProviders.json#L27
And configure this provider, just copy paste, rename to `"SqlServer.2017"` and setup your connection string.
https://github.com/linq2db/linq2db/blob/master/Tests/DataProviders.json#L117-L120

That's it, you can run tests on your workstation.

**Closed** 2020-06-24 13:19 UTC
Labels: status: has-pr
