### ISSUE TITLE
Include-tables param example in documentation is possibly wrong

### ISSUE THREAD

**Issue by cdjambovyourbteam** [linq2db/linq2db#4388] opened 2024-01-25 14:18 UTC
### Describe your issue
According to the documentation here (https://linq2db.github.io/articles/cli-help.txt v5.2.1) the _include-tables param regex part looks like 

 { "schema": { "include-tables": [ { "regex": "^audit_.$+", "schema": "dbo" } ] } } // all tables starting from audit_ prefix

And the result was that no generation occurred in the target directory. I have tables with prefix.

What worked for me was (note the regex value):
 { "schema": { "include-tables": [ { "regex": "^(audit_.+)$", "schema": "dbo" } ] } } // all tables starting from audit_ prefix

Perhaps it is a typo ?

### Steps to reproduce

Above text explains enough

### Environment details

`Linq To DB` version: v5.2.1

Database (with version): SQL Server 2019

Operating system: W11

.NET Version: 8

**Comment by MaceWindu** [comment] 2024-01-26 11:17
duplicate of #4373

**Closed by MaceWindu** 2024-01-26 11:17 UTC
