### ISSUE TITLE
MySQL: Data is Null. This method or property cannot be called on Null values.

### ISSUE THREAD

**Issue by pebezo** [linq2db/linq2db#800] opened 2017-08-13 19:27 UTC
This may not be caused by LINQ2DB, but hopefully someone already came across this issue. I'm using LINQ2DB to access a MySQL instance (5.6.35 / Percona 80). 

There's one particular query that accesses a view from one db that does a cross-db select (may not be relevant), something like:

```sql
SELECT id, name FROM other_database.some_table st WHERE st.id = 1234;
```

On the LINQ2DB site the query is super simple as well:

```cs
var record = (from sv in db.SomeView where sv.Id == 1234 select sv).FirstOrDefault();
```

99% of the time, this query works without issues. Sometimes though, I'm getting:

Exception message: `Data is Null. This method or property cannot be called on Null values.`
Stack trace:
```
at MySql.Data.MySqlClient.MySqlDataReader.GetFieldValue(Int32 index, Boolean checkNull)\r\n   at MySql.Data.MySqlClient.MySqlDataReader.GetString(Int32 i
at lambda_method(Closure , QueryContext , IDataContext , IDataReader , Expression , Object[] )\r\n   at LinqToDB.Linq.Query`1.<Map>d__69.MoveNext()
at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
at LinqToDB.Linq.Builder.FirstSingleBuilder.FirstSingleContext.<>c__DisplayClass12`1.<BuildQuery>b__b(QueryContext ctx, IDataContext db, Expression expr, Object[] ps)
at LinqToDB.Linq.ExpressionQuery`1.System.Linq.IQueryProvider.Execute[TResult](Expression expression)
at MyNamespace.MyFunction(Int32 campaignId, Int32 dealerId) in [my source code]
```
Once I get this error, subsequent requests fail with the same message (and always the same spot). Most of the time, restarting the application pool fixes the problem, but I've seen it where it wasn't fixing it.

If I put a breakpoint right before the error and extract the SQL query and then run that query in MySQL Workbench the query runs fine and none of the returned rows are null. However, LINQ2DB complains that the results set came back with nulls for ints. It's almost as if MySQL returns a blank row to my app, but a proper result set for MySQL Workbench (same exact query). Is there a way I could catch the raw data coming back from MySQL before LINQ2DB tries to deserialize?

It's very strange and very hard to reproduce... I was not able to find a pattern (yet).

Any ideas? Thanks.

### Steps to reproduce
None, unfortunately...

### Environment details
linq2db version: *1.8.3*  
Database Server: *MySQL 5.6*  
Database Provider: *MySqlDataProvider*  
Operating system: *Windows Server 2012 R2*  
Framework version: *.NET Framework 4.6.1*

**Comment by MaceWindu** [comment] 2017-08-13 20:26
Potentially, there are several reasons to get this error, so you need to narrow it down to one of them.

First of all lets describe what linq2db does here. Linq2db maps record from data reader to target class, using generated method. This method reads value from data reader for each target property. If linq2db knows that data reader's column could contain null values, generated operation will have two operations: check for DBNull and read of non-null value. Otherwise it will read value directly.
As you get this error it means that there is no check for DBNull for some column, but for some reason it contains DBNull value.

There are several reasons:
- mysql returns null where it shouldn't. This could be MySQL issue, which could be workarounded by forcing linq2db to expect null for this column(s)
- linq2db incorrectly decided that server cannot return null for some column - for that you need to review generated mapping function and see if it miss DBNull checks for column that definitly could contain nulls and then we could try to fix it
- linq2db uses wrong mapping function from cache - definitely linq2db bug

Your next steps:
- enable logging of generated mapping functions : 
```
Configuration.Linq.TraceMapperExpression = true;
DataConnection.TurnTraceSwitchOn();
DataConnection.WriteTraceLine = (message, category) => YourLogger.Write($"[{category}] {message}");
```
this already could give you required information. If no, see next steps
- build debug version of linq2db from 1.8.3 branch
- when you start getting those errors - attach with debugger and check what mapping function is used and which column unexpectedly returned nulls. After that it should be clear what is going on. You will need to put breakpint in Query.Map function and check `mapInfo.MapperExpression` and `dr` datareader's content for failing column

**Comment by pebezo** [comment] 2017-08-14 03:11
Thank you for your thorough response! I've made the changes you recommended and now waiting for the bug to show up...

**Comment by pebezo** [comment] 2017-08-15 14:46
TurnTraceSwitchOn() and TraceMapperExpression didn't help much. I can basically see the query that it's about to run and then it fails. Next step is to clone linq2db and build against it (instead of NuGet) so that I could debug into linq2db. Thanks.

**Comment by pebezo** [comment] 2017-08-15 15:37
I can compile the linq2db project by itself without errors, but when I try add a reference to it I'm getting "NU1001 The dependency linq2db >= 1.8.4-* could not be resolved". When I add a reference to the local linq2db project it puts this ```"linq2db": "1.8.4-*",``` in my project.json file. 

Have you seen this issue? (VS2015 update 3, the project is using Core 1.1 and running on 461). I've removed project.lock.json to force a rebuild, and remove the cached linq2db packages (locally and globally)... it's still saying it cannot resolve.

Thanks.

**Comment by MaceWindu** [comment] 2017-08-15 15:49
I don't know your environment, but why just don't replace linq2db.dll with built debug version + .pdb file after your application build? It should be easier than changing project.

**Comment by pebezo** [comment] 2017-08-27 04:51
I was trying to bring it into my solution so that I could step into the source code. I wasn't able to do this with VS2015 and project.json, so I decided to upgrade to VS2017 and csproj (2.0 tools). This took a while to convert, hence the delay in responding.

I pulled linq2db and added it to my solution. I had to remove the global.json and *.project.json files to make it work. I did a ```git checkout tags/Release.1.8.3``` so that I could use the latest released version. BTW: something seems to be broken in the master branch because table schemas are ignored (works fine in 1.8.3). I'm using ```GetTable<MyTable>().SchemaName("my_schema")```.

The good news is that I'm able to replicate the problem. The bad news is that I can only trigger it when running the entire suite of tests. I have 5 tests that consistently fail when I run the entire suite, but if I run each failing test separately they pass. I'm using xunit with collections to prevent tests from running in parallel.

The second good news is that I was able to isolate the problem to one of my queries. It's above average in complexity, about 10 joins, but nothing special imo. If I replace that query with raw ado.net code, bypassing linq2db, then all the tests pass; so it seems like there's a bug in linq2db somewhere...

It's like there's some kind of state corruption in linq2db and I'm seeing the echoes of the original problem. I was able to put a global break on SqlNullValueException and it took me to Query.cs line 1234 in the Map() function just like you said. 

From there I was able to look at "dr" and all the values seem to be there... What's interesting is that it doesn't like the "email" column. My query returns 18 columns, but if I comment out the email column (so it's not returned in the result set) everything looks like it's working. All the tests pass. I don't see anything unusual or special about this column (varchar(128) in MySQL and string in C#).

Any suggestions on how to proceed? Thanks.

**Comment by ili** [comment] 2017-08-27 07:47
I think you would need to migrate to VS2017 to reference debug dll in .Net Core project :(

Speaking about an issue, are there any rows with `NULL`  in `email` column in result dataset?

**Comment by MaceWindu** [comment] 2017-08-27 09:27
schema name doesn't work for you in master/1.9.0 due to #681. Looks like we will need to emphasise it in release notes.

**Comment by MaceWindu** [comment] 2017-08-27 09:38
Could you inspect content of data reader and mapping expression more carefully when error occur like:
- there is no null values in any column of dr
- mapping expression doesn't try to access column with out-of-range index
- mapping expression doesn't what it needs for current query

Also could it be possible that you have other queries that are similar to this one or return same set of columns? Or even better, could you narrow down you test set to two (I hope) tests that trigger this failure?

**Comment by pebezo** [comment] 2017-08-27 13:29
@ili yes, I did migrate to VS2017

@MaceWindu I've hit that exact same issue (double dots "..") with master... after rolling back to 1.8.3 this issue goes away

"there is no null values in any column of dr" -- the email column is null, but it's a string, so it shouldn't be an issue. Here's what "dr" looks like:

![image](https://user-images.githubusercontent.com/1287097/29750028-4a736c10-8b06-11e7-9bb5-ade3eb32d27a.png)

"mapping expression doesn't try to access column with out-of-range index" -- how do I check for this?

"mapping expression does what it needs for current query" -- well... here's what I was able to fish out from the debug view:

```
.Lambda #Lambda1<System.Func`6[LinqToDB.Linq.QueryContext,LinqToDB.IDataContext,System.Data.IDataReader,System.Linq.Expressions.Expression,System.Object[],Denali.Core.Entities.Organization.Dto.ProspectDetail]>(
    LinqToDB.Linq.QueryContext $context,
    LinqToDB.IDataContext $dctx,
    System.Data.IDataReader $rd,
    System.Linq.Expressions.Expression $expr,
    System.Object[] $ps) {
    .Block(
        MySql.Data.MySqlClient.MySqlDataReader $ldr,
        Denali.Core.Entities.Organization.Dto.ProspectDetail $ProspectDetail1) {
        $ldr = (MySql.Data.MySqlClient.MySqlDataReader)$rd;
        $ProspectDetail1 = .New Denali.Core.Entities.Organization.Dto.ProspectDetail(){
            ProspectDetailId = #(System.Int32)((System.UInt32).Call $ldr.GetValue(0)),
            ProspectId = #(System.Int32)((System.UInt32).Call $ldr.GetValue(1)),
            CustomerId = #(System.Int32)((System.UInt32).Call $ldr.GetValue(2)),
            CustomerKey = .If (
                .Call $ldr.IsDBNull(3)
            ) {
                null
            } .Else {
                .Call $ldr.GetString(3)
            },
            Proof = .If (
                .Call $ldr.IsDBNull(4)
            ) {
                null
            } .Else {
                .New System.Nullable`1[System.Int32](.Call $ldr.GetInt32(4))
            },
            FirstName = .Call $ldr.GetString(5),
            LastName = .Call $ldr.GetString(6),
            Street1 = .If (
                .Call $ldr.IsDBNull(7)
            ) {
                null
            } .Else {
                .Call $ldr.GetString(7)
            },
            Street2 = .If (
                .Call $ldr.IsDBNull(8)
            ) {
                null
            } .Else {
                .Call $ldr.GetString(8)
            },
            City = .If (
                .Call $ldr.IsDBNull(9)
            ) {
                null
            } .Else {
                .Call $ldr.GetString(9)
            },
            State = .If (
                .Call $ldr.IsDBNull(10)
            ) {
                null
            } .Else {
                .Call $ldr.GetString(10)
            },
            Zip = .If (
                .Call $ldr.IsDBNull(11)
            ) {
                null
            } .Else {
                .Call ((System.UInt32).Call $ldr.GetValue(11)).ToString()
            },
            Phone = .If (
                .Call $ldr.IsDBNull(12)
            ) {
                null
            } .Else {
                .Call $ldr.GetString(12)
            },
            Email = .Call $ldr.GetString(13),
            VIN = .If (
                .Call $ldr.IsDBNull(14)
            ) {
                null
            } .Else {
                .Call $ldr.GetString(14)
            },
            Year = .Call (.If (
                .Call $ldr.IsDBNull(15)
            ) {
                0
            } .Else {
                .Call $ldr.GetInt32(15)
            }).ToString(),
            Make = .If (
                .Call $ldr.IsDBNull(16)
            ) {
                null
            } .Else {
                .Call $ldr.GetString(16)
            },
            Model = .If (
                .Call $ldr.IsDBNull(17)
            ) {
                null
            } .Else {
                .Call $ldr.GetString(17)
            }
        };
        $ProspectDetail1
    }
}
```

Here's what my query looks like:

![image](https://user-images.githubusercontent.com/1287097/29750202-9612c50a-8b09-11e7-90ee-d2a04646f7d0.png)

What I find interesting is that both Phone and VIN are strings, just like Email, but those two are wrapped with a IsDBNull check while Email is not...

Also, what's interesting is that if I force the null check by doing ```Email = ea.Email == null ? null : ea.Email``` instead of just ```Email = ea.Email``` the it works... 

Thoughts?

**Comment by MaceWindu** [comment] 2017-08-27 14:40
`the email column is null, but it's a string, so it shouldn't be an issue`
this is not true when we work with .net data reader.

Now it is clear, that for email column linq2db thinks that it cannot contain NULL values and doesn't generate check for it in row mapper.
We get information about nullability from data reader schema, so could you check what data reader returns for email column:
```cs
dr.GetSchemaTable().Rows[13]["AllowDBNull"]
```

**Comment by pebezo** [comment] 2017-08-27 14:46
That returns "true":

![image](https://user-images.githubusercontent.com/1287097/29750837-eddf8e34-8b14-11e7-9ef5-1c5420094cbd.png)

**Comment by MaceWindu** [comment] 2017-08-27 14:55
Ok, I think MySQL provider cannot return stable schema information regarding AllowDBNull property (maybe related to your setup with cross-db view). So if first query execution returned false for AllowDBNull, next queries will use generated mapper that could fail when null value returned.

For now I recommend to use your workaround as there is not time left to fix it in 1.9.0.

**Comment by MaceWindu** [comment] 2017-08-27 14:57
` I've hit that exact same issue (double dots "..") with master`

not sure what you mean as there is no way for MySQL provider to generate double dots in FQ table name anymore in current master.

**Comment by pebezo** [comment] 2017-08-27 15:00
"not sure what you mean as there is no way for MySQL provider to generate double dots in FQ table name anymore in current master." -- Ignore that comment... I was getting those errors when I was setting the database name, but not the schema. With 1.9 the schema is ignore though. Sorry about the confusion.

**Comment by pebezo** [comment] 2017-08-27 15:06
Do you feel like you understand the issue? Anything else you'd like me to try? If I implement my workaround I may not able to trigger the problem later...

Also, I refactored the code to not use views. I thought it may have something to do with MySQL views. The current code looks only at tables and it's only looking at single database/schema (not the main one, but the one pointed by SchemaName(). So no cross-db/schema joins...

Is there anything in particular that I should be on the lookout?

**Comment by MaceWindu** [comment] 2017-08-27 15:08
Just to confirm that I guessed it correctly, you can try to add call to
`DataConnection.ClearObjectReaderCache()` before this query execution as another woraround.
Don't forget to remove it later as it will affect performance.

**Comment by pebezo** [comment] 2017-08-27 15:14
Negative. I tried calling that before building the query and right before the call to FirstOrDefault(). It didn't make a difference.

**Comment by MaceWindu** [comment] 2017-08-27 15:18
Okaaayy... Anyway, thanks for your patience :)

**Comment by pebezo** [comment] 2017-08-27 15:19
Just as a sanity check, I called `DataConnection.ClearObjectReaderCache()` before and after the query with and without returning the email field. Only commenting out the email field made a difference.

**Comment by pebezo** [comment] 2017-08-27 15:19
Thank YOU for your patience 👍

**Comment by MaceWindu** [comment] 2017-08-27 15:23
BTW, could you post view creation statement? It will help us to reproduce this issue later.

**Comment by pebezo** [comment] 2017-08-27 15:24
What do you mean with view creation statement?

**Comment by pebezo** [comment] 2017-08-27 15:25
The MySQL view creation statement?

**Comment by MaceWindu** [comment] 2017-08-27 15:25
yep

**Comment by pebezo** [comment] 2017-08-27 15:33
Originally, I was seeing these issues in one spot that was using a database view. It was happening somewhat randomly (once or twice a day). I was not able to reproduce that issue and it was not happening when running the test suite, only in production.

Since I thought the issue was with the MySQL view I went ahead and got rid of the view. It's now running against tables; doesn't use views anymore. After I removed the views I was able to trigger the issue within the test suite.

The create statement for the emails table is:

```
CREATE TABLE `email_addresses` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `email` varchar(128) NOT NULL,
  `unsubscribed` tinyint(1) NOT NULL DEFAULT '0',
  `is_valid_for_analysis` tinyint(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  UNIQUE KEY `email` (`email`) USING BTREE,
  UNIQUE KEY `id` (`id`,`unsubscribed`) USING BTREE,
  KEY `idx_analysis` (`id`,`is_valid_for_analysis`)
) ENGINE=InnoDB AUTO_INCREMENT=5230558 DEFAULT CHARSET=latin1 ROW_FORMAT=DYNAMIC;
```
and the one for the vehicles table (the one that works even though it's very similar to the emails table)

```
CREATE TABLE `vehicles` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `vin` varchar(17) NOT NULL,
  `year` int(4) NOT NULL,
  `make` varchar(50) NOT NULL,
  `model` varchar(50) NOT NULL DEFAULT '',
  `is_cleaned` tinyint(1) DEFAULT '0',
  `blackbook_value` decimal(10,4) DEFAULT NULL,
  `blackbook_last_updated` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `year` (`year`) USING BTREE,
  KEY `vehicle` (`vin`,`year`,`make`,`model`)
) ENGINE=InnoDB AUTO_INCREMENT=24913935 DEFAULT CHARSET=latin1 ROW_FORMAT=DYNAMIC;
```

**Comment by sdanyliv** [comment] 2017-08-27 15:35
@pebezo, looks like it is DataProvider issue. Looking for ways how to fix that.

**Comment by pebezo** [comment] 2017-08-27 15:36
@sdanyliv what do you mean? How could I solve that?

**Comment by sdanyliv** [comment] 2017-08-27 15:38
We can take in account that field is nullable using mapping attributes and do not ask DataProvider in that case.

**Comment by pebezo** [comment] 2017-08-27 15:47
Is there any other way to force linq2db to get rid of all the internal caching besides `DataConnection.ClearObjectReaderCache();`?

**Comment by pebezo** [comment] 2017-08-28 13:15
Potentially interesting finding: I converted the query to a stored procedure, ran it via QueryProc<T>, and I saw the same exact issue. So it doesn't seem like it matters if the query is generated by linq2db or hardcoded (in a stored proc)

**Comment by pebezo** [comment] 2017-08-29 02:12
I was able to narrow it down to two tests that are causing the issue. This made it a lot easier to reproduce.

In the GetObjectReader function there's a commented line:

https://github.com/linq2db/linq2db/blob/master/Source/Data/CommandInfo.cs#L1043

If I uncomment that line (and add sql as the third parameter) then all the tests pass! 

If leave it as is and debug, in CreateObjectReader I notice that the email column has CanBeNull = true

![image](https://user-images.githubusercontent.com/1287097/29801143-13a4ad52-8c3c-11e7-9ac3-3875f8f82041.png)

However, a few lines down when the members list is built, the expression seems to not account for null:

![image](https://user-images.githubusercontent.com/1287097/29801201-8c676b9e-8c3c-11e7-9580-7ce83f103425.png)

Something else that may be helpful is that on the first run of that query, the email is not null (it has a valid email address). On the second call, the one that breaks, the email is null. So could it be that the expression builder is looking at (or considering) the value of the column rather than the CanBeNull property?

Here's the final debug view

```
.New Denali.Core.Entities.Organization.Dto.ProspectDetail(){
    ProspectDetailId = #(System.Int32)((System.UInt32).Call ((MySql.Data.MySqlClient.MySqlDataReader)$var1).GetValue(0)),
    ProspectId = #(System.Int32)((System.UInt32).Call ((MySql.Data.MySqlClient.MySqlDataReader)$var1).GetValue(1)),
    CustomerId = #(System.Int32)((System.UInt32).Call ((MySql.Data.MySqlClient.MySqlDataReader)$var1).GetValue(2)),
    Proof = .If (
        .Call ((MySql.Data.MySqlClient.MySqlDataReader)$var1).IsDBNull(4)
    ) {
        null
    } .Else {
        .New System.Nullable`1[System.Int32](.Call ((MySql.Data.MySqlClient.MySqlDataReader)$var1).GetInt32(4))
    },
    FirstName = .Call ((MySql.Data.MySqlClient.MySqlDataReader)$var1).GetString(5),
    LastName = .Call ((MySql.Data.MySqlClient.MySqlDataReader)$var1).GetString(6),
    Street1 = .If (
        .Call ((MySql.Data.MySqlClient.MySqlDataReader)$var1).IsDBNull(7)
    ) {
        null
    } .Else {
        .Call ((MySql.Data.MySqlClient.MySqlDataReader)$var1).GetString(7)
    },
    Street2 = .If (
        .Call ((MySql.Data.MySqlClient.MySqlDataReader)$var1).IsDBNull(8)
    ) {
        null
    } .Else {
        .Call ((MySql.Data.MySqlClient.MySqlDataReader)$var1).GetString(8)
    },
    City = .If (
        .Call ((MySql.Data.MySqlClient.MySqlDataReader)$var1).IsDBNull(9)
    ) {
        null
    } .Else {
        .Call ((MySql.Data.MySqlClient.MySqlDataReader)$var1).GetString(9)
    },
    State = .If (
        .Call ((MySql.Data.MySqlClient.MySqlDataReader)$var1).IsDBNull(10)
    ) {
        null
    } .Else {
        .Call ((MySql.Data.MySqlClient.MySqlDataReader)$var1).GetString(10)
    },
    Zip = .If (
        .Call ((MySql.Data.MySqlClient.MySqlDataReader)$var1).IsDBNull(11)
    ) {
        null
    } .Else {
        .Call ((System.UInt32).Call ((MySql.Data.MySqlClient.MySqlDataReader)$var1).GetValue(11)).ToString()
    },
    Phone = .If (
        .Call ((MySql.Data.MySqlClient.MySqlDataReader)$var1).IsDBNull(12)
    ) {
        null
    } .Else {
        .Call ((MySql.Data.MySqlClient.MySqlDataReader)$var1).GetString(12)
    },
    Email = .Call ((MySql.Data.MySqlClient.MySqlDataReader)$var1).GetString(13),
    VIN = .If (
        .Call ((MySql.Data.MySqlClient.MySqlDataReader)$var1).IsDBNull(14)
    ) {
        null
    } .Else {
        .Call ((MySql.Data.MySqlClient.MySqlDataReader)$var1).GetString(14)
    },
    Year = .If (
        .Call ((MySql.Data.MySqlClient.MySqlDataReader)$var1).IsDBNull(15)
    ) {
        null
    } .Else {
        .Call (.Call ((MySql.Data.MySqlClient.MySqlDataReader)$var1).GetInt32(15)).ToString()
    },
    Make = .If (
        .Call ((MySql.Data.MySqlClient.MySqlDataReader)$var1).IsDBNull(16)
    ) {
        null
    } .Else {
        .Call ((MySql.Data.MySqlClient.MySqlDataReader)$var1).GetString(16)
    },
    Model = .If (
        .Call ((MySql.Data.MySqlClient.MySqlDataReader)$var1).IsDBNull(17)
    ) {
        null
    } .Else {
        .Call ((MySql.Data.MySqlClient.MySqlDataReader)$var1).GetString(17)
    }
}
```
This happend on the very first call to that function. I don't yet understand how the `getMemberExpression` works, but I'll keep digging. 

Thoughts?

**Comment by pebezo** [comment] 2017-08-29 03:39
https://msdn.microsoft.com/en-us/library/system.data.sqlclient.sqldatareader.getschematable(v=vs.110).aspx

> Set if the consumer can set the column to a null value or if the provider cannot determine whether the consumer can set the column to a null value. Otherwise, not set. **A column may contain null values, even if it cannot be set to a null value.**

Given that a column may contain null values (even if it cannot be set to a null value) why are we trying to use AllowDBNull when reading? Sounds to me like null values should always be expected...

https://github.com/linq2db/linq2db/blob/master/Source/DataProvider/DataProviderBase.cs#L278

In my test case `st.Rows[idx]["AllowDBNull"]` returns `false` for the email column. If replace that line with `return true;` then all the test pass. Is there a reason why that doesn't return `true` for all cases, not just net standard?

**Comment by MaceWindu** [comment] 2017-08-29 08:17
Yes, we are considering ignoring this flag for all or some providers as a fix...

**Comment by pebezo** [comment] 2017-08-29 23:07
OK. If others are hitting this issue, you can make your own data provider class and override IsDBNullAllowed, like this:

```
public class CustomMySqlDataProvider : MySqlDataProvider
{
    public override bool? IsDBNullAllowed(IDataReader reader, int idx) => true;
}
```

**Comment by json0007** [comment] 2022-07-22 14:33
@MaceWindu @ili @sdanyliv  Looks like this was a bug.  Do any of you know if this been fixed?  We were coping with the issue by overriding the MySqlDataProvider.IsDbNullAllowed() method to always return true.  However, we are looking to upgrade to version 4 and the IsDBNullAllowed() methd is no longer available. Please advise.  Thanks in advance.

**Comment by MaceWindu** [comment] 2022-07-22 14:38
1. it wasn't fixed as we didn't get query to reproduce it
2. `IsDBNullAllowed` is still here in v4 and you should be able to override it. Only change is that `MySqlDataProvider` is abstract class now and you need to inherit from it (like we do [here](https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/DataProvider/MySql/MySqlDataProvider.cs#L16-L17))

**Comment by json0007** [comment] 2022-07-22 14:49
@MaceWindu hmm.  I am getting the follwing error

 MySqlDataProviderDenali.cs(18, 31): [CS0115] 'MySqlDataProviderDenali.IsDBNullAllowed(IDataReader, int)': no suitable method found to override
 
 and I am not able to find the method here
 
 https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/DataProvider/MySql/MySqlDataProvider.cs

**Comment by MaceWindu** [comment] 2022-07-22 14:51
Ah, I see now - we changed signature to use `DbDataReader` from `IDataReader`

**Comment by json0007** [comment] 2022-07-22 14:53
@MaceWindu Yes, that works.  Thank you.  I don't know why I couldn't find it in the base class.

**Comment by MaceWindu** [comment] 2024-06-09 18:15
Closing for now as without repro nothing more could be done here

**Closed by MaceWindu** 2024-06-09 18:15 UTC
Labels: type: bug, provider: mysql, status: needs-tests
