### ISSUE TITLE
Bad translation of inline if in postgress

### ISSUE THREAD

**Issue by dagtveit** [linq2db/linq2db#3373] opened 2021-12-02 23:41 UTC
Hey the following code worked on mssql i dont have copy of the query but it translated it to working code. and produced good results. i just recently migrated to postgressql and have issues with this window query. its translating the code under to some weird case when null = true.

Also postgress supports filter function in window querys is there a plan to support this ?

The filters are just list of <int> with some int values
```c#
    var transactionsAggregateQuery =
                        from t in db.InstrumentTransactions
                        where t.Retracted == null &&
                              t.Instrument.Customer.IdentityId == companyIdentityId &&
                              t.TransactionDate <= dateModified
                        select new
                        {
                            t.TransactionDate,
                            t.Instrument.Id,
                            SumOfCostPriceOnOwnedSecurities = Sql.Ext.Sum(SecuritiesTransactionsFilters.StockCostPriceList.Contains(t.ActionType) ? t.Amount : 0)
                                
                                .Over()
                                .PartitionBy(t.Instrument.Id)
                                .OrderBy(t.TransactionDate)
                                .ToValue(),
                            SumOfCostPriceOnOwnedSecuritiesInCurrency = Sql.Ext.Sum(SecuritiesTransactionsFilters.StockCostPriceList.Contains(t.ActionType) ? t.CurrencyAmount : 0)
                                .Over()
                                .PartitionBy(t.Instrument.Id)
                                .OrderBy(t.TransactionDate)
                                .ToValue(),
                            Quantity = Sql.Ext.Sum(SecuritiesTransactionsFilters.InstrumentQuantityList.Contains(t.ActionType) ? t.Quantity : 0)
                                .Over()
                                .PartitionBy(t.Instrument.Id)
                                .OrderBy(t.TransactionDate)
                                .ToValue(),
                            LoanQty = Sql.Ext.Sum(SecuritiesTransactionsFilters.InstrumentLoanQuantityList.Contains(t.ActionType) && t.DueDate >= dateModified ? t.Quantity : 0)
                                .Over()
                                .PartitionBy(t.Instrument.Id)
                                .OrderBy(t.TransactionDate)
                                .ToValue(),
                            AmountSold = Sql.Ext.Sum(SecuritiesTransactionsFilters.SummableActionTypesSales.Contains(t.ActionType) ? t.Amount : 0)
                                .Over()
                                .PartitionBy(t.Instrument.Id)
                                .OrderBy(t.TransactionDate)
                                .ToValue(),
                            AmountCostReduction = Sql.Ext.Sum(SecuritiesTransactionsFilters.SummableActionTypesCostReduction.Contains(t.ActionType) ? t.Amount : 0)
                                .Over()
                                .PartitionBy(t.Instrument.Id)
                                .OrderBy(t.TransactionDate)
                                .ToValue(),
                            RowNumber = Sql.Ext.RowNumber().Over().PartitionBy(t.Instrument.Id).OrderByDesc(t.TransactionDate).ToValue()
                        };

```
```sql
WITH "transactionsAggregateCte"
         (
          "TransactionDate",
          "Id",
          "SumOfCostPriceOnOwnedSecurities",
          "SumOfCostPriceOnOwnedSecuritiesInCurrency",
          "Quantity",
          "LoanQty",
          "RowNumber",
          "LoanQty_1"
             )
         AS
         (
             SELECT
                 t."TransactionDate",
                 "a_Instrument"."Id",
                 SUM(CASE
                         WHEN NULL = True THEN t."Amount"
                         ELSE 0
                     END) OVER(PARTITION BY "a_Instrument"."Id" ORDER BY t."TransactionDate"),
                 SUM(CASE
                         WHEN NULL = True THEN t."CurrencyAmount"
                         ELSE 0
                     END) OVER(PARTITION BY "a_Instrument"."Id" ORDER BY t."TransactionDate"),
                 SUM(CASE
                         WHEN NULL = True THEN t."Quantity"
                         ELSE 0
                     END) OVER(PARTITION BY "a_Instrument"."Id" ORDER BY t."TransactionDate"),
                 SUM(CASE
                         WHEN t."ActionType" IN (38) AND t."DueDate" >= '2021-11-04'::date
                             THEN t."Quantity"
                         ELSE 0
                     END) OVER(PARTITION BY "a_Instrument"."Id" ORDER BY t."TransactionDate"),
                 ROW_NUMBER() OVER(PARTITION BY "a_Instrument"."Id" ORDER BY t."TransactionDate" DESC),
                 SUM(CASE
                         WHEN t."ActionType" IN (38) AND t."DueDate" >= '2021-11-04'::date
                             THEN t."Quantity"
                         ELSE 0
                     END) OVER(PARTITION BY "a_Instrument"."Id" ORDER BY t."TransactionDate")
             FROM
                 "InstrumentTransactions" t
                     LEFT JOIN "Instruments" "a_Instrument" ON t."InstrumentId" = "a_Instrument"."Id"
                     LEFT JOIN "Customers" "a_Customer" ON "a_Instrument"."CompanyId" = "a_Customer"."Id"
             WHERE
                 t."Retracted" IS NULL AND "a_Customer"."IdentityId" = 8 AND
                     t."TransactionDate" <= '2021-11-04'::date 
             
         )
SELECT
    t1."TransactionDate",
    t1."Id",
    t1."SumOfCostPriceOnOwnedSecurities",
    t1."SumOfCostPriceOnOwnedSecuritiesInCurrency",
    t1."Quantity",
    t1."LoanQty_1",
    t1."RowNumber"
FROM
    "transactionsAggregateCte" t1 
```

### Environment details
linq2db version: *5.9.0*
Database Server: *postgress*
Database Provider: *scaleway*
Operating system: *linux*
.NET Framework: *core 5*

**Comment by dagtveit** [comment] 2021-12-12 20:04
Anything happening ?

**Comment by dagtveit** [comment] 2021-12-13 11:58
Thanks for the response. is there anything more you need to research this issue ?

**Comment by dagtveit** [comment] 2021-12-13 12:04
Also what is the ca estimated timeline for 3.7.0. and will that require upgrade to dotnet 6 ?

**Comment by MaceWindu** [comment] 2021-12-13 12:10
there is no estimate for 3.7 right now, we probably will release another 3.6.x release with fixes only when we have something to release.

Also there is no plans to change min. platform requirements for 3.x (we probably will phaseout .net core 2.1 in v4)

**Comment by dagtveit** [comment] 2021-12-13 12:12
is there somehow this can be fixed in an earlier version ?. this is blocking my migration to postgress server on my last service.

**Comment by MaceWindu** [comment] 2021-12-13 12:12
I'm waiting for @sdanyliv  response for it as he is more familiar with it

**Comment by dagtveit** [comment] 2021-12-13 12:14
ok. thanks for the reply. do you have any other means of communication. i would like to discuss something a bit off topic for this bug.

**Comment by sdanyliv** [comment] 2021-12-13 13:31
Unfortunately I cannot reproduce. I need small query which do not work. Or post your model classes used in query and filter definition.

**Comment by dagtveit** [comment] 2021-12-13 13:41
```
using System;
using System.Collections.Generic;

namespace VoucherDbContext.Models
{
    public partial class InstrumentTransaction
    {
        public InstrumentTransaction()
        {
            CategorySecuritiesTransactions = new HashSet<InstrumentTransactionsCategories>();
            InverseCounterTransaction = new HashSet<InstrumentTransaction>();
            InverseParentTransactions = new HashSet<InstrumentTransaction>();
            Pogotransactions = new HashSet<GlTransaction>();
            GlTransactions = new HashSet<GlTransaction>();
        }

        public int Id { get; set; }
        public DateTime TransactionDate { get; set; }
        public decimal Quantity { get; set; }
        public decimal Amount { get; set; }
        public DateTime Created { get; set; }
        public DateTime Changed { get; set; }
        public decimal Fee { get; set; }
        public int? ChangedById { get; set; }
        public int? CreatedById { get; set; }
        public int? InstrumentId { get; set; }
        public int? ParentTransactionsId { get; set; }
        public int? VoucherDocumentMetaId { get; set; }
        public int ActionType { get; set; }
        public string Broker { get; set; }
        public bool UpdateGl { get; set; }
        public decimal Interests { get; set; }
        public bool UpdatedGl { get; set; }
        public DateTime GlStatusChangeDate { get; set; }
        public int? CounterTransactionId { get; set; }
        public int? SecuritiesTypeId { get; set; }
        public DateTime? Retracted { get; set; }
        public int UpdateGlfailedCount { get; set; }
        public string ExternalGeneralLedgerId { get; set; }
        public string VoucherNr { get; set; }
        public string CurrencyCode { get; set; }
        public decimal? CurrencyAmount { get; set; }
        public int? CurrencyId { get; set; }
        public decimal? CurrencyInterests { get; set; }

        public virtual User ChangedBy { get; set; }
        public virtual InstrumentTransaction CounterTransaction { get; set; }
        public virtual User CreatedBy { get; set; }
        public virtual InstrumentCurrency InstrumentCurrency { get; set; }
        public virtual Instrument Instrument { get; set; }
        public virtual InstrumentTransaction ParentTransaction { get; set; }
        public virtual InstrumentType InstrumentType { get; set; }
        public virtual ICollection<InstrumentTransactionsCategories> CategorySecuritiesTransactions { get; set; }
        public virtual ICollection<InstrumentTransaction> InverseCounterTransaction { get; set; }
        public virtual ICollection<InstrumentTransaction> InverseParentTransactions { get; set; }
        //old 1 to many
        public virtual ICollection<GlTransaction> Pogotransactions { get; set; }
        //many to many
        public virtual ICollection<GlTransaction> GlTransactions { get; set; }
        public string SubjectId { get; set; }
        public int? ExternalDocumentId { get; set; }
        public int? ExternalRowId { get; set; }
        public DateTime? DueDate { get; set; }
    }
}
```

**Comment by sdanyliv** [comment] 2021-12-13 13:42
Simplify this as much as as possible, simplify query. And `FILTER` class

**Comment by dagtveit** [comment] 2021-12-13 14:24
The filter class only gives a list of integer values example

 public static List<int>  InstrumentLoanQuantityList = new List<int>
        {
            (int) Constants.ActionType.InstrumentLoan,
        };


and if you look ath the code for that particular calculation it does add this "more correctly" i say more as i havent gotten far enough to realy test the numbers yet. but it produces atleast this
 
  SUM(CASE
                         WHEN t."ActionType" IN (38) AND t."DueDate" >= '2021-11-04'::date
                             THEN t."Quantity"
                         ELSE 0
                     END) OVER(PARTITION BY "a_Instrument"."Id" ORDER BY t."TransactionDate")

all the other filters are only different integers.

so this seem to produce correctly but not the same if they dont have additional date filter
Sql.Ext.Sum(SecuritiesTransactionsFilters.InstrumentLoanQuantityList.Contains(t.ActionType) && t.DueDate >= dateModified ? t.Quantity : 0)

**Comment by dagtveit** [comment] 2021-12-13 14:47
SumOfCostPriceOnOwnedSecurities = Sql.Ext.Sum(new List<int>{1,2}.Contains(t.ActionType) ? t.Amount : 0) this procuses the same issue while
SumOfCostPriceOnOwnedSecurities = Sql.Ext.Sum(new HashSet<int>{1,2}.Contains(t.ActionType) ? t.Amount : 0)
this dont. so it seems like to be an issue with lists. i dont mind changing all the filters to hashset instead. thats is probalby what it should have been all allong. ill try that and report back

**Comment by dagtveit** [comment] 2021-12-18 22:38
Suggested solution worked fine

**Comment by Kshitij-Kafle-123** [comment] 2022-01-03 16:27
Filter LINQ Queries looks tedious, is there any way to simplify them.

**Comment by MaceWindu** [comment] 2024-09-14 15:31
Closing as no full code were provided to reproduce issue

**Closed by MaceWindu** 2024-09-14 15:31 UTC
Labels: type: bug, status: has-tests, status: needs-tests, area: efcore
