### ISSUE TITLE
SQLite provider

### ISSUE THREAD

**Issue by JTrotta** [linq2db/linq2db#1981] opened 2019-11-16 07:08 UTC
Describe your issue.
Querying SQLite does not work.

```
Exception message:
Stack trace:
`   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, StackCrawlMarkHandle stackMark, ObjectHandleOnStack assemblyLoadContext, Boolean loadTypeFromPartialName, ObjectHandleOnStack type, ObjectHandleOnStack keepalive)
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext, Boolean loadTypeFromPartialName)
   at System.RuntimeType.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase, StackCrawlMark& stackMark)
   at System.Type.GetType(String typeName, Boolean throwOnError)
   at LinqToDB.DataProvider.DynamicDataProviderBase.get_DataReaderType()
   at LinqToDB.Data.DataConnection.LinqToDB.IDataContext.get_DataReaderType()
   at LinqToDB.Linq.Builder.ExpressionBuilder..ctor(Query query, IDataContext dataContext, Expression expression, ParameterExpression[] compiledParameters)
   at LinqToDB.Linq.Query`1.CreateQuery(IDataContext dataContext, Expression expr)
   at LinqToDB.Linq.Query`1.GetQuery(IDataContext dataContext, Expression& expr)
   at LinqToDB.Linq.ExpressionQuery`1.GetQuery(Expression& expression, Boolean cache)
   at LinqToDB.Linq.ExpressionQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at RPTestcore3.Program.Start2() in D:\Visual Studio 2019\Projects\RPTestcore3\RPTestcore3\Program.cs:line 23
   at RPTestcore3.Program.Main(String[] args) in D:\Visual Studio 2019\Projects\RPTestcore3\RPTestcore3\Program.cs:line 15
```

### Steps to reproduce
1) Add linq2db.SQLite library
2) Update System.Data.SQLite.Core from 1.0.107 -> 1.0.112

Starting db query  got error:
System.IO.FileNotFoundException: 'Could not load file or assembly 'Microsoft.Data.Sqlite, Culture=neutral, PublicKeyToken=null'.'

```c#
            using (var db = new DataModels.TestDB())
            {
                var q = db.LobuSettings.OrderBy(x => x.Name).ToList();

                foreach (var c in q)
                    Console.WriteLine(c.Name);
            }
```

### Environment details
linq2db version: *2.9.4*
Database Server: *SQLite*
Database Provider: *System.Data.SQLite*
Operating system: *Windows/Linux*
.NET Framework: *.net core 3*

**Comment by MaceWindu** [comment] 2019-11-16 08:19
Tries same steps on Windows, but cannot reproduce it. Was `System.Data.SQLite.dll` copied to bin during build?

**Comment by jogibear9988** [comment] 2019-11-16 09:33
Also think we have a hole here: https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/DataProvider/SQLite/SQLiteTools.cs

We always have only one AssemblyName, even if ProviderDetector (https://github.com/linq2db/linq2db/blob/e6d3199cde3485b8ddac2d626e087e5b113132a3/Source/LinqToDB/DataProvider/SQLite/SQLiteTools.cs#L34) can switch on the IConnectionStringSettings the assemblyname is always static

**Comment by MaceWindu** [comment] 2019-11-16 09:35
Yep, don't like current implementation of tools too. Something I'm going to address in PR I'm working on right now.

**Comment by MaceWindu** [comment] 2019-11-21 15:12
I'm stupid. Just noticed assembly name in error message. Yep, as @jogibear9988 mentioned, it is a bug in provider type detection. I would prefer to not fix it now, as I'm working on major refactoring of it for 3.0 anyway.

As workaround you need to tell linq2db which provider you want to use. E.g. by adding `Classic` to connection name.

**Comment by koujiangheng** [comment] 2020-02-06 14:16
when i use sqlite nuget it will tell the same exception as his, i swith to microsoft.sqlite.data it will throw ```Format of the initialization string does not conform to specification starting at index 0```

**Comment by MaceWindu** [comment] 2020-02-06 14:49
How you configure your sqlite connection? As I stated above, you need to specify sqlite provider type more explicitly.
Regarding exception - it's hard to say where issue is without stack trace

**Comment by koujiangheng** [comment] 2020-02-06 14:59
Thanks MaceWindu.

> How you configure your sqlite connection? As I stated above, you need to specify sqlite provider type more explicitly.
> Regarding exception - it's hard to say where issue is without stack trace, as it is generic `Format` exception message

**Comment by MaceWindu** [comment] 2020-02-29 10:22
Should be fixed in preview2 as detection logic improved by #1961

**Closed by MaceWindu** 2020-02-29 10:22 UTC
Labels: type: bug
