### ISSUE TITLE
DataContext Close

### ISSUE THREAD

**Issue by croban** [linq2db/linq2db#1891] opened 2019-09-13 13:44 UTC
If I run this Code

```c#
{
var db = new MyContext();
var x = db.SomeTable.ToList();
var y = db.SomeTable.ToList();
}
```
until context end i have 2 connections open (sleeping) on db, after context ends they are released.

but if i ran this code
```c#
{
var db = new MyContext();
db.OnTraceConnection = (e) =>
{
         if (e.TraceInfoStep == TraceInfoStep.Completed || e.TraceInfoStep == TraceInfoStep.Error)
                    e.DataConnection.Close();
};
var x = db.SomeTable.ToList();
var y = db.SomeTable.ToList();
}
```
until context end i have 1 connections open(sleeping) on db, after context ends this is released.

### Environment details
linq2db version: 2.9.0
Database Server: Microsoft Sql Server
Database Provider: SqlServerVersion.v2017
Operating system: Windows
.NET Framework: 4.7.2

**Comment by sdanyliv** [comment] 2019-09-13 13:48
@croban, why not disposing context (`DataConnection`?) after usage as described [here](https://linq2db.github.io/articles/general/Managing-data-connection.html):
```cs
using (var db = new MyContext())
{
   var x = db.SomeTable.ToList();
   var y = db.SomeTable.ToList();
} 
```

**Comment by sdanyliv** [comment] 2019-09-13 13:59
`DataContext` do not need closing. It closes connection after each request, if it is not specified `KeepConnectionAlive = true`.

**Comment by croban** [comment] 2019-09-13 14:55
I think that, that is partly true. It does not close it's disposing connection and this dataconnection instance will be there until datacontext released. Until datacontext is also disposed there will be an connection on database in sleeping mode with own spid and will not be reused by anyone (connection pool blocking). 
So if the datacontext do two queries inside same code context e.g.
```c#
{
var x = db.SomeTable.ToList();
var y = db.SomeTable.ToList();
}
```
there will be two connection with own spid (try it with debug and look what is happening on db with sp_who), those connection will be released after datacontext is disposed. 

And now if you put this there will be only one connection with one spid inside database.
```c#
db.OnTraceConnection = (e) =>
{
         if (e.TraceInfoStep == TraceInfoStep.Completed || e.TraceInfoStep == TraceInfoStep.Error)
                    e.DataConnection.Close();
};
```

Therefore I think inside DataContext.Close method DatabaseConnection must be closed instead of disposing it and on DataContext Dispose DatabaseConnection must be disposed.

**Comment by croban** [comment] 2019-09-13 15:01
You could try this test:

```c#
            var db = new MyContext();
            db.OnTraceConnection = (e) =>
            {
                  //comment out, without this code you will run into connection pool error
                  //if (e.TraceInfoStep == TraceInfoStep.Completed || e.TraceInfoStep == TraceInfoStep.Error)
                    //e.DataConnection.Close();
            };
            db.CloseAfterUse = true;

            //be sure that connection pool on db is smaller than 200 connections
            for (int i = 0; i < 200; i++)
            {
                var x = await db.SomeTable.ToListAsync();
                Console.WriteLine("Container" + i);
            }
```

**Comment by sdanyliv** [comment] 2019-09-13 15:35
Very and very strange. Looks like a bug in `SqlConnection`.

**Comment by sdanyliv** [comment] 2019-09-13 15:41
Also it is reproducible only for async version. Investigation needed.

**Comment by sdanyliv** [comment] 2019-09-20 09:00
@croban, fix prepared. I hope it will be released next Thursday.

**Closed** 2019-10-02 09:56 UTC
Labels: area: data-context, status: patch-proposed, type: bug
