### ISSUE TITLE
NullReferenceException with self generated Expression Tree

### ISSUE THREAD

**Issue by Fruchuxs** [linq2db/linq2db#1202] opened 2018-06-21 10:00 UTC
I get a NullReferenceException with a self generated Select expression tree. I also generate some Null-Checks but I dont know (after some hours of debugging), which part of my expression tree triggers the exception. Can you handle this case and add a meaningful exception message for better debug purposes?

```
Unhandled Exception: NullReferenceException
  System.NullReferenceException: Object reference not set to an instance of an object.
   at LinqToDB.Linq.Builder.SelectContext.BuildExpression(Expression expression, Int32 level, Boolean enforceServerSide)
   at LinqToDB.Linq.Builder.SelectContext.BuildExpression(Expression expression, Int32 level, Boolean enforceServerSide)
   at LinqToDB.Linq.Builder.ExpressionBuilder.TransformExpression(IBuildContext context, Expression expr, Boolean enforceServerSide)
   at LinqToDB.Linq.Builder.ExpressionBuilder.<>c__DisplayClass72_0.<BuildExpression>b__0(Expression expr)
   at LinqToDB.Expressions.Extensions.Transform(Expression expr, Func`2 func)
   at LinqToDB.Expressions.Extensions.<>c__DisplayClass34_1.<Transform>b__1(MemberBinding b)
   at LinqToDB.Expressions.Extensions.Transform2[T](ICollection`1 source, Func`2 func)
   at LinqToDB.Expressions.Extensions.Transform(Expression expr, Func`2 func)
   at LinqToDB.Expressions.Extensions.<>c__DisplayClass34_1.<Transform>b__1(MemberBinding b)
   at LinqToDB.Expressions.Extensions.Transform2[T](ICollection`1 source, Func`2 func)
   at LinqToDB.Expressions.Extensions.Transform(Expression expr, Func`2 func)
   at LinqToDB.Linq.Builder.SelectContext.BuildExpression(Expression expression, Int32 level, Boolean enforceServerSide)
   at LinqToDB.Linq.Builder.SelectContext.BuildQuery[T](Query`1 query, ParameterExpression queryParameter)
   at LinqToDB.Linq.Builder.FirstSingleBuilder.FirstSingleContext.BuildQuery[T](Query`1 query, ParameterExpression queryParameter)
   at LinqToDB.Linq.Builder.ExpressionBuilder.Build[T]()
   at LinqToDB.Linq.Query`1.CreateQuery(IDataContext dataContext, Expression expr)
   at LinqToDB.Linq.Query`1.GetQuery(IDataContext dataContext, Expression& expr)
   at LinqToDB.Linq.ExpressionQuery`1.GetQuery(Expression& expression, Boolean cache)
   at LinqToDB.Linq.ExpressionQuery`1.System.Linq.IQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.SingleOrDefault[TSource](IQueryable`1 source)
```

### Environment details
linq2db version: *1.10.2*

**Comment by sdanyliv** [comment] 2018-06-21 10:10
> linq2db version: 1.10.2

I don't think that this will solve problem, but updating a good idea sometimes.

Here we can not help you without expression tree.
Try to post here data generated by this call:
```cs
IQueryable<Some> query = // some your linq magic
string thisStr = query.GenerateTestString();
```

**Comment by Fruchuxs** [comment] 2018-06-21 11:02
Sorry, I forget to mention out, that I use .NET Core 2.1.1. NuGet doesn't show any Updates for me.

```c#
//---------------------------------------------------------------------------------------------------
// This code was generated by LinqToDB.
//---------------------------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Linq.Expressions;
using LinqToDB;

using NUnit.Framework;

namespace SomeNamespace.Models
{
	public class ArticleModel
	{
		public int ArticleId { get; set; }

		public string ArticleNo { get; set; }

		public string Description { get; set; }

		public string Gtin { get; set; }

		public string ProductNo { get; set; }

		public string PostArticleNo { get; set; }

		public string InformationArtNo { get; set; }

		public Decimal? TaxRate { get; set; }

		public Int16? PriceUnit { get; set; }

		public Decimal? PurchPrice { get; set; }

		public Decimal? SalePrice { get; set; }

		public DateTime? DatePrice { get; set; }

		public bool Deliverable { get; set; }

		public Double? StockQuantity { get; set; }

		public string Unit { get; set; }

		public Double? PackQuantity { get; set; }

		public string PackUnit { get; set; }

		public Double? OrderQuantity { get; set; }

		public Int16? DeliveryDays { get; set; }

		public DateTime? DateModified { get; set; }

		public SomeNamespace.Models.InformationModel Information { get; set; }
	}
}

namespace SomeNamespace.Models
{
	public class InformationModel
	{
		public int? InformationId { get; set; }

		public string Description { get; set; }
	}
}

namespace SomeNamespace.dal.Tables
{
	LinqToDB.Mapping.TableAttribute
	public class ArticleRow
	{
		LinqToDB.Mapping.ColumnAttribute
		public string ArticleNo { get; set; }

		LinqToDB.Mapping.ColumnAttribute
		public string Description { get; set; }

		LinqToDB.Mapping.ColumnAttribute
		public string Gtin { get; set; }

		LinqToDB.Mapping.ColumnAttribute
		public string ProductNo { get; set; }

		LinqToDB.Mapping.ColumnAttribute
		public string PostArticleNo { get; set; }

		LinqToDB.Mapping.ColumnAttribute
		public string InformationArtNo { get; set; }

		LinqToDB.Mapping.ColumnAttribute
		public Decimal? TaxRate { get; set; }

		LinqToDB.Mapping.ColumnAttribute
		public Int16? PriceUnit { get; set; }

		LinqToDB.Mapping.ColumnAttribute
		public string Unit { get; set; }

		LinqToDB.Mapping.ColumnAttribute
		public Double? PackQuantity { get; set; }

		LinqToDB.Mapping.ColumnAttribute
		public string PackUnit { get; set; }

		LinqToDB.Mapping.ColumnAttribute
		public Double? OrderQuantity { get; set; }

		LinqToDB.Mapping.ColumnAttribute
		public Int16? DeliveryDays { get; set; }
	}
}

namespace SomeNamespace.dal.Tables
{
	LinqToDB.Mapping.TableAttribute
	public class SpecialArticleRow
	{
		LinqToDB.Mapping.PrimaryKeyAttribute
		public int ArticleId { get; set; }

		LinqToDB.Mapping.ColumnAttribute
		public Decimal? PurchPrice { get; set; }

		LinqToDB.Mapping.ColumnAttribute
		public Decimal? SalePrice { get; set; }

		LinqToDB.Mapping.ColumnAttribute
		public DateTime? DatePrice { get; set; }

		LinqToDB.Mapping.ColumnAttribute
		public bool Deliverable { get; set; }

		LinqToDB.Mapping.ColumnAttribute
		public Double? StockQuantity { get; set; }

		LinqToDB.Mapping.ColumnAttribute
		public DateTime? DateModified { get; set; }
	}
}

namespace SomeNamespace.dal.Tables
{
	LinqToDB.Mapping.TableAttribute
	public class InformationRow
	{
		LinqToDB.Mapping.PrimaryKeyAttribute
		LinqToDB.Mapping.IdentityAttribute
		public int InformationId { get; set; }

		LinqToDB.Mapping.ColumnAttribute
		public string Description { get; set; }
	}
}

namespace Tests.UserTests
{
	[TestFixture]
	public class UserTest : TestBase
	{
		[Test, DataContextSource]
		public void Test(string context)
		{
			// --  MySql
DECLARE @CustomerId1 Int32
SET     @CustomerId1 = 31
DECLARE @CurrentViewId Int32
SET     @CurrentViewId = 21

SELECT
	`articleRow`.`ArticleId`,
	`articleRow`.`ViewId`,
	`articleRow`.`ArticleNo`,
	`articleRow`.`Description`,
	`articleRow`.`Gtin`,
	`articleRow`.`ProductNo`,
	`articleRow`.`PostArticleNo`,
	`articleRow`.`InformationArtNo`,
	`articleRow`.`InformationId`,
	`articleRow`.`TaxRate`,
	`articleRow`.`PriceUnit`,
	`articleRow`.`PurchPrice`,
	`articleRow`.`SalePrice`,
	`articleRow`.`DatePrice`,
	`articleRow`.`Deliverable`,
	`articleRow`.`StockQuantity`,
	`articleRow`.`Unit`,
	`articleRow`.`PackQuantity`,
	`articleRow`.`PackUnit`,
	`articleRow`.`OrderQuantity`,
	`articleRow`.`DeliveryDays`,
	`articleRow`.`DateModified`,
	`leftInformationJoin`.`InformationId` as `InformationId1`,
	`leftInformationJoin`.`Description` as `Description1`,
	`leftSpecialArtJoin`.`ArticleId` as `ArticleId1`,
	`leftSpecialArtJoin`.`CustomerId`,
	`leftSpecialArtJoin`.`PurchPrice` as `PurchPrice1`,
	`leftSpecialArtJoin`.`SalePrice` as `SalePrice1`,
	`leftSpecialArtJoin`.`DatePrice` as `DatePrice1`,
	`leftSpecialArtJoin`.`Deliverable` as `Deliverable1`,
	`leftSpecialArtJoin`.`StockQuantity` as `StockQuantity1`,
	`leftSpecialArtJoin`.`DateModified` as `DateModified1`
FROM
	`article` `articleRow`
		LEFT JOIN `Information` `leftInformationJoin` ON `articleRow`.`InformationId` = `leftInformationJoin`.`InformationId`
		LEFT JOIN `SpecialArticle` `leftSpecialArtJoin` ON `articleRow`.`ArticleId` = `leftSpecialArtJoin`.`ArticleId` AND @CustomerId1 = `leftSpecialArtJoin`.`CustomerId`
WHERE
	`articleRow`.`ViewId` = @CurrentViewId
.Select(dto => new ArticleModel() {Information = IIF((dto.Information != null), new InformationModel() {InformationId = IIF((dto.Information == null), Convert(null, Nullable`1), Convert(dto.Information.InformationId, Nullable`1)), Description = dto.Information.Description}, null), ArticleId = IIF((dto.SpecialArticleRow == null), Convert(0, Int32), dto.SpecialArticleRow.ArticleId), ArticleNo = IIF((dto.Article == null), Convert(null, String), dto.Article.ArticleNo), Description = IIF((dto.Article == null), Convert(null, String), dto.Article.Description), Gtin = IIF((dto.Article == null), Convert(null, String), dto.Article.Gtin), ProductNo = IIF((dto.Article == null), Convert(null, String), dto.Article.ProductNo), PostArticleNo = IIF((dto.Article == null), Convert(null, String), dto.Article.PostArticleNo), InformationArtNo = IIF((dto.Article == null), Convert(null, String), dto.Article.InformationArtNo), TaxRate = IIF((dto.Article == null), Convert(null, Nullable`1), dto.Article.TaxRate), PriceUnit = IIF((dto.Article == null), Convert(null, Nullable`1), dto.Article.PriceUnit), PurchPrice = IIF((dto.SpecialArticleRow == null), Convert(null, Nullable`1), dto.SpecialArticleRow.PurchPrice), SalePrice = IIF((dto.SpecialArticleRow == null), Convert(null, Nullable`1), dto.SpecialArticleRow.SalePrice), DatePrice = IIF((dto.SpecialArticleRow == null), Convert(null, Nullable`1), dto.SpecialArticleRow.DatePrice), Deliverable = IIF((dto.SpecialArticleRow == null), Convert(False, Boolean), dto.SpecialArticleRow.Deliverable), StockQuantity = IIF((dto.SpecialArticleRow == null), Convert(null, Nullable`1), dto.SpecialArticleRow.StockQuantity), Unit = IIF((dto.Article == null), Convert(null, String), dto.Article.Unit), PackQuantity = IIF((dto.Article == null), Convert(null, Nullable`1), dto.Article.PackQuantity), PackUnit = IIF((dto.Article == null), Convert(null, String), dto.Article.PackUnit), OrderQuantity = IIF((dto.Article == null), Convert(null, Nullable`1), dto.Article.OrderQuantity), DeliveryDays = IIF((dto.Article == null), Convert(null, Nullable`1), dto.Article.DeliveryDays), DateModified = IIF((dto.SpecialArticleRow == null), Convert(null, Nullable`1), dto.SpecialArticleRow.DateModified)})
			using (var db = GetDataContext(context))
			{
				var quey = db.GetTable<SomeNamespace.dal.Tables.ArticleRow>()
					.GroupJoin(
						db.GetTable<SomeNamespace.dal.Tables.InformationRow>(),
						articleRow => articleRow.InformationId,
						leftInformation => (int?)leftInformation.InformationId,
						(articleRow, leftInformationJoin) => new
						{
							articleRow = articleRow,
							leftInformationJoin = leftInformationJoin
						})
					.SelectMany(
						tp0 => tp0.leftInformationJoin
							.DefaultIfEmpty(),
						(tp0, InformationRow) => new
						{
							tp0 = tp0,
							InformationRow = InformationRow
						})
					.Where(
						tp1 => ((int?)tp1.tp0.articleRow.ViewId == value(SomeNamespace.Repositories.ArticleRepository).fArticleViewInfo.CurrentViewId))
					.GroupJoin(
						db.GetTable<SomeNamespace.dal.Tables.SpecialArticleRow>(),
						tp1 => new
						{
							ArticleId = tp1.tp0.articleRow.ArticleId,
							CustomerId = value(SomeNamespace.Repositories.ArticleRepository).fCustomerInfo.CustomerId
						},
						leftSpecialArt => new
						{
							ArticleId = leftSpecialArt.ArticleId,
							CustomerId = leftSpecialArt.CustomerId
						},
						(tp1, leftSpecialArtJoin) => new
						{
							tp1 = tp1,
							leftSpecialArtJoin = leftSpecialArtJoin
						})
					.SelectMany(
						tp2 => tp2.leftSpecialArtJoin
							.DefaultIfEmpty(),
						(tp2, SpecialArticleRow) => new
						{
							Article = tp2.tp1.tp0.articleRow,
							Information = tp2.tp1.InformationRow,
							SpecialArticleRow = SpecialArticleRow
						})
					.Select(
						dto => new SomeNamespace.Models.ArticleModel()
						{
							Information = ((dto.Information != null) ? new SomeNamespace.Models.InformationModel()
							{
								InformationId = ((dto.Information == null) ? (int?)null : (int?)dto.Information.InformationId),
								Description = dto.Information.Description
							} : null),
							ArticleId = ((dto.SpecialArticleRow == null) ? (int)0 : dto.SpecialArticleRow.ArticleId),
							ArticleNo = ((dto.Article == null) ? (string)null : dto.Article.ArticleNo),
							Description = ((dto.Article == null) ? (string)null : dto.Article.Description),
							Gtin = ((dto.Article == null) ? (string)null : dto.Article.Gtin),
							ProductNo = ((dto.Article == null) ? (string)null : dto.Article.ProductNo),
							PostArticleNo = ((dto.Article == null) ? (string)null : dto.Article.PostArticleNo),
							InformationArtNo = ((dto.Article == null) ? (string)null : dto.Article.InformationArtNo),
							TaxRate = ((dto.Article == null) ? (Decimal?)null : dto.Article.TaxRate),
							PriceUnit = ((dto.Article == null) ? (Int16?)null : dto.Article.PriceUnit),
							PurchPrice = ((dto.SpecialArticleRow == null) ? (Decimal?)null : dto.SpecialArticleRow.PurchPrice),
							SalePrice = ((dto.SpecialArticleRow == null) ? (Decimal?)null : dto.SpecialArticleRow.SalePrice),
							DatePrice = ((dto.SpecialArticleRow == null) ? (DateTime?)null : dto.SpecialArticleRow.DatePrice),
							Deliverable = ((dto.SpecialArticleRow == null) ? (bool)False : dto.SpecialArticleRow.Deliverable),
							StockQuantity = ((dto.SpecialArticleRow == null) ? (Double?)null : dto.SpecialArticleRow.StockQuantity),
							Unit = ((dto.Article == null) ? (string)null : dto.Article.Unit),
							PackQuantity = ((dto.Article == null) ? (Double?)null : dto.Article.PackQuantity),
							PackUnit = ((dto.Article == null) ? (string)null : dto.Article.PackUnit),
							OrderQuantity = ((dto.Article == null) ? (Double?)null : dto.Article.OrderQuantity),
							DeliveryDays = ((dto.Article == null) ? (Int16?)null : dto.Article.DeliveryDays),
							DateModified = ((dto.SpecialArticleRow == null) ? (DateTime?)null : dto.SpecialArticleRow.DateModified)
						});
			}
		}
	}
}

```

**Comment by sdanyliv** [comment] 2018-06-21 11:06
Current version is 2.0.0 and today we expecting release 2.1.0.
Will check if i have time to analyse that. BTW, clone LinqToDB repository and just add reference to project LinqToDB.csproj - and you will see what happened here.

**Comment by sdanyliv** [comment] 2018-06-21 11:07
So you have generated only projection part?

**Comment by Fruchuxs** [comment] 2018-06-21 11:29
Yes, the select statement as lambda expression.

**Comment by Fruchuxs** [comment] 2018-06-21 11:33
Btw. I assume that the problem is the nested expression Tree "Information". But the null checks are correct. It seems to work if I remove this part. But the null checks in the tree are correct.

**Comment by sdanyliv** [comment] 2018-06-21 12:31
Unfortunately i can not reproduce problem on our side. 
I suggest to update to 2.0.0 version. Note that `linq2db.Core` is outdated package. `linq2db` package supports .NET Core instead.

**Comment by Fruchuxs** [comment] 2018-06-21 12:50
Cuz of significant changes in Version 2.0, I can't upgrade to this version ad hoc.
For example SelectQuery.IsUpdae, SelectQuery.Update and the nested classes SelectQuery.SearchCondition, SelectQuery.Condition is missing (+ some other properties and classes).

I can't also use the 1.10.1 Repo because it's not .net core compatible.

**Comment by sdanyliv** [comment] 2018-06-21 12:56
Yes in 2.0.0 we have refactored Sql part. We have introduced `SqlStatement` because `SelectQuery` was over-weighted with non related to query information. Everything is there but moved to other place.
This class may help to understand.
https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/SqlQuery/SqlExtensions.cs#L10

**Comment by Fruchuxs** [comment] 2018-06-21 13:32
Thanks. I had adjustet our adjustments but I still get the exception. The exception occours in Line 247 of SelectContext.cs. The variable sequence is null, because of Line 1017 which retuns null if the NodeType ist not equals ExpressionTypre.Parameter.

The problematic expression is
`c# InformationId = ((dto.Information == null) ? (int?)null : (int?)dto.Information.InformationId)`

because the expressiontype is "Conditional".
Any idea to fix this?

**Comment by sdanyliv** [comment] 2018-06-21 14:52
Show me your code that generates projection.

**Comment by Fruchuxs** [comment] 2018-06-21 15:12
The problematic Path is generated by Automapper 6.2.2. The original code from where my code is based is here:
https://github.com/AutoMapper/AutoMapper/blob/master/src/AutoMapper/QueryableExtensions/ProjectionExpression.cs#L60

Documentation: 
http://docs.automapper.org/en/stable/Projection.html

For some special problems I extend the automapper behavior, what is not the problem (I commented this all out, can reproduce the problem and theoretically my Snippet below shall do the same as ProjectTo from AutoMapper).
Here the Code to reproduce the Mapping:

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;
using AutoMapper;

namespace SomeNamespace.Project
{
    class QueryProjector
    {
        private readonly IMapper fMapper;

        public QueryProjector(IMapper aMapper)
        {
            fMapper = aMapper;
        }

        public IQueryable<TDestinationModel> ProjectTo<TDestinationModel>(IQueryable aSourceQuery)
        {
            var naivMapping = GetMapExpression(typeof(TDestinationModel), aSourceQuery.ElementType);
            var bindings = new List<MemberBinding>(naivMapping.Bindings);
            var rootParameter = Expression.Parameter(aSourceQuery.ElementType, "dto");

            var newMemberInit = Expression.MemberInit(naivMapping.NewExpression, bindings);
            var lambda = CreateLambdaExpression(
                rootParameter,
                newMemberInit,
                (DestinationType: typeof(TDestinationModel), SourceType: aSourceQuery.ElementType));

            var query = AsQueryable<TDestinationModel>(aSourceQuery, lambda);

            return query;
        }

        private MemberInitExpression GetMapExpression(Type aDestination, Type aSource)
        {
            var mapping = fMapper.ConfigurationProvider.ExpressionBuilder.GetMapExpression(
                aSource,
                aDestination,
                new Dictionary<string, object>(),
                new MemberInfo[] { });

            return mapping.FirstOrDefault().Body as MemberInitExpression;
        }

        private LambdaExpression CreateLambdaExpression(ParameterExpression aRootParameter, MemberInitExpression aMemberInitExpression,
            (Type DestinationType, Type SourceType) aTarget) =>
            Expression.Lambda(
                typeof(Func<,>)
                    .MakeGenericType(aTarget.SourceType, aTarget.DestinationType),
                body: aMemberInitExpression,
                parameters: aRootParameter);

        private IQueryable<TDestinationModel> AsQueryable<TDestinationModel>(IQueryable aSourceQuery, LambdaExpression aSelectExpression)
        {
            var selectClause = Expression.Call(
                typeof(Queryable),
                nameof(Queryable.Select),
                new Type[]
                {
                    aSourceQuery.ElementType,
                    typeof(TDestinationModel)
                },
                Expression.Constant(aSourceQuery),
                aSelectExpression);

            return (IQueryable<TDestinationModel>)aSourceQuery.Provider.CreateQuery(selectClause);
        }
    }
}
```


The funny thing is, that this seems to work work:
```c#
query.Select(p => new ArticleModel()
{
    Information = p.InformationRow != null ? new InformationModel()
    {
        InformationId = p.InformationRow == null ? (int?)null : p.InformationRow.InformationId,
        Description = p.InformationRow.Description
    } : null,
}.ToList());
```

**Comment by sdanyliv** [comment] 2018-06-21 21:45
@Fruchuxs, do you have a problem or you still need our assistance?

**Comment by Fruchuxs** [comment] 2018-06-22 08:46
There was an error in my code, but this wasn't the problem. I updated the Sourcecode of my QueryProjector above.
I have also write a simple Tests to check if the code works with LINQ, and works fine (I also debugged the Test, because the assert.true statement is quite stupid).

```c#
using System;
using System.Collections.Generic;
using System.Linq;
using AutoMapper;
using NUnit.Framework;

namespace Tests
{
    [TestFixture]
    class DebugTest
    {
        #region NestedMocks
        class FruitsTableSource
        {
            public int FruitId { get; set; }
            public string FruitName { get; set; }
        }

        class FruitsAmountTableSource
        {
            public int FruitId { get; set; }
            public int FruitAmount { get; set; }
        }

        class FruitDestination
        {
            public int ID { get; set; }
            public string Name { get; set; }
            public int Amount { get; set; }
        }

        class FruitAmountDestination
        {
            public int ID { get; set; }
            public int Count { get; set; }
        }

        class FruitAggregatedDestination
        {
            public FruitDestination Fruit { get; set; }
            public FruitAmountDestination Amount { get; set; }
        }
        #endregion

        private Mapper fAutoMapper;
        private DebugProjector fProjector;
        private IQueryable<FruitsTableSource> fFruitRows;
        private IQueryable<FruitsAmountTableSource> fFruitAmountRows;

        [SetUp]
        public void SetUp()
        {
            var mapperConfig = new MapperConfiguration(cfg =>
            {
                cfg.CreateMissingTypeMaps = true;

                cfg.AddProfiles(GetType().Assembly);

                cfg.CreateMap<FruitsTableSource, FruitDestination>()
                    .ForMember(p => p.Name, p => p.MapFrom(t => t.FruitName));
                cfg.CreateMap<FruitsAmountTableSource, FruitAmountDestination>()
                    .ForMember(p => p.Count, p => p.MapFrom(t => t.FruitAmount));
            });

            

            fAutoMapper = new Mapper(mapperConfig);
            fProjector = new DebugProjector(fAutoMapper);

            fFruitRows = new List<FruitsTableSource>()
            {
                {
                    new FruitsTableSource()
                    {
                        FruitId = 1,
                        FruitName = "Apfel",
                    }
                },
                {
                    new FruitsTableSource()
                    {
                        FruitId = 2,
                        FruitName = "Birne",
                    }
                },
                {
                    new FruitsTableSource()
                    {
                        FruitId = 3,
                        FruitName = "Pflaume",
                    }
                },
                {
                    new FruitsTableSource()
                    {
                        FruitId = 4,
                        FruitName = "Orange",
                    }
                }
            }.AsQueryable();

            fFruitAmountRows = new List<FruitsAmountTableSource>()
            {
                {
                    new FruitsAmountTableSource()
                    {
                        FruitId = 1,
                        FruitAmount = 100,
                    }
                },
                {
                    new FruitsAmountTableSource()
                    {
                        FruitId = 2,
                        FruitAmount = 200,
                    }
                },
                {
                    new FruitsAmountTableSource()
                    {
                        FruitId = 3,
                        FruitAmount = 300,
                    }
                },
                {
                    new FruitsAmountTableSource()
                    {
                        FruitId = 4,
                        FruitAmount = 400,
                    }
                }
            }.AsQueryable();
        }

        [Test]
        public void TestProjection()
        {
            var projector = new DebugProjector(fAutoMapper);

            var query = fProjector.ProjectTo<FruitAggregatedDestination>(from fruits in fFruitRows
                         join fruitsAmount in fFruitAmountRows
                         on fruits.FruitId equals fruitsAmount.FruitId
                         select new
                         {
                             Fruit = fruits,
                             Amount = fruitsAmount
                         }).ToList();

            Assert.True(query.Count() == 4);
        }
    }
}
```

**Comment by sdanyliv** [comment] 2018-06-22 10:29
@Fruchuxs, i have checked your sample, rewritten to use with linq2db instead of IQueryable.
With small change, i have commented out  line `cfg.AddProfiles(GetType().Assembly);`.

Unfortunately everything works fine. SQL is ok, projection works as expected.

Linq2db : 2.1.0
Automapper: 6.2.2 - i have trouble with installing 7.0.1 to our test projects

**Comment by Fruchuxs** [comment] 2018-06-22 11:49
Thank you.
Can you please change the Type of the Count variable to nullable int and test it again with your adjusted test case? My test before doesnt cover the problematic case exactly. Sorry, my fault. 
```c#
 class FruitAmountDestination
{
    public int ID { get; set; }
    public int? Count { get; set; }
}
```

Automapper generates the unecessary if-Statement (see tree debug view below) if the destination property is nullable and the source property are not.

```c#
Information = ((dto.Information != null) ? new SomeNamespace.Models.InformationModel()
{
    InformationId = ((dto.Information == null) ? (int?)null : (int?)dto.Information.InformationId),
    Description = dto.Information.Description
} : null),
```

I assume linq2db expects after the first if-codition  ExpressionTypre.Parameter and not another condition.

**Comment by sdanyliv** [comment] 2018-06-22 12:17
@Fruchuxs, it's also works.
Have you tried to update to 2.1.0?

**Comment by Fruchuxs** [comment] 2018-06-22 12:50
I just used master, but I switched to 2.1.0 now.
Same as before: 
In SelectContext.cs =>
levelExpression is 'p.Information', expression is 'p.Information.InformationId', in the switch case root is

```c#
.If ($dto.Information != null) {
    .New es2000.wawi.business.Models.InformationModel(){
        InformationId = .If ($dto.Information == null) {
            (System.Nullable`1[System.Int32])null
        } .Else {
            (System.Nullable`1[System.Int32])($dto.Information).InformationId
        },
        Description = ($dto.Information).Description
    }
} .Else {
    null
}
```
which shall be the same as my fruit example. Here the expression tree debug view:

```
Amount = .If ($dto.Amount != null) {
    .New es2000.wawi.business.tests.Repository.DebugTest+FruitAmountDestination(){
        Count = .If ($dto.Amount == null) {
            (System.Nullable`1[System.Int32])null
        } .Else {
            (System.Nullable`1[System.Int32])($dto.Amount).FruitAmount
        }
    }
} .Else {
    null
}
```

So the if-Statement in line 1016 
```c#
if (root.NodeType != ExpressionType.Parameter)
    return null;
```

is true and he returns "null", so 'var sequence' in line 222 and line 247 is also null, which triggers a NullReferenceException in the attempt to call BuildExpression on 'sequence'.
```c#
return sequence.BuildExpression(expr, 1, enforceServerSide);
```

I have no idea why it works for your but not for me.

**Comment by Fruchuxs** [comment] 2018-06-22 12:52
Btw. I don't tested my fruit example with linq2db because I have no idea how to use this in tests. I just build the fruit example for you for testing purposes.

**Comment by sdanyliv** [comment] 2018-06-22 12:58
Just call 
```cs
db.CreateTempTable(fFruitRows);
db.CreateTempTable(fFruitAmountRows);
```
And you will have 2 filled tables in your database.
Then i've just rewritten your query
```cs
var projector = new DebugProjector(fAutoMapper);

var sourceQuery = from fruits in db.GetTable<FruitsTableSource>()
    join fruitsAmount in db.GetTable<FruitsAmountTableSource>()
        on fruits.FruitId equals fruitsAmount.FruitId
    select new
    {
        Fruit = fruits,
        Amount = fruitsAmount
    };

var result = fProjector.ProjectTo<FruitAggregatedDestination>(sourceQuery).ToList();

```

**Comment by Fruchuxs** [comment] 2018-06-22 13:20
I got the following exception:
```
Result Message:	System.InvalidOperationException : There is no method 'Insert' on type 'LinqToDB.LinqExtensions' that matches the specified arguments
Result StackTrace:	
at System.Linq.EnumerableRewriter.FindMethod(Type type, String name, ReadOnlyCollection`1 args, Type[] typeArgs)
   at System.Linq.EnumerableRewriter.VisitMethodCall(MethodCallExpression m)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.EnumerableExecutor`1.Execute()
   at LinqToDB.LinqExtensions.Insert[TSource,TTarget](IQueryable`1 source, ITable`1 target, Expression`1 setter) in D:\Desktop\linq2db-master\Source\LinqToDB\LinqExtensions.cs:line 1497
   at LinqToDB.TempTable`1.Insert(IQueryable`1 items) in D:\Desktop\linq2db-master\Source\LinqToDB\TempTable.cs:line 202
   at LinqToDB.TempTable`1..ctor(IDataContext db, IQueryable`1 items, String tableName, String databaseName, String schemaName, Action`1 action) in D:\Desktop\linq2db-master\Source\LinqToDB\TempTable.cs:line 121
   at LinqToDB.DataExtensions.CreateTempTable[T](IDataContext db, IQueryable`1 items, String tableName, String databaseName, String schemaName, Action`1 action) in D:\Desktop\linq2db-master\Source\LinqToDB\TempTable.cs:line 398
```

**Comment by sdanyliv** [comment] 2018-06-22 13:30
`EnumerableRewriter` ??

**Comment by sdanyliv** [comment] 2018-06-22 13:32
Pass `fFruitRows.AsEnumerable()` in temporary table creation.

**Comment by Fruchuxs** [comment] 2018-06-22 14:27
Thank you, I can now reproduce the problem: If you call a second select, Linq2Db fails. In my service layers I reselect the requested data to just select specific fields. This works fine, but not for this scenario.

```c#
using System;
using System.Collections.Generic;
using System.Linq;
using AutoMapper;
using LinqToDB;
using NUnit.Framework;

namespace SomeNamespace.Test
{
    [TestFixture]
    class DebugTest
    {
        #region NestedMocks

        class InformationRow
        {
            public int Id { get; set; }
            public string Description { get; set; }
        }

        class Information
        {
            public int? ID { get; set; }
            public string Description { get; set; }
        }

        class ArticleModel
        {
            public Information Info { get; set; }
        }
        #endregion

        private Mapper fAutoMapper;
        private DebugProjector fProjector;
        private IQueryable<InformationRow> fInfoRow;

        [SetUp]
        public void SetUp()
        {
            var mapperConfig = new MapperConfiguration(cfg =>
            {
                cfg.CreateMissingTypeMaps = true;

                cfg.AddProfiles(GetType().Assembly);

                cfg.CreateMap<InformationRow, Information>()
                    .ForMember(p => p.ID, p => p.MapFrom(t => t.Id));
            });

            fAutoMapper = new Mapper(mapperConfig);
            fProjector = new DebugProjector(fAutoMapper);

            fInfoRow = new List<InformationRow>()
            {
                {
                    new InformationRow()
                    {
                        Id = 1,
                        Description = "Hello",
                    }
                },
                {
                    new InformationRow()
                    {
                        Id = 2,
                        Description = "Hello",
                    }
                },
            }.AsQueryable();
        }

        [Test]
        public void TestProjection()
        {
            //var connection = ...

            var projector = new DebugProjector(fAutoMapper);

            var query = fProjector.ProjectTo<ArticleModel>(
                from info in connection.GetTable<InformationRow>()
                select new
                {
                    Info = info,
                })
                .Select(x => new ArticleModel()
                {
                    Info = new Information()
                    {
                        Description = x.Info.Description,
                    }
                }).ToList();
        }

    }
}
```

**Comment by sdanyliv** [comment] 2018-06-22 15:06
@Fruchuxs, will check it on Monday.

**Comment by Fruchuxs** [comment] 2018-06-22 15:08
Thank you! Have a nice weekend.

**Comment by sdanyliv** [comment] 2018-06-25 13:55
@Fruchuxs, we have reproduced issue. Looking for ways to fix that.
Workaround is obvious - you have to correct in method `ProjectTo` expression and remove Null Propagation code until we support this.

**Comment by Fruchuxs** [comment] 2018-06-25 14:21
I can remove the unnecessary second if-statement but I can't remove them all, because they are important for the mapping.
But thanks for your help, I will wait for a new version.

**Comment by sdanyliv** [comment] 2018-06-25 15:25
@Fruchuxs, fix is ready.
Could you please check latest sources in master?

**Comment by Fruchuxs** [comment] 2018-06-26 11:07
As already said, I use AutoMapper to reuse already existing code. My way is to travers over the tree and remove the conditions, this shall work. Problematic is, that I need to decide which Condition part I shall use.

Maybe you should remove your fix, because it doesn't solve all cases, which is problematic.

**Comment by sdanyliv** [comment] 2018-06-26 11:12
@Fruchuxs, fix is ok - it fixes NRE. I'm preparing another fix that may work with null propagation.
But i need confirmation about correctness from @igor-tkachev. 

You have possibility to handle Expression before execution. Just implement `IExpressionPreprocessor` in your `DataConnection` class.

**Comment by Fruchuxs** [comment] 2018-06-26 11:46
Thank you for your information, will check.

**Comment by sdanyliv** [comment] 2018-07-03 04:21
Fixed in #1208.

**Comment by MaceWindu** [comment] 2018-07-21 15:34
we need to add support for reverse conditions, when null is a left side on equality expression before release

**Comment by MaceWindu** [comment] 2019-02-16 15:04
Assigning it to next release, because we still didn't addressed reverse conditions support

**Comment by MaceWindu** [comment] 2019-04-14 10:51
Reverse conditions now work too due to #1665

**Comment by MaceWindu** [comment] 2019-04-14 10:53
Sorry, only 2 of 3 reverse tests work now, so it is still actual

**Closed** 2019-07-01 18:07 UTC
Labels: status: has-tests, status: patch-proposed, type: bug
