### ISSUE TITLE
Missing `LinqToDB.DataType` for text[]

### ISSUE THREAD

**Issue by HypeillingerChillinger** [linq2db/linq2db#4157] opened 2023-06-07 07:51 UTC
Is there any possibility to configure a column of Postgres type `text[]` in Linq2Db? Cannot find the corresponding data type in `LinqToDB.DataType`.

If not how should I insert data into that column using string configuration?

Like this?

```c#
entityBuilder.Property(x => x.Bla)
            .HasColumnName("bla")
            .HasConversionFunc(
                x =>
                {
                    if (x == null)
                    {
                        return null;
                    }

                    var arrayJson = JsonConvert.SerializeObject(x);

                    var arrayPostgresFormat = $"{{{arrayJson[1..^1]}}}";

                    return arrayPostgresFormat;
                },
                x =>
                {
                    if (x == null)
                    {
                        return null;
                    }

                    return JsonConvert.DeserializeObject<List<string>>(x);
                });

```

**Comment by HypeillingerChillinger** [comment] 2023-06-07 08:28
Dead simple, just use a `string[]` as data type that's it.

**Comment by MaceWindu** [comment] 2023-06-07 17:18
What doesn't work? Please provide mappings and code you try to execute.

**Comment by MaceWindu** [comment] 2024-07-27 11:00
duplicate of #341

**Closed by MaceWindu** 2024-07-27 11:00 UTC
Labels: status: expecting answer
