### ISSUE TITLE
GroupBy Limitation

### ISSUE THREAD

**Issue by sdanyliv** [linq2db/linq2db#654] opened 2017-05-04 11:09 UTC
Found during investigation of #649 
Current implementation can not handle queries like this:
```cs
[Test, DataContextSource]
public void TestGrouping2(string context)
{
	using (var db = GetDataContext(context))
	{
		db.InlineParameters = true;
		var q1 = db.Child.GroupBy(c => new
		{
			c.ParentID,
			c.ChildID
		}, (c, g)       => new
		{
			Child      = c,
			Grouped    = g
		}).Select(data => new
		{
			ParentID   = data.Child.ParentID,
			ChildID    = data.Child.ChildID,
			LastChild  = data.Grouped.Max(f => f.ChildID)
		});

		var str = q1.ToString();
	}
```
But this is usual expression tree for VB.NET.
Tested on LinqToSql - it works as expected.

**Comment by MaceWindu** [comment] 2020-04-07 20:13
Closing as duplicate of #649

**Closed by MaceWindu** 2020-04-07 20:13 UTC
Labels: area: linq, area: vb.net, status: needs-tests, type: bug
