### ISSUE TITLE
MS SQL - slow boolean comparison

### ISSUE THREAD

**Issue by LbISS** [linq2db/linq2db#1142] opened 2018-05-10 15:49 UTC
The following code:
```c#
using (var db = DataConnectionFactory().Value)
{
	var res = db.GetTable<Entities.Task>().Select(x => new TaskShortDTO (x.TaskID, x.SubcatID)).Where(w => !w.IsOverdue)
	return res.ToList();
}
```

produces next query to ms sql server:
```sql
select [t].[SubcatID],
       [t].[TaskID]
from    [Tasks] [t]
where NOT ([t].[IsOverdue] = 1)
``` 

That boolean comparison with "NOT" in WHERE clause have perfomance issues in more complicated queries - such comparison could lead to ignoring indexes in sql query plan, etc.
The more clear and optimized way should look like:
```sql	  
select [t].[SubcatID],
       [t].[TaskID]
from    [Tasks] [t]
where ([t].[IsOverdue] = 0)
``` 

Is there any way to do make release version of linq2db produce such SQL?

### Environment details
linq2db version: *1.10.1.0*  
Database Server: *MS SQL Server 2016*  
Operating system: *Windows 10*  
Framework version: *.NET Framework 4.7.1*

**Comment by MaceWindu** [comment] 2018-05-11 10:57
Have you tried explicit comparison with true/false as workaround?

**Comment by LbISS** [comment] 2018-05-11 13:42
> Have you tried explicit comparison with true/false as workaround? I think it will generate expected SQL

I have tried and .Where(w => w.IsOverdue == false) produces the same query

**Comment by sdanyliv** [comment] 2018-05-12 08:52
Current linq2db code produces
```sql
WHERE IsOverdue <> 1
```
Can you check performance degradation?

**Comment by arwyl** [comment] 2018-05-14 09:42
i could not reproduce the bug with only w => !w.IsOverdue predicate
but if I add any other condition (i.e. w => !w.IsOverdue && w.Id > 10), the bug can be reproduced even in version 2.0

**Comment by arwyl** [comment] 2018-05-14 09:54
Code to reproduce:
```
using System;
using System.Linq;
using LinqToDB;
using LinqToDB.Data;
using LinqToDB.DataProvider.SqlServer;
using LinqToDB.Mapping;
using NUnit.Framework;

namespace Tests
{
	[TestFixture]
	public class Linq2DBOtherTests
	{
		[Table(Name = "Users")]
		public class TestUser
		{
			[PrimaryKey, Identity]
			[Column(Name = "Id")]
			public int Id { get; set; }

			[Column(Name = "Name")]
			public string Name { get; set; }

			[Column(Name = "IsActive")]
			public bool IsActive { get; set; }
		}

		[Test]
		public void Linq2DBOtherTests_NotTest()
		{
			var someConnStr = "%SomeConnStringName%";

			DataConnection.TurnTraceSwitchOn();
			DataConnection.OnTrace = x =>
			{
				if (x.TraceInfoStep == TraceInfoStep.AfterExecute)
				{
					Console.WriteLine(x.SqlText);
				}
			};

			var db = new DataConnection(new SqlServerDataProvider("testDataProvider", SqlServerVersion.v2008), someConnStr);

			db.CreateTable<TestUser>();

                         // here everything is ok
			db.GetTable<TestUser>().Where(x => !x.IsActive).ToList();
                         // here is NOT
			db.GetTable<TestUser>().Where(x => !x.IsActive && x.Id > 10).ToList();

			db.DropTable<TestUser>();

			DataConnection.TurnTraceSwitchOn(System.Diagnostics.TraceLevel.Off);
		}
	}
}

```

output:

```
--  testDataProvider SqlServer.2008
CREATE TABLE [Users]
(
	[Id]       Int            NOT NULL IDENTITY,
	[Name]     NVarChar(Max)      NULL,
	[IsActive] Bit            NOT NULL,

	CONSTRAINT [PK_Users] PRIMARY KEY CLUSTERED ([Id])
)

--  testDataProvider SqlServer.2008
SELECT
	[t1].[Id],
	[t1].[Name],
	[t1].[IsActive]
FROM
	[Users] [t1]
WHERE
	1 <> [t1].[IsActive]

--  testDataProvider SqlServer.2008
SELECT
	[t1].[Id],
	[t1].[Name],
	[t1].[IsActive]
FROM
	[Users] [t1]
WHERE
	NOT (1 = [t1].[IsActive]) AND [t1].[Id] > 10

--  testDataProvider SqlServer.2008
IF (OBJECT_ID(N'[Users]', N'U') IS NOT NULL)
	DROP TABLE [Users]
```

**Comment by LbISS** [comment] 2018-05-15 13:14
Thanks!

**Comment by MaceWindu** [comment] 2018-05-17 13:31
fix merged to master and will be available soon on myget (or you can wait an hour for final release :) )

**Closed by MaceWindu** 2018-05-17 13:31 UTC
Labels: bug, patch-proposed, sql
