### ISSUE TITLE
Problem after publishing as NativeAOT

### ISSUE THREAD

**Issue by CodeFanaticX** [linq2db/linq2db#4267] opened 2023-09-09 00:33 UTC
### Describe your issue

If you have a question, first try to check our [documentation](https://linq2db.github.io/), especially [FAQ](https://linq2db.github.io/articles/FAQ.html) and search in [issues](https://github.com/linq2db/linq2db/issues) and [discussions](https://github.com/linq2db/linq2db/discussions) - maybe your question already answered there.

If you still have questions or want to start general discussion, please create new topic in [discussions](https://github.com/linq2db/linq2db/discussions).

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.TypeInitializationException: A type initializer threw an exception. To determine which type, inspect the InnerException's StackTrace property.
 ---> System.NotSupportedException: Specified method is not supported.
   at Internal.Reflection.Execution.ExecutionEnvironmentImplementation.GetInterfaceMap(Type instanceType, Type interfaceType, MethodInfo[]& interfaceMethods, MethodInfo[]& targetMethods) + 0x2df
   at System.Reflection.Runtime.TypeInfos.RuntimeTypeInfo.GetInterfaceMap(Type interfaceType) + 0xd3
   at LinqToDB.Reflection.TypeAccessor`1..cctor() + 0x389
   at System.Runtime.CompilerServices.ClassConstructorRunner.EnsureClassConstructorRun(StaticClassConstructionContext* pContext) + 0xc2
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.ClassConstructorRunner.EnsureClassConstructorRun(StaticClassConstructionContext* pContext) + 0x14a
   at System.Runtime.CompilerServices.ClassConstructorRunner.CheckStaticClassConstructionReturnNonGCStaticBase(StaticClassConstructionContext* context, IntPtr nonGcStaticBase) + 0xd
   at LinqToDB.Reflection.TypeAccessor`1..ctor() + 0x1e
   at KeyVaultTest!<BaseAddress>+0xda59e4
   at System.Reflection.DynamicInvokeInfo.Invoke(Object thisPtr, IntPtr methodToCall, Object[] parameters, BinderBundle binderBundle, Boolean wrapInTargetInvocationException) + 0xb3
   --- End of inner exception stack trace ---
   at System.Reflection.DynamicInvokeInfo.Invoke(Object thisPtr, IntPtr methodToCall, Object[] parameters, BinderBundle binderBundle, Boolean wrapInTargetInvocationException) + 0x1d6
   at Internal.Reflection.Execution.MethodInvokers.InstanceMethodInvoker.CreateInstance(Object[] arguments, BinderBundle binderBundle, Boolean wrapInTargetInvocationException) + 0x44
   at Internal.Reflection.Core.Execution.MethodBaseInvoker.CreateInstance(Object[] arguments, Binder binder, BindingFlags invokeAttr, CultureInfo cultureInfo) + 0x3b
   at System.Reflection.Runtime.MethodInfos.RuntimePlainConstructorInfo`1.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) + 0x55
   at System.ActivatorImplementation.CreateInstance(Type, Boolean) + 0xd3
   at LinqToDB.Reflection.TypeAccessor.GetAccessor(Type type) + 0xb1
   at LinqToDB.Mapping.EntityDescriptor..ctor(MappingSchema mappingSchema, Type type, Action`2 onEntityDescriptorCreated) + 0xc4
   at LinqToDB.Mapping.MappingSchema.<>c.<GetEntityDescriptor>b__98_0(ICacheEntry`2 o, ValueTuple`2 context) + 0x76
   at LinqToDB.Common.Internal.Cache.CacheExtensions.GetOrCreate[TItem, TKey, TContext](IMemoryCache`2 cache, TKey key, TContext context, Func`3 factory) + 0x6b
   at LinqToDB.Mapping.MappingSchema.GetEntityDescriptor(Type type, Action`2 onEntityDescriptorCreated) + 0xcc
   at LinqToDB.Linq.Table`1.InitTable(IDataContext dataContext, Expression expression, EntityDescriptor tableDescriptor) + 0x59
   at LinqToDB.DataExtensions.GetTable[T](IDataContext dataContext) + 0x29
   at DatabaseConnection.<GetDataAsync>d__5.MoveNext() + 0x57
```

### Steps to reproduce

I'm trying to add it to rd.xml but I don't know how to fix it or am I missing something?

```xml
<Assembly Name="linq2db">
            <Type Name="LinqToDB.DataExtensions" Dynamic="Required All" >
            </Type>

            <Type Name="LinqToDB.Data.DataParameter" Dynamic="Required All" />
        </Assembly>
```

```c#
<code with error and mapping classes>
```

### Environment details

`Linq To DB` version: *?* latest

Database (with version): *?* (e.g. SQL Server 2019)

ADO.NET Provider (with version): *?* (e.g. Microsoft.Data.SqlClient 4.1.0)

Operating system: *?*

.NET Version: *?*

**Comment by MaceWindu** [comment] 2023-10-08 17:00
Looks like duplicate of #2680
I suspect Microsoft still didn't implemented this method so we should expand fix surface to .net runtimes...

**Comment by MaceWindu** [comment] 2023-10-08 17:06
I suspect it could be related to https://github.com/dotnet/runtime/issues/89157

**Comment by MaceWindu** [comment] 2023-10-08 17:08
We should look into adding nativeaot build testing.

**Comment by MaceWindu** [comment] 2023-10-08 17:28
We will release temporary workaround which hopefully help with this issue #4291
Note that because GetIterfaceMap method is not available you cannot use interfaces in your mappings (you can, but it could work incorrectly)

**Comment by MaceWindu** [comment] 2023-10-09 11:27
Actually I found that it fails only for interfaces with new features like default members/statics. That's  runtime issue, but it is not critical if user don't use such features in mapped interfaces. I will implement fix, which will ignore such interfaces

**Closed as completed** 2023-10-10 09:40 UTC
Labels: type: bug, status: has-pr, area: AOT
