### ISSUE TITLE
Type Initializer Error Thrown by linq2db InformixDataProvider when run in Web API Application

### ISSUE THREAD

**Issue by juliosm** [linq2db/linq2db#856] opened 2017-09-15 01:23 UTC
I'm testing linq2db for an Informix connection, it is working fine in a Windows Forms application, but when I tried to use the same code to connect from an ASP.NET Web API application it throws an exception when creating InformixTools.CreateDataConnection(..)

Apparently, it's the same issue described here: https://stackoverflow.com/questions/30171835/type-initializer-error-thrown-by-linq2db-informixdataprovider-when-run-in-web-ap

I downloaded source code and I modified the line 128 in InformixDataProvider.cs (as described by quintopereira) and it's working now.

Anyway, I'm attaching the project to reproduce the problem. I don't want to make own fixes in linq2db to avoid problems when updating.

[code.zip](https://github.com/linq2db/linq2db/files/1305020/code.zip)
[lib.zip](https://github.com/linq2db/linq2db/files/1305014/lib.zip)

```
Exception message:
The type initializer for 'IBM.Data.Informix.IfxDecimal' threw an exception

Stack trace:
   en lambda_method(Closure )
   en LinqToDB.DataProvider.Informix.InformixDataProvider.GetNullValue(Type type) en C:\Desarrollo\coilvalidation\code\Linq2DB\Source\DataProvider\Informix\InformixDataProvider.cs:línea 128
   en LinqToDB.DataProvider.Informix.InformixDataProvider.OnConnectionTypeCreated(Type connectionType) en C:\Desarrollo\coilvalidation\code\Linq2DB\Source\DataProvider\Informix\InformixDataProvider.cs:línea 118
   en LinqToDB.DataProvider.DynamicDataProviderBase.GetConnectionType() en C:\Desarrollo\coilvalidation\code\Linq2DB\Source\DataProvider\DynamicDataProviderBase.cs:línea 41
   en LinqToDB.DataProvider.DynamicDataProviderBase.IsCompatibleConnection(IDbConnection connection) en C:\Desarrollo\coilvalidation\code\Linq2DB\Source\DataProvider\DynamicDataProviderBase.cs:línea 51
   en LinqToDB.Data.DataConnection..ctor(IDataProvider dataProvider, IDbConnection connection) en C:\Desarrollo\coilvalidation\code\Linq2DB\Source\Data\DataConnection.cs:línea 188
   en LinqToDB.DataProvider.Informix.InformixTools.CreateDataConnection(IDbConnection connection) en C:\Desarrollo\coilvalidation\code\Linq2DB\Source\DataProvider\Informix\InformixTools.cs:línea 43
```

### Environment details
linq2db version: 1.9.1  
Database Server: Informix 11.50.0000 FC8GE
Database Provider: IBM.Data.Informix
Operating system: Windows 10
Framework version: .NET Framework 4.6.2

Thanks in advance and best regards.

Julio S.

**Comment by sdanyliv** [comment] 2017-10-05 10:23
@juliosm, how do you fix that?
I only see possible solution to catch all exceptions here: https://github.com/linq2db/linq2db/blob/1af71f1711a1bf1cf9ba9c411fc9993ac428443c/Source/DataProvider/Informix/InformixDataProvider.cs#L130

**Comment by sdanyliv** [comment] 2017-10-05 12:59
Reproduced, thanks for sample project. Trying to figure out how to fix correctly.

**Comment by juliosm** [comment] 2017-10-05 16:46
@sdanyliv, I followed the answer described here: http://bit.ly/2y1S5KI

Modifying this line in GetNullValue() in InformixDataProvider.cs (line 128)

```
		static object GetNullValue(Type type)
		{
			try
			{
				var getValue = Expression.Lambda<Func<object>>(Expression.Convert(Expression.Field(null, type, "Null"), typeof(object)));
                                return getValue.Compile();
				//return getValue.Compile()();
			}
			catch (SecurityException)
			{
				return null;
			}
		}

```

I really don't know why, but it's working fine after that.

**Comment by sdanyliv** [comment] 2017-10-05 16:55
It is a bad fix. You just return compiled function, but not ifxDecimal.Null value.
Looks like there is problem with locales, i can not fugure out why it works with console application.
Process Monotor says that in iisexpress version, library can not find appropriate culture and fails in conversion in string to decimal.

You can try just call `new ifxDecimal(-1)` or `ifxDecimal.Null` and it should fail.

BTW, have you tried 64 bit client libraries?

**Comment by sdanyliv** [comment] 2017-10-06 10:33
@juliosm, it takes more time that i can give. Looks like it is Informix issue with locales. 
What we can do:
1. Catch exception in this place and pray that it will not fail during work with decimals
2. Report problem to IBM with simple demo - just call in web application `new ifxDecimal(-1);` 
Debugging shows that function `deccvasc` returns -23101, which is not correct.
[InformixFail.zip](https://github.com/linq2db/linq2db/files/1362395/InformixFail.zip)

**Comment by sdanyliv** [comment] 2018-11-14 19:52
Closing for now, since it is not linq2db related bug. Will reopen if needed.

**Comment by ExzaSolutions** [comment] 2019-03-05 18:57
Hi any news on this?

**Comment by ExzaSolutions** [comment] 2019-03-05 19:04
Hi I fixed my issue,had the same error.
So there is a tool called setnet that installs with informix sdk.
If you open that tool there is a field CLIENT_LOCALE.
I set that to EN_US.UTF8 and now it is working.

**Comment by sdanyliv** [comment] 2019-03-05 19:13
@MaceWindu, looks like solution has been found and needs to be documented.

**Comment by MaceWindu** [comment] 2019-03-06 09:04
@ExzaSolutions thanks for details

**Comment by MaceWindu** [comment] 2019-05-26 12:19
Documentation issue to track https://github.com/linq2db/docs/issues/13

**Closed by MaceWindu** 2019-05-26 12:19 UTC
Labels: area: documentation, provider: informix
