### ISSUE TITLE
After last update of Mysql.Data (and Linq2db) MysqlDateTime conversion issue

### ISSUE THREAD

**Issue by SoftwareMagicIT** [linq2db/linq2db#997] opened 2018-02-06 18:48 UTC
this seem solution (get by official mysql forum):
```cs
public override DateTime GetDateTime(int i) 
 { 
      IMySqlValue val = GetFieldValue(i, true); 
      MySqlDateTime dt; 

      if (val is MySqlDateTime) 
         dt = (MySqlDateTime)val; 
      else 
     { 
        // we need to do this because functions like date_add return string 
        string s = GetString(i); 
        dt = MySqlDateTime.Parse(s); 
     } 

     dt.TimezoneOffset = driver.timeZoneOffset; 
     if (_connection.Settings.ConvertZeroDateTime && !dt.IsValidDateTime) 
           return DateTime.MinValue; 
      else 
           return dt.GetDateTime(); 
      } 

```

Issue is present when:
DateTime is null or zero value in database when populate ITable of linq2db with mysql plugin.
In my code for solve this issue I transform autogenerated datetime in mysqldatetime and when need to parse date I call code above for right conversion. But my solution is unclean. Anyone help me?

**Comment by sdanyliv** [comment] 2018-02-08 04:32
We need clear reproduce steps, because there is no time for experiments.
Please provide us with DataModel, table structure (SQL), Linq statement with problem.
Thanks!

**Comment by MaceWindu** [comment] 2023-01-29 12:26
Closing as no issue details were provided

**Closed by MaceWindu** 2023-01-29 12:26 UTC
Labels: status: expecting answer, provider: mysql, status: needs-tests
