### ISSUE TITLE
Don't escape my Escape Character

### ISSUE THREAD

**Issue by jdistlr** [linq2db/linq2db#776] opened 2017-07-26 17:06 UTC
A manually attached LIKE clause `Sql.Like(f.FIELDNAME, "slot[_]__")` will be translated to `[f].[FIELDNAME] LIKE N'slot[[]_]__'`. What I want is match contents like "slot_01", "slot_02" and so on. I can't match with a `Sql.Like(f.FIELDNAME, "slot%")` or `f.FIELDNAME.StartsWith("slot_")` ...

Is there any option to disable the auto-escaping?

Edit:
Provider is Microsoft SqlServer.

Thanks.

**Comment by sdanyliv** [comment] 2017-07-27 09:50
It is regression after fixing #169.
Looks like it was fixed in wrong place.

**Comment by sdanyliv** [comment] 2017-07-27 10:24
@jdistlr, i propose to do this in that way - Implement your own function:

```c#
[Sql.Expression("{0} LIKE {1}", Precedence = LinqToDB.SqlQuery.Precedence.Comparison, IsPredicate = true, ServerSideOnly = true)]
public static bool MyLike(string matchExpression, string pattern)
{
	throw new NotImplementedException();
}
```

**Comment by jdistlr** [comment] 2017-08-08 20:18
Works perfectly. Thanks a lot!

**Comment by igor-tkachev** [comment] 2017-08-09 02:42
@jdistlr Did you try Sql.Like(string matchExpression, string pattern**, char? escapeCharacter**) method?

**Comment by sdanyliv** [comment] 2017-08-09 05:17
@igor-tkachev, that's why this issue was created - Sql.Like has code that add additional escaping.

**Closed** 2019-12-26 14:21 UTC
Labels: area: linq, area: sql, good first issue, status: needs-tests, type: bug
