### ISSUE TITLE
Parameterization in PostgreSQL queries

### ISSUE THREAD

**Issue by murkykiska** [linq2db/linq2db#4514] opened 2024-05-28 06:02 UTC
I encountered the following problem:
If there is a “where” or “limit” in queries for postgres, the following queries are built:

```c#
int number = 3;       
var users1 = connection.GetTable<User>().Where(u => u.Id > number);
```

```sql
--  PostgreSQL.15 PostgreSQL
DECLARE @number Integer -- Int32
SET     @number = 3

SELECT
        u."Id",
        u."Name",
        u."Email",
        u."CreatedAt"
FROM
        "User" u
WHERE
        u."Id" > :number
```

Such a request is not correct in syntax, i.e. when we try to execute it we get the following error: **Npgsql.PostgresException: "42601: Syntax error (approximate position: "@")**

A workaround was found: if you substitute a specific number/string into a linq query, then they are directly substituted into the “where”. But in real tasks, more complex data types are used (guides/dates, etc.), and this way does not work with them.

```c#
var sql = service.BuildQuery(dc =>
{   
    return
        dc.Table
            .AsSqlServer().WithNoLock()
          .Where(r => r.InstanceID == Guid.Empty)
          .OrderBy(r => r.Number)
          .Take(10);
});
```

```sql
--  PostgreSQL.9.2 PostgreSQL
DECLARE @Empty Uuid -- Guid
SET     @Empty = '00000000-0000-0000-0000-000000000000'::uuid
DECLARE @take Integer -- Int32
SET     @take = 10

SELECT
	"r"."RowID",	
    "r"."Number",
	"r"."InstanceID"	
FROM
	"Table" "r"
WHERE
	"r"."InstanceID" = :Empty
ORDER BY
	"r"."Number"
LIMIT :take
```

Is it possible to get rid of variable declarations?

### Environment details

`Linq To DB` version: 5.4.1

Database (with version): PostgreSQL 15

ADO.NET Provider (with version): Npgsql

Operating system: Windows 11

.NET Version: .net framework 4.8, .net 6.0

**Comment by sdanyliv** [comment] 2024-05-28 07:42
Currently `linq2db` is not usable for building just SQL, what you see is debug information, which executes only in SQL Server. What is the implication of generating SQL queries without execution?

**Comment by MaceWindu** [comment] 2024-07-14 14:36
Duplicate of #4419

**Closed by MaceWindu** 2024-07-14 14:36 UTC
