### ISSUE TITLE
InserOrReplace fails if model was not changed

### ISSUE THREAD

**Issue by tmteam** [linq2db/linq2db#1422] opened 2018-11-21 11:27 UTC
https://github.com/linq2db/linq2db/blob/b182372bc62367a134670212d0ae92df3c2f9b30/Source/LinqToDB/Linq/QueryRunner.InsertOrReplace.cs#L91

It is contrintuitive. My code can not predict if client code have changed model or not. So what is the motivation to throw such an unpredictable exception?

**Comment by MaceWindu** [comment] 2018-11-21 11:31
This exception is not related to to model changes (linq2db has no change tracking at all). This exception means that you try to execute update for model without updateable fields, which doesn't make any sense.

**Comment by sdanyliv** [comment] 2018-12-10 19:02
Closing as designed. Will reopen if needed.

**Closed by sdanyliv** 2018-12-10 19:02 UTC
Labels: question

**Comment by sebastien-f** [comment] 2023-10-16 22:06
In case someone had the same problem, I ran into that error and it was due to a missing PK on the table (and thus was not updatable). Also I was using LinqPad driver.
