### ISSUE TITLE
Ambient transactions and database connections

### ISSUE THREAD

**Issue by yallie** [linq2db/linq2db#2942] opened 2021-04-10 12:59 UTC
For an application using `System.Transcations`, what's the best way to ensure that  
Linq2db uses the same database connection for all commands in the same transaction scope?

In the code like the following, I'd like to ensure that dc1.Connection and dc2.Connection  
will be the same `IDbConnection` instance to avoid escalating to the distributed transaction:

```c#
using (var scope = new TransactionScope()) 
{
     Service1.DoStuff();
     Service2.DoMoreStuff();
     scope.Complete();
}

class Service1
{
     public void DoStuff()
     {
	       using (var dc1 = new DataConnection())
	       {
	          dc1.SetCommand(...).Execute();
	       }
     }
}

class Service2
{
     public void DoMoreStuff()
     {
	       using (var dc2 = new DataConnection())
	       {
	          dc2.SetCommand(...).Execute();
	       }
     }
}
```

As a workaround, I'm currently using a custom data provider that returns the same  
connection for each ambient transaction instead of creating a new one every time.  

The code worked fine in BLToolkit and works just as well in Linq2db but I'm wondering  
if there is a better way supported by Linq2db?

**Comment by MaceWindu** [comment] 2021-04-10 13:06
What kind of issue you have? It should work with `TransactionScope` out-of-box, except case, when connection created before transaction scope (that issue discussed here #2676)

**Comment by yallie** [comment] 2021-04-10 18:57
In theory yes, but here is the code that fails:

```c#
using (var ts = new TransactionScope())
using (var dc = new DataConnection())
using (var tmp = dc.CreateTempTable<MyTempTable>())
{
	// insert a few rows into my temporary table
	tmp.Copy(new[] { new MyTable()... }));

	// make sure that the table exists:
	var q1 = dc.GetTable<MyTempTable>();
	Console.WriteLine($"q1.Count() == {q1.Count()}");

	// this code works inside the same ambient transaction,
    // it should share the same db connection but it doesn't
	using (var dc2 = new DataConnection())
	{
		var q2 = dc2.GetTable<MyTempTable>();
		Console.WriteLine($"q2.Count() == {q2.Count()}"); // fails
	}
}
```

The code prints the following:

```txt
q1.Count() == 3

Unhandled exception: Npgsql.PostgresException: 42P01: relation "MyTempTable" does not exist
   в Npgsql.NpgsqlConnector.<>c__DisplayClass160_0.<<DoReadMessage>g__ReadMessageLong|0>d.MoveNext()
```

**Comment by yallie** [comment] 2021-04-10 19:01
I'm using here temporary table because in PostgreSQL temp tables  
are only visible to the same database connection.

The code that inserts the data to the normal table fails as well.  
The second `DataConnection` doesn't share the same database connection.

Here is the complete source code for the failing demo:

```c#
// D:\MVS2017\MSBuild\15.0\Bin\Roslyn\csc.exe test.cs /r:linq2db.dll /r:System.Threading.Tasks.Extensions.dll /r:System.Runtime.dll /r:System.Runtime.CompilerServices.Unsafe.dll /r:netstandard.dll

using System;
using System.Data;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Transactions;
using LinqToDB;
using LinqToDB.Data;
using LinqToDB.DataProvider.PostgreSQL;

class Program
{
	const string ConnectionString = "Host=localhost;Port=1522;Database=postgres;User Id=test;Password=test;";

	public class MyTempTable
	{
		public string Name { get; set; }
	}

	static void Main()
	{
		SetupDataConnection();

		using (var ts = new TransactionScope())
		using (var dc = new DataConnection())
		using (var tmp = dc.CreateTempTable<MyTempTable>())
		{
			// insert a few test rows
			tmp.Copy(Enumerable.Repeat(new MyTempTable(), 3));

			// make sure that the table exists:
			var q1 = dc.GetTable<MyTempTable>();
			Console.WriteLine($"q1.Count() == {q1.Count()}");

			// pass the temporary table data to another service
			AnotherService_UseMyTempTable();
		}
	}

	static void AnotherService_UseMyTempTable()
	{
		// this code works in ambient transaction
		// and should share the same database connection
		// but it doesn't
		using (var dc2 = new DataConnection())
		{
			var q2 = dc2.GetTable<MyTempTable>();
			Console.WriteLine($"q2.Count() == {q2.Count()}");
		}
	}

	static void SetupDataConnection()
	{
		// use PostgreSQL data provider
		var provider = new PostgreSQLDataProvider();
		Console.WriteLine($"Initializing the data provider: {provider.Name}...");

		DataConnection.DefaultDataProvider = provider.Name;
		DataConnection.DefaultConfiguration = "*";
		DataConnection.AddConfiguration("*", ConnectionString, provider);
	}
}
```

**Comment by jods4** [comment] 2021-04-10 19:01
@yallie are you sure that works in raw ADO.NET?

I don't know the Postgre provider, but in other providers I wouldn't expect that to work.

You create two different connection to your DB, at best with a distributed transaction, I wouldn't expect them to share temporary tables.

**Comment by jods4** [comment] 2021-04-10 19:03
> The second DataConnection doesn't share the same database connection.

Isn't that expected? 
`DataConnection` is basically a statically typed `DbConnection`. 1 `DataConnection` == 1 `DbConnection`.

In raw ADO.NET if you open a second `DbConnection` even under the same `TransactionScope`, you'll get 2 different connections to your DB (possibly enlisted in a distributed transaction).

**Comment by jods4** [comment] 2021-04-10 19:05
What you can do if you want to is pass the first DbConnection and DbTransaction to the ctor of your 2nd `DataConnection`, that would work and you'd have 2 `DataConnection` that share a single connection to the DB.

I'm not sure why you'd do that, though, and you need to be careful because DB connections are thread-safe and often not even re-entrant (i.e. you can't open 2 queries simultaneously).

**Comment by yallie** [comment] 2021-04-10 19:21
>I don't know the Postgre provider, but in other providers I wouldn't expect that to work.

PostgreSQL and Oracle data providers support this mode (PostgreSQL support is enabled  
by default, Oracle support is opt-in, as far as I remember). This code works fine:

```c#
using (var ts = new TransactionScope())
{
	TempTable<MyTempTable> tmp;

	using (var dc = new DataConnection())
	{
		// insert a few test rows
		tmp = dc.CreateTempTable<MyTempTable>();
		tmp.Copy(Enumerable.Repeat(new MyTempTable(), 3));

		// make sure that the table exists:
		var q1 = dc.GetTable<MyTempTable>();
		Console.WriteLine($"q1.Count() == {q1.Count()}");
	}

	// pass the temporary table data to another service
	using (var dc2 = new DataConnection())
	{
		var q2 = dc2.GetTable<MyTempTable>();
		Console.WriteLine($"q2.Count() == {q2.Count()}");
	}

	// drop temporary table
	tmp?.Dispose();
}
```

**Comment by yallie** [comment] 2021-04-10 19:26
>You create two different connection to your DB, at best with a distributed transaction, 
>I wouldn't expect them to share temporary tables.

That's right, I'm creating two `DataConnection` instances.

My question is whether it's possible to set up Linq2db in a way that two `DataConnection`s
share the same underlying database connection when ambient transaction is in progress.

I know I can do this explicitly, like this:

```c#
using (var db = new DataConnection())
{
	using (var db2 = new DataConnection(db1.Connection))
    {
        // db2 shares the same connection
    }
}
```

But I'm asking does Linq2db supports such connection sharing natively when  
an ambient transaction is in progress.

>I'm not sure why you'd do that, though, and you need to be careful because DB
>connections are not thread-safe and often not even re-entrant (i.e. you can't
>open 2 queries simultaneously).

Yes, I'm aware of these limitations, and I don't use DB connections in a multithreaded  
environment. I just want to execute a bunch of services in the same ambient  
transaction without escalating to a distributed transaction and 2-phase commit:

```c#
using (var scope = new TranscationScope())
{
	Service1.DoSomething();
    Service2.DoSomethindElse();
    scope.Complete();
}

class Service1
{
    public void DoSomething()
    {
        using var dc = new DataConnection()...
        Service2.DoSomethingMore()
    }
}

class Service2
{
    public void DoSomethingElse()
    {
        using var dc = new DataConnection()...
    }

    public void DoSomethingMore()
    {
        using var dc = new DataConnection()...
    }
}
```

I'm starting to suspect that nope, Linq2db doesn't support this mode out-of-the box :)

**Comment by jods4** [comment] 2021-04-10 19:30
OK, I don't know Postgre.
Is it possible though that it cleverly re-uses connections? I'm just making guesses here:

The difference between the working and broken code is that the working code uses only one connection at a time, and the broken code nests two connections.

When you have a non-committed transaction, even if you disposed the `DataConnection` (and hence the `DbConnection`), the provider has to keep that connection open until its transaction is committed or rollbacked.
I'm gonna guess that if you re-open a new connection under the same transaction context, Postgre gives you the already opened connection.
If I'm right that explains why your code works: it's the same connection, same session, same opened local transaction.

When you open a nested connection, your provider has to give you a new, different connection (different session, at best distributed transaction with the first one). Unless there's a magic mode to tell Postgre to give everyone the same connection, but then how does that trick happen? Linq2db is just opening `DbConnection` the same way you'd do it in ADO.NET.

Can you make it work in plain ADO.NET?

**Comment by sdanyliv** [comment] 2021-04-10 19:32
1.  Do not use `TransactionScope`, you do not have distributed transactions.
2. Share `DataConnection` between services. It is easily doable using DI and it's scopes, or just pass DataConnection as additional parameter for the service.

**Comment by jods4** [comment] 2021-04-10 19:34
> But I'm asking does Linq2db supports such connection sharing natively when an ambient transaction is in progress.

I don't think so but let's see what the LinqToDb say.

I'm gonna say that would be quite unexpected, at least by default, because that's not how `DbConnection` works.
For all providers that I know of, if you open two `DbConnection` under a transaction scope, you get two _different_ connections.

Since conceptually `DataConnection` == a typed `DbConnection` it would be surprising to have a different behavior.

**Comment by yallie** [comment] 2021-04-10 19:34
>Is it possible though that it cleverly re-uses connections?

@jods4 

Yes, it surely does.

>Can you make it work in plain ADO.NET?

Yes, it works in plain ADO.NET the same way as it works in the sample above.

**Comment by jods4** [comment] 2021-04-10 19:35
> Yes, it works in plain ADO.NET the same way as it works in the sample above.

I meant the part that _doesn't_ work with LinqToDb (nested connections), of course. If it doesn't work in ADO.NET it's unlikely to work in LinqToDb either.

**Comment by sdanyliv** [comment] 2021-04-10 19:36
>. Yes, it works in plain ADO.NET the same way as it works in the sample above.

Probably because of connection pooling. For me it is UB.

**Comment by jods4** [comment] 2021-04-10 19:39
Returning an open transaction to the pool sounds like a huge bug to me. My guess is that this re-use inside a transaction scope is very much intended by the provider.

It has tricky implications for users because depending on how your code runs, after opening two connections you could unpredictably be in a distributed tx or a local tx, which isn't quite the same.

**Comment by yallie** [comment] 2021-04-10 19:40
@sdanyliv 

>1. Do not use TransactionScope, you do not have distributed transactions.
>2. Share DataConnection between services. It is easily doable using DI and it's scopes, or just pass DataConnection as additional parameter for the service.

I'm sorry, I'm porting a large legacy app to Linq2db and I can't change the user-level services.
I have to make sure that their legacy code works the same way it worked.

>For me it is UB.

Sorry, what is UB?

>My guess is that this re-use inside a transaction scope is very much intended by the provider.

Yes, it's intended. I think I've seen in somewhere in the data provider documentation.

**Comment by yallie** [comment] 2021-04-10 19:52
@jods4 

>I meant the part that doesn't work with LinqToDb (nested connections), of course. 
>If it doesn't work in ADO.NET it's unlikely to work in LinqToDb either.

I don't think that would in plain ADO.NET with real nested database connections.

My intent was to set up Linq2db that it doesn't keep this 1:1 relationship between
`DataConnection` and real database connection instances.

If I'm doing something weird, and this mode isn't supported by Linq2db, please  
discard my question. I'll just keep using the workaround I've found for my use case.

**Comment by MaceWindu** [comment] 2021-04-11 08:58
Made some tests and can confirm two things:
- for some reason transaction is not shared when using DataConnection but shared with raw ado.net (`select txid_current()` return different transaction ids for linq2db and same for ado.net). This is bug and will will check if I can find workaround for you
- temp table is connection-scoped, not transaction-sccoped so your example will not work even withing same transaction over different connections. looks like postgresql limitation/behavior

**Comment by MaceWindu** [comment] 2021-04-11 09:01
Basically if your temp table example is something you use in real code - you should stick to your custom solution with connection sharing, but if you want to share transaction, I will try to find out what's wrong here

**Comment by MaceWindu** [comment] 2021-04-11 09:07
Actually I made typo in my test code: transaction ids are differ for ado.net too, so I don't see any difference between linq2db and raw ado.net behavior here.

**Comment by MaceWindu** [comment] 2021-04-11 09:18
Hmm, I don't see what transaction scope actually do in Npgsql except setting `EnlistedTransaction` property on connection - even with raw ado.net it behave like transaction is not shared

**Comment by MaceWindu** [comment] 2021-04-11 09:37
Ok, I think this will summarise it: https://github.com/npgsql/npgsql/issues/1376
What you see is expected behavior with Npgsql: you cannot share anything between different connections withing single transaction scope as it is not real transaction but more like emulation on npgsql side.

**Comment by yallie** [comment] 2021-04-11 11:49
@MaceWindu Thanks a lot for your research!

I know that I can't share anything uncommitted between different database connections.
Many years ago I tested it for both PostgreSQL and Oracle and can confirm it's true.

My question was — can I set up Linq2db in such a way that it reuses real  
database connections and doesn't keep the default 1:1 relationship between  
`DataConnection` and `IDbConnection`. What I had in mind is basically this:

```c#
// Case 1: no ambient transaction
var db1 = new DataConnection();
var db2 = new DataConnection();
Assert.AreNotSame(db1.Connection, db2.Connection);

// Case 2: ambient transcation
using (var scope = new TransactionScope())
{
	var db1 = new DataConnection();
	var db2 = new DataConnection();
	Assert.AreSame(db1.Connection, db2.Connection);
}
```

Now it looks clearly to me that this mode is not supported, so the issue  
can be closed. Thanks everyone for your answers, I very appreciate it!

**Comment by MaceWindu** [comment] 2021-04-11 12:09
Problem is that there is no API to get connection, associated with `Transaction.Current`, so you need to store this information somewhere.

You can achieve it with something like that:
```cs
// custom connection factory
private static ConcurrentDictionary<Guid, NpgsqlConnection> _connections = new ConcurrentDictionary<Guid, NpgsqlConnection>();
        static NpgsqlConnection ConnectionFactory()
        {
            if (Transaction.Current != null)
            {
                var id = Transaction.Current.TransactionInformation.DistributedIdentifier;
                if (!_connections.TryGetValue(id, out var connection))
                {
                    connection = new NpgsqlConnection(cn);
                    _connections[id] = connection;
                    Transaction.Current.TransactionCompleted += (sender, e) => _connections.TryRemove(e.Transaction.TransactionInformation.DistributedIdentifier, out var _);
                }
                return connection;
            }

            return new NpgsqlConnection(cn);
        }

// and use
new DataConnection(PostgreSQLTools.GetDataProvider(PostgreSQLVersion.v95), ConnectionFactory);
```

**Comment by MaceWindu** [comment] 2021-04-11 12:10
Will not say I would be happy to use something like that, but if it will help with migration - why not :)

**Comment by yallie** [comment] 2021-04-11 21:34
>Problem is that there is no API to get connection, associated with 
>Transaction.Current, so you need to store this information somewhere.

Yes, exactly!

>You can achieve it with something like that:

That's right, I'm currently using similar piece of code :)

**Closed** 2021-04-16 10:15 UTC
Labels: resolution: external
