### ISSUE TITLE
ValueConverter not applied to a bool column when used as a predicate

### ISSUE THREAD

**Issue by jods4** [linq2db/linq2db#3830] opened 2022-11-16 15:04 UTC
### Problem description

Assume you have a `ValueConverter` that maps bool in C# to Y/N chars in DB model.
```csharp
class BoolConverterAttribute : ValueConverter 
{
  public BoolConverterAttribute() 
  {
    ValueConverter = new ValueConverter<bool, string>(
      b => b ? "Y" : "N",
      m => m == "Y");
  }
}

class Model 
{
  [BoolConverter]
  public bool  IsCool { get; set; }
}
```

This works when you read or update data, but is ignored is you make a predicate on the bool value, like so:

```csharp
var query = db.Models.Where(x => x.IsCool);
```

linq2db automatically converts boolean expressions into predicate with comparisons to 1/0, so this generates:
```sql
select * 
from Model
where IsCool = 1
```

But the desired outcome would of course be
```sql
select * 
from Model
where IsCool = 'Y'
```

### Suggested resolution
The code the converts boolean expressions into predicate should check if the expression is a model property and if that property has a value converter.
If so, it should do `property = convert(true)` instead of the default ` = 1` conversion.

### Possible complications
Some converters might map values to `null`, especially the false value.
We probably need to be careful that:
-  when the converted value is `null` it's converted into `property is null` instead.
- `!IsCool` must not be converted to `IsCool != 'Y'` but into `IsCool = convert(false)` and `null` is handled property.

**Comment by MaceWindu** [comment] 2022-12-06 14:49
@jods4 I cannot reproduce your issue, looks like something is missing in my test.

**Comment by MaceWindu** [comment] 2022-12-06 15:16
@jods4 I cannot reproduce your issue (but found issue with remote context). Could you check my test to see what's missing from it

**Comment by MaceWindu** [comment] 2024-07-21 15:36
I'm closing it. Reopen if you have proper repro

**Closed by MaceWindu** 2024-07-21 15:36 UTC
Labels: type: bug, status: expecting answer
