### ISSUE TITLE
Error writing sql sentence

### ISSUE THREAD

**Issue by ferbenor** [linq2db/linq2db#621] opened 2017-04-04 16:33 UTC
@AK107 @igor-tkachev on postgresql i write this linq sentence
```cs
using (var db = new emcasrDB())
            {
                var fechaDesde = new DateTime(anio, 1, 1);
                var fechaHasta = new DateTime(anio, 12, 31);
                var listar = (from pg in db.pagosrubros.Where(x=> x.fecha.Between(fechaDesde, fechaHasta))
                         from dp in db.detallepagosrubros.Where(x => x.idpagorubro == pg.id)
                         from dr in db.detallerecaudacions.Where(x => dp.idrecaudacion == x.idrecaudacion && dp.idcabecerarubro == x.idcabecerarubro && dp.numerorubro == x.numero)
                         from ru in db.rubros.Where(x => dr.idrubro == x.id)
                         where dp.anulado == false && Sql.Length(ru.abreviaturareporte ?? "") > 0
                         group dp.valor by new { **pg.fecha.Month** }
                             into gr
                             select new
                             {
                                 Mes = **gr.Key.Month**,
                                 Valor = gr.Sum()
                             }).ToList();
                            
            }
```
and the sql sentence result is this, where the first column not is the same in group by
```sql
SELECT
	**_t4.fecha_**,
	Sum(t1.valor) as c1
FROM
	"public".pagosrubros t4
		INNER JOIN "public".detallepagosrubros t1 ON t1.idpagorubro = t4.id
		INNER JOIN "public".detallerecaudacion t2 ON t1.idrecaudacion = t2.idrecaudacion AND t1.idcabecerarubro = t2.idcabecerarubro AND t1.numerorubro = t2.numero
		INNER JOIN "public".rubros t3 ON t2.idrubro = t3.id
WHERE
	t4.fecha BETWEEN :fechaDesde AND :fechaHasta AND t1.anulado = False AND
	Length(Coalesce(t3.abreviaturareporte, '')) > 0
GROUP BY
	**_Extract(Month from t4.fecha)_**,
	t4.fecha
```

**Comment by sdanyliv** [comment] 2017-04-26 14:57
It is the same bug as in #264

**Comment by sdanyliv** [comment] 2017-04-28 15:31
Duplicate of #264

**Closed by sdanyliv** 2017-04-28 15:31 UTC
Labels: bug, linq
