### ISSUE TITLE
ExpressionMethod Exception on SQLite - No change on Oracle

### ISSUE THREAD

**Issue by KarlssonBernoulli** [linq2db/linq2db#2800] opened 2021-01-27 21:05 UTC
The given ``` ExpressionMethod``` produces an exception on SQLite with null
```  carTable.Where(x => x.FilterBySpecialString(null)).ToList();```
but it works for false and true

On Oracle there is no exception but it produces the same select for null, false and true as if it was not used at all.

```C#
    public class Car
    {
        public long Id {get;set;}
        public string Name {get;set;}
    } 

    public static class CarExtensions
    {
        [ExpressionMethod(nameof(FilterBySpecialStringExpression))]
        public static bool FilterBySpecialString(this Car car, bool? isSpecial = false)
        {
            return !isSpecial.HasValue || isSpecial.Value && car.Name == "Special" || !isSpecial.Value && car.Name != "Special";
        }

        public static Expression<Func<Car, bool?, bool>> FilterBySpecialStringExpression()
        {
            return (x, isSpecial) => !isSpecial.HasValue || isSpecial.Value && x.Name == "Special" || !isSpecial.Value && x.Name != "Special";
        }
    }


    public class Linq2DbPlayground
    {
        public void Start()
        {
            var context = new DataConnection(new SQLiteDataProvider(ProviderName.SQLiteClassic), "Data Source=:memory:");
            context.CreateTable<Car>();

            var fluentMappingBuilder = context.MappingSchema.GetFluentMappingBuilder();

            var carBuilder = fluentMappingBuilder.Entity<Car>();
            carBuilder.Property(x => x.Id).IsPrimaryKey();
            carBuilder.Association(x => x.Group, x => x.GroupId, x => x.Id);

            context.Insert(new Car { Id = 1, Name = "MyCar", IsSet = true });

            var carTable = context.GetTable<Car>();

            var result = carTable.Where(x => x.FilterBySpecialString(null)).ToList();

            var lastQuery = context.LastQuery;
        }
    }
```

**Comment by jogibear9988** [comment] 2021-01-27 21:41
What Exception is created?
What SQL is created?

**Comment by KarlssonBernoulli** [comment] 2021-01-27 21:54
Exception

Ein Ausnahmefehler des Typs "System.Reflection.TargetException" ist in linq2db.dll aufgetreten.: 'Non-static method requires a target.'
   bei System.Reflection.RuntimeMethodInfo.CheckConsistency(Object target)
   bei System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   bei System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   bei System.Reflection.RuntimePropertyInfo.GetValue(Object obj, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
   bei System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   bei LinqToDB.Expressions.InternalExtensions.EvaluateExpression(Expression expr)
   bei LinqToDB.Linq.Builder.ExpressionBuilder.BuildConstant(Expression expr, ColumnDescriptor columnDescriptor)
   bei LinqToDB.Linq.Builder.ExpressionBuilder.ConvertToSql(IBuildContext context, Expression expression, Boolean unwrap, ColumnDescriptor columnDescriptor, Boolean isPureExpression)
   bei LinqToDB.Linq.Builder.ExpressionBuilder.ConvertCompare(IBuildContext context, ExpressionType nodeType, Expression left, Expression right)
   bei LinqToDB.Linq.Builder.ExpressionBuilder.ConvertPredicate(IBuildContext context, Expression expression)
   bei LinqToDB.Linq.Builder.ExpressionBuilder.ConvertPredicate(IBuildContext context, Expression expression)
   bei LinqToDB.Linq.Builder.ExpressionBuilder.BuildSearchCondition(IBuildContext context, Expression expression, List`1 conditions, Boolean isNotExpression)
   bei LinqToDB.Linq.Builder.ExpressionBuilder.BuildSearchCondition(IBuildContext context, Expression expression, List`1 conditions, Boolean isNotExpression)
   bei LinqToDB.Linq.Builder.ExpressionBuilder.BuildSearchCondition(IBuildContext context, Expression expression, List`1 conditions, Boolean isNotExpression)
   bei LinqToDB.Linq.Builder.ExpressionBuilder.BuildSearchCondition(IBuildContext context, Expression expression, List`1 conditions, Boolean isNotExpression)
   bei LinqToDB.Linq.Builder.ExpressionBuilder.BuildWhere(IBuildContext parent, IBuildContext sequence, LambdaExpression condition, Boolean checkForSubQuery, Boolean enforceHaving)
   bei LinqToDB.Linq.Builder.WhereBuilder.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo)
   bei LinqToDB.Linq.Builder.MethodCallBuilder.BuildSequence(ExpressionBuilder builder, BuildInfo buildInfo)
   bei LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo)
   bei LinqToDB.Linq.Builder.ExpressionBuilder.Build[T]()
   bei LinqToDB.Linq.Query`1.CreateQuery(IDataContext dataContext, Expression expr)
   bei LinqToDB.Linq.Query`1.GetQuery(IDataContext dataContext, Expression& expr)
   bei LinqToDB.Linq.ExpressionQuery`1.GetQuery(Expression& expression, Boolean cache)
   bei LinqToDB.Linq.ExpressionQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   bei System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   bei System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   bei linq2dbsample.Linq2DbPlayground.Start() in /home/heidewitzka/WorkingDirectories/linq2db-samples/linq2dbsample/Linq2Db/Linq2DbPlayground.cs: Zeile76
   bei linq2dbsample.Program.Main(String[] args) in /home/heidewitzka/WorkingDirectories/linq2db-samples/linq2dbsample/Program.cs: Zeile21

**Comment by KarlssonBernoulli** [comment] 2021-01-27 21:56
Sql for true

SELECT
	[x].[Id],
	[x].[Name],
	[x].[DateTime],
	[x].[IsSet],
	[x].[GroupId]
FROM
	[Car] [x]
WHERE
	[x].[Name] = 'Special'

**Comment by MaceWindu** [comment] 2021-02-02 15:33
You didn't specified version of linq2db. We already had similar issue recently #2688.

**Comment by MaceWindu** [comment] 2021-02-02 15:36
I'm going to close it as regression test show no issue with this query, so I will assume 3.1.x version were used

**Comment by sdanyliv** [comment] 2021-02-02 15:38
I need to recheck

**Comment by sdanyliv** [comment] 2021-02-03 10:23
@KarlssonBernoulli, I cannot reproduce. We need more detailed reproducing steps.

**Comment by MaceWindu** [comment] 2021-02-03 10:25
@KarlssonBernoulli , [test](https://github.com/linq2db/linq2db/pull/2814) and [generated sql](https://github.com/linq2db/linq2db.baselines/pull/522/files)

**Comment by KarlssonBernoulli** [comment] 2021-02-03 21:03
My main issue is on 
Oracle Version 12.2
Nuget linq2db Version 3.2.3
Nuget linq2db.Oracle.Managed 3.2.3

For reproduction use 
1. null
2. true and
3. false

The SQL look always the same as if I did not use the ```Where```

```SQL
SELECT
    x."Id",
    x."Name"
FROM
   "Car" x
```

The second issue with the exception was on Linq2Db Version 3.1.3. I should have upgraded to the newest version, sorry for the inconvenience.

**Comment by sdanyliv** [comment] 2021-02-03 21:22
Looks like a caching issue. But I have also tested that. Will check order of the tests.

**Comment by KarlssonBernoulli** [comment] 2021-02-03 21:30
https://github.com/linq2db/linq2db/pull/2814/commits/36a2016af8b1bbb0c9c27b6551acaa5f70d6672f
Line 1070 - There is a ```this``` missing or doesn't that matter in Linq2Db?

**Comment by sdanyliv** [comment] 2021-02-04 15:18
@KarlssonBernoulli, 
I still cannot reproduce. Everything counts, how you write query. It is local variable or parameter or constant.

**Comment by sdanyliv** [comment] 2021-02-04 17:50
@KarlssonBernoulli, if it is a bug, we should fix that ASAP. So reproducing project will be appreciated.

**Comment by KarlssonBernoulli** [comment] 2021-02-04 20:33
So, I have created an example with all you need. 

Reproduction:
I copied the following code into a new project with Version 3.2.3

The issue occurs in the second example see below. You only need to enter the connection string and debug.
The first three queries work, the last three queries are completely equal strings.

```C#
    public class Car
    {
        public long Id {get;set;}
        public string Name {get;set;}
    } 

    public static class CarExtensions
    {
        [ExpressionMethod(nameof(FilterBySpecialStringExpression))]
        public static bool FilterBySpecialString(this Car car, bool? isSpecial = false)
        {
            return !isSpecial.HasValue || isSpecial.Value && car.Name == "Special" || !isSpecial.Value && car.Name != "Special";
        }

        public static Expression<Func<Car, bool?, bool>> FilterBySpecialStringExpression()
        {
            return (x, isSpecial) => !isSpecial.HasValue || isSpecial.Value && x.Name == "Special" || !isSpecial.Value && x.Name != "Special";
        }
    }

    public class Linq2DbPlayground
    {
        public void Start()
        {
            var connectionString = "";
            var context = new DataConnection(new OracleDataProvider(ProviderName.OracleManaged), connectionString);
            try
            {
                context.CreateTable<Car>();
            }
            catch{}
            
            var fluentMappingBuilder = context.MappingSchema.GetFluentMappingBuilder();
            var carBuilder = fluentMappingBuilder.Entity<Car>();
            carBuilder.Property(x => x.Id).IsPrimaryKey();
            var carTable = context.GetTable<Car>();

            // Start: This works perfectly
            var values = new bool?[]{ null, false, true };
            var sqlResults = new List<string>();
            foreach(var value in values)
            {
                var query = carTable.Where(x => x.FilterBySpecialString(value)).ToList();
                sqlResults.Add(context.LastQuery);
            }
            // End of first example
            
            // Start: This does not work meaning that there is not difference in the resulting SQL statement
            sqlResults.Clear();
            
            carTable.Where(x => x.FilterBySpecialString(null)).ToList();
            sqlResults.Add(context.LastQuery);
            
            carTable.Where(x => x.FilterBySpecialString(true)).ToList();
            sqlResults.Add(context.LastQuery);
            
            carTable.Where(x => x.FilterBySpecialString(false)).ToList();
            sqlResults.Add(context.LastQuery);
            
            // End of failing code
        }
    }

```

**Comment by sdanyliv** [comment] 2021-02-04 20:36
Well, third attempt tomorrow, thanks for the full sample!

**Comment by KarlssonBernoulli** [comment] 2021-02-04 20:45
Your pointed out that there could be a difference if it was a variable or not. So I rechecked it. And indeed if it is a variable it works if not it does not.
Thanks for having a look at that issue.

**Comment by jogibear9988** [comment] 2021-02-15 19:22
@sdanyliv why the test only for firebird? as I understood it was broken on oracle?

**Comment by sdanyliv** [comment] 2021-02-15 19:24
@jogibear9988, not for Firebird, but except Firebird.

**Closed** 2021-02-21 11:57 UTC
Labels: status: has-pr
