### ISSUE TITLE
Thread Safety in Mapping 

### ISSUE THREAD

**Issue by jogibear9988** [linq2db/linq2db#548] opened 2017-02-06 18:38 UTC
Do we still have a problem in Thread Safety?

I've had the following Stacktraces:

      06.02.2017 19:18:12|Fatal|ExecutionContext.RunInternal|System.Reflection.TargetInvocationException: Ein Aufrufziel hat einen Ausnahmefehler verursacht. ---> System.Reflection.TargetInvocationException: Ein Aufrufziel hat einen Ausnahmefehler verursacht. ---> System.ArgumentNullException: Der Wert darf nicht NULL sein.
                          Parametername: source
                             bei System.Linq.Enumerable.SelectMany[TSource,TCollection,TResult](IEnumerable`1 source, Func`2 collectionSelector, Func`3 resultSelector)
                             bei LinqToDB.Mapping.MappingSchema.GetAttributes[T](MemberInfo memberInfo, Boolean inherit) in c:\projects\linq2db\Source\Mapping\MappingSchema.cs:Zeile 598.
                             bei LinqToDB.Mapping.MappingSchema.GetAttributes[T](MemberInfo memberInfo, Func`2 configGetter, Boolean inherit) in c:\projects\linq2db\Source\Mapping\MappingSchema.cs:Zeile 637.
                             bei LinqToDB.Mapping.MappingSchema.GetAttribute[T](MemberInfo memberInfo, Func`2 configGetter, Boolean inherit) in c:\projects\linq2db\Source\Mapping\MappingSchema.cs:Zeile 659.
                             bei LinqToDB.Mapping.EntityMappingBuilder`1.<>c__DisplayClass37`1.<SetAttribute>b__36(Expression e, Boolean m) in c:\projects\linq2db\Source\Mapping\EntityMappingBuilder.cs:Zeile 281.
                             bei LinqToDB.Mapping.EntityMappingBuilder`1.SetAttribute[TA](Expression`1 func, Boolean processNewExpression, Func`2 getNew, Action`2 modifyExisting, Func`2 configGetter, Func`2 overrideAttribute) in c:\projects\linq2db\Source\Mapping\EntityMappingBuilder.cs:Zeile 314.
                             bei LinqToDB.Mapping.PropertyMappingBuilder`1.SetColumn(Action`1 setColumn) in c:\projects\linq2db\Source\Mapping\PropertyMappingBuilder.cs:Zeile 82.
                             bei MCC.Common.DL.Mappings.ImageDTOMapping..ctor() in E:\csharp\git\mcc5\MCC.V1.0\4DL\MCC.Common.DL\Mappings\ImageDTOMapping.cs:Zeile 14.

and

     06.02.2017 19:22:17|Fatal|ExecutionContext.RunInternal|System.Reflection.TargetInvocationException: Ein Aufrufziel hat einen Ausnahmefehler verursacht. ---> System.Reflection.TargetInvocationException: Ein Aufrufziel hat einen Ausnahmefehler verursacht. ---> System.ArgumentNullException: Der Wert darf nicht NULL sein.
                          Parametername: source
                             bei System.Linq.Enumerable.SelectMany[TSource,TCollection,TResult](IEnumerable`1 source, Func`2 collectionSelector, Func`3 resultSelector)
                             bei LinqToDB.Mapping.MappingSchema.GetAttributes[T](MemberInfo memberInfo, Boolean inherit) in c:\projects\linq2db\Source\Mapping\MappingSchema.cs:Zeile 598.
                             bei LinqToDB.Mapping.MappingSchema.GetAttributes[T](MemberInfo memberInfo, Func`2 configGetter, Boolean inherit) in c:\projects\linq2db\Source\Mapping\MappingSchema.cs:Zeile 637.
                             bei LinqToDB.Mapping.MappingSchema.GetAttribute[T](MemberInfo memberInfo, Func`2 configGetter, Boolean inherit) in c:\projects\linq2db\Source\Mapping\MappingSchema.cs:Zeile 659.
                             bei LinqToDB.Mapping.EntityMappingBuilder`1.<>c__DisplayClass37`1.<SetAttribute>b__36(Expression e, Boolean m) in c:\projects\linq2db\Source\Mapping\EntityMappingBuilder.cs:Zeile 281.
                             bei LinqToDB.Mapping.EntityMappingBuilder`1.SetAttribute[TA](Expression`1 func, Boolean processNewExpression, Func`2 getNew, Action`2 modifyExisting, Func`2 configGetter, Func`2 overrideAttribute) in c:\projects\linq2db\Source\Mapping\EntityMappingBuilder.cs:Zeile 314.
                             bei LinqToDB.Mapping.PropertyMappingBuilder`1.SetColumn(Action`1 setColumn) in c:\projects\linq2db\Source\Mapping\PropertyMappingBuilder.cs:Zeile 82.
                             bei MCC.Common.DL.Mappings.ConfigurationDTOMapping..ctor() in E:\csharp\git\mcc5\MCC.V1.0\4DL\MCC.Common.DL\Mappings\ConfigurationDTOMapping.cs:Zeile 13.

**Comment by ili** [comment] 2017-02-07 06:31
Looks like yes, with using `FluentMappingBuilder`... Or changing `MatedataReaders` from several threads & reading data from others...

**Comment by jogibear9988** [comment] 2017-02-07 06:36
any idea where?

**Comment by ili** [comment] 2017-02-07 06:43
Yes, i'v found one point, now will try to reproduce

**Comment by ili** [comment] 2017-02-08 09:54
This one should be fixed now

**Closed by ili** 2017-02-08 09:54 UTC
Labels: bug

**Comment by jogibear9988** [comment] 2017-02-08 14:46
Thanks
