### ISSUE TITLE
CTE column names not corresponds to aliases when GenerateFinalAliases is true

### ISSUE THREAD

**Issue by filippobottega** [linq2db/linq2db#2029] opened 2020-01-09 16:27 UTC
If I set Configuration.Sql.GenerateFinalAliases = true the CTE's column names are not corresponding with the final aliases of the internal SELECT.

Example:

...
WITH AllowedNcCode (**Handle**, **NcCodeColumn**, **Description**)
AS
(
	SELECT DISTINCT
		ncCode.HANDLE as **NcCodeBo**,
		ncCode.NC_CODE as **NcCode**,
		ncCode.DESCRIPTION as **NcCodeDescription**
	FROM
...

### Environment details
linq2db version: 3.0.0-preview.1
Database Server: Oracle
Database Provider: Oracle.ManagedDataAccess.Core (3.0.0-preview.1)
Operating system: Windows 10
.NET Framework:.NET Core 3.1

**Comment by sdanyliv** [comment] 2020-01-09 18:51
@filippobottega, ca you post small reproducible query? I've tried several variants without success.

**Comment by filippobottega** [comment] 2020-01-10 09:34
@sdanyliv , I have created a sample project that you can use to find the bug.
Please read the README.txt file contained in the project to setup a new Oracle Database and to update the connection string to run the sample.

[LinqToDb.Sample1.zip](https://github.com/linq2db/linq2db/files/4044882/LinqToDb.Sample1.zip)

**Comment by filippobottega** [comment] 2020-01-10 09:53
Solved! I have found that the class used in the Select inside the CTE was defined **internal** and linq2db was not able to use it to name the CTE parameters.
Changing the modifier from internal to **public** solved the issue.
I know, this is mine error, but please update the documentation to alert the user to use only public classes.

Thank you!

**Comment by sdanyliv** [comment] 2020-01-10 09:55
Reopening, i have to examine what happened. And it is strange that internal classes are not processed.

**Comment by filippobottega** [comment] 2020-01-10 10:17
@sdanyliv , if you have time to review the code, please note that the alias generated in the joins are not really correct.
For example I get: 

`... INNER JOIN WIPUSER.CUSTOM_FIELDS customFields_1 ON ...`

If GenerateFinalAliases is true, the table name CUSTOM_FIELDS is named in C# as CustomFields.
Now linq2sql if I specify customFields in:

`... join customFields in db.CustomFields on ...`

changes the alias name from customFields to customFields_1 but will be better if it was customFields because customFields name is not colliding with CUSTOM_FIELDS.

**Comment by filippobottega** [comment] 2020-01-10 10:34
@sdanyliv , and last but not least ;) the order of CTE parameters is not so well defined.
For example if I write:

```
select new ProductionFailedNcDataOutput
{
    NcCode = ncCodeItem,
    Operation = operationItem.OperationColumn,
    OperationBo= ncData.OperationBo,
    CurrentOperationBo= "OperationBO:" + ncData.Site + "," + operationItem.OperationColumn + ",#",
    SfcBo = sfc.Handle,
    Sfc = sfc.SfcColumn,
    ShopOrderBo= sfc.ShopOrderBo,
    ItemBo=  sfc.ItemBo,
    NcDataBo = ncData.Handle,
    ResourceBo= ncData.ResourceBo,
    WorkCenterBo=   ncData.WorkCenterBo,
    PartitionDate=  ncData.PartitionDate,
    Site= ncData.Site
}
```

where class ProductionFailedNcDataOutput is:

```
public class ProductionFailedNcDataOutput : ISfcCurrentOperation
{
    public AllowedNcCodeOutput NcCode { get; set; }
    public string Operation { get; set; }
    public string OperationBo { get; set; }
    public string CurrentOperationBo { get; set; }
    public string SfcBo { get; set; }
    public string Sfc { get; set; }
    public string ShopOrderBo { get; set; }
    public string ItemBo { get; set; }
    public string NcDataBo { get; set; }
    public string ResourceBo { get; set; }
    public string WorkCenterBo { get; set; }
    public DateTime PartitionDate { get; set; }
    public string Site { get; set; }
}
```

and ISfcCurrentOperation is:

```
public interface ISfcCurrentOperation
{
    string SfcBo { get; set; }
    string CurrentOperationBo { get; set; }

}
```

and AllowedNcCodeOutput  is:

```
public class AllowedNcCodeOutput
{
    public string NcCodeBo { get; set; }
    public string NcCode { get; set; }
    public string NcCodeDescription { get; set; }
}
```

The CTE output parameters are defined as:

```
(
	SfcBo, 
	CurrentOperationBo, 
	NcCodeBo, 
	NcCode, 
	NcCodeDescription, 
	OperationColumn, 
	OperationBo, 
	Site, 
	SfcColumn, 
	ShopOrderBo, 
	ItemBo, 
	Handle, 
	ResourceBo, 
	WorkCenterBo, 
	PartitionDate
)
```

CTE Parameters order is not the same as the properties defined in ProductionFailedNcDataOutput class.

It would be better for readability if the order will be maintained.

**Comment by filippobottega** [comment] 2020-01-10 10:47
@sdanyliv , I have found other cases where aliases used in the Select are not used in the CTE parameters. I think that the problem is not only in the internal modifier. I suppose that some times the alias is not used in favor of the name of the property of the object used in the Select statement.

**Comment by sdanyliv** [comment] 2020-01-10 10:49
Will check. I know why order is different - it is how we optimize projection. Possible at finalization stage we can sort CTE columns based on their property order.

**Comment by sdanyliv** [comment] 2020-01-10 11:31
So main problem that names of CTE columns do not match class that represents columns?
If yes, it is a possible situation. We will try to handle this this later.
Imagine complex query in CTE:
```cs
var query = 
   from a in db.GetTable<A>()
   from b in db.GetTable<B>().InnerJoin(b => b.ParentId == a.Id)
   select new Cte 
   {
       A = a,
       B = b
   };

var cte = query.AsCte();

var result = 
   from c in cte
   select 
   {
       c.A.SomeField
   }
```
So generate field names here can be difficult task.

**Comment by filippobottega** [comment] 2020-01-10 11:41
The problem is that now I have to write:

``` CSHARP
var query = 
   from a in db.GetTable<A>()
   from b in db.GetTable<B>().InnerJoin(b => b.ParentId == a.Id)
   select new Cte 
   {
       A = a.SomeField,
       B = b
   };

var cte = query.AsCte();

var result = 
   from c in cte
   select 
   {
       c.SomeField
   }
```

but I would like:

``` CSHARP
var query = 
   from a in db.GetTable<A>()
   from b in db.GetTable<B>().InnerJoin(b => b.ParentId == a.Id)
   select new Cte 
   {
       A = a.SomeField,
       B = b
   };

var cte = query.AsCte();

var result = 
   from c in cte
   select 
   {
       c.A
   }
```

The problem is that A is not used but is used SomeField. I think this is a bug.

**Comment by sdanyliv** [comment] 2020-01-10 11:44
It should work. Your first query is wrong because class `Cte` do not have property `SomeField`  but `A`

**Comment by filippobottega** [comment] 2020-01-10 11:53
> It should work. Your first query is wrong because class `Cte` do not have property `SomeField` but `A`

Sorry, I have edited my last message because was wrong. Please read it again.

**Comment by sdanyliv** [comment] 2020-01-10 12:04
So it's why i have shown that we support more complex scenarios. LINQ is difficult to parse and there are more possibilities to express the query. Your case is obvious but we have to keep in mind that there can be VERY complex queries inside and we have to handle that.

Anyway i have checked current code. It is not obvious task to correct names for CTE. If it is not critical i vote to postpone fix.

**Comment by filippobottega** [comment] 2020-01-10 13:31
Thank you for your answer,
I agree with you that the task to correct names could be really difficult.
My concern is that I'm porting existing queries from SQL to linq2db and I need to compare the original ones with the emitted from linq2db. Corrected CTE names let us to understand if we are doing a good job quickly. 
Please let the issue opened to understand if it is relevant to others.

**Comment by sdanyliv** [comment] 2020-01-10 13:42
I see your point. But there are other urgent tasks to do, so better ping me later.
BTW, maybe this tool can speedup your work https://www.sqltolinq.com/

**Comment by filippobottega** [comment] 2020-01-10 15:26
Hi @sdanyliv,
  I have found another issue: the naming algorithm doesn't consider the CTE context isolation. It seems that if an alias is used inside a CTE, the same alias is not allowed in another CTE. I suppose that for simplicity the algorithm doesn't consider the CTE scopes.

  But if you have a lot of CTE it's common to reuse the same aliases.

  I have created an image to explain this and other problems found in naming algorithm that you can use when you'll have time to refactor the naming algorithm:

![Linq2db SQL output](https://user-images.githubusercontent.com/2587684/72163736-a7cc1d80-33c4-11ea-9eac-c3f89580ff9f.png)

**Comment by sdanyliv** [comment] 2020-01-10 15:38
For Table Sources we always generate unique aliases. It simplify debugging and understanding queries.

**Comment by sdanyliv** [comment] 2020-01-10 15:49
This summer we significantly improved generating aliases and names, don't be so critic :))
In comparison to SQL generated by EF Core - you see really brilliant query ;)

Nothing perfect and needs improvements. So we will fix that later.

**Comment by filippobottega** [comment] 2020-01-10 16:04
@sdanyliv , sorry if it seems that I am so critic... 
I REALLY LOVE LINQ2DB!!! :DDD
It's an amazing way to write SQL because with linq2db we have the possibility to automate complex SQL building processes.
If I open an issue is because I like to help, not to critic.

Thank you for your time and support.

**Comment by sdanyliv** [comment] 2020-01-10 17:11
> It's an amazing way to write SQL because with linq2db we have the possibility to automate complex SQL building processes.

True, linq2db created for developers who know SQL and know how hard is concatenating raw strings. We bring typesafe query decomposition to SQL world and i hope it works well )

> If I open an issue is because I like to help, not to critic.

NP, just joking. You are first after me who analyze generated query for such details.

**Comment by sdanyliv** [comment] 2020-03-11 14:34
@filippobottega, it should be fixed in 2.9.7. Can you confirm that?

**Comment by filippobottega** [comment] 2020-03-12 08:57
@sdanyliv I'm using .Net Core 3.1 and linq2db version: 3.0.0-preview.1. Do you have an upgrade of version: 3.0.0-preview.1 ?

**Comment by MaceWindu** [comment] 2020-03-12 08:58
You can try latest version from azure artifacts. It contains changes from 2.9.7 and pass our regression testing.

**Comment by MaceWindu** [comment] 2020-03-12 09:01
https://dev.azure.com/linq2db/linq2db/_packaging?_a=package&feed=linq2db%40Local&package=linq2db&protocolType=NuGet&version=3.0.0-rc.1695

**Comment by sdanyliv** [comment] 2020-03-12 09:03
If you do not use 3.0 features, better switch to 2.9.7
3.0-preview1 is outdated for a several months until preview2.

**Comment by filippobottega** [comment] 2020-03-12 09:54
@sdanyliv  I have the new SQL of an example just a little different. It works but I have no time now to understand if the new naming algorithm is compliant with my needs. Anyway I think that the new naming convention is better than before.

The new SQL is:
![image](https://user-images.githubusercontent.com/2587684/76509054-a44e2480-644f-11ea-945a-627d250f37cb.png)

**Comment by filippobottega** [comment] 2020-03-16 11:35
Hi @sdanyliv ,
  I'm testing linq2db.Oracle.Managed version 3.0.0-rc.1695.

  I have a regression error:

```
System.InvalidCastException
  HResult=0x80004002
  Messaggio=Unable to cast object of type 'System.Linq.Expressions.InvocationExpression2' to type 'System.Linq.Expressions.BinaryExpression'.
  Origine=<Non è possibile valutare l'origine dell'eccezione>
  Analisi dello stack:
<Non è possibile valutare l'analisi dello stack dell'eccezione>
```

Reverting to 3.0.0-rc.1491 solved the issue.
For the moment I don't have any code to send you because the error appear after a complex cte building process and I need to isolate the offending code.
The error appears when I call ToString() of a CTE.
I'm investigating if the following code is allowed in the last release:

``` C#
internal IQueryable<FindProductionFailedNcDataOutput> Cte<TIn>(IQueryable<TIn> ncCode, Expression<Func<NcData, Sfc, bool>> predicate) where TIn : INcCodeKey
...
where predicate.Compile()(ncData, sfc)
...
```

**Comment by MaceWindu** [comment] 2020-06-14 12:03
@filippobottega  is it still an issue?

**Comment by MaceWindu** [comment] 2020-06-14 12:25
Looks like it is fixed in preview2 (updated test project to preview2 and got proper aliases).
Will create regression test and close it

**Closed** 2020-06-14 14:30 UTC
Labels: area: sql, type: bug

**Comment by filippobottega** [comment] 2020-06-15 08:03
@MaceWindu The issue is not present anymore, I'm using 3.0.0-rc.2202 version now without errors.
Thank you!
