### ISSUE TITLE
INSERT INTO ... ON CONFLICT DO UPDATE clause

### ISSUE THREAD

**Issue by AndrePScope** [linq2db/linq2db#2241] opened 2020-05-27 11:13 UTC
Hi!

Does linq2db support `INSERT INTO ... ON CONFLICT DO UPDATE` clause for Postgresql?
This is some analog of SQL `MERGE ` operation (without deletion).

As MERGE does not support by Postgre, could this clause use for db.Merge() in ling2db?

Thank you.

**Comment by sdanyliv** [comment] 2020-05-27 11:22
Only for one record
```cs
db.InsertOrReplace(obj)
db.Table.InsertOrUpdate(...)
```

**Comment by AndrePScope** [comment] 2020-05-27 12:20
Ok, Thank you!

**Comment by AndrePScope** [comment] 2020-05-27 15:43
Hi @sdanyliv!

I decide to reopen this issue and ask about Linq2Db opinion about implementation MERGE for multiple rows in Postgre (like you do in BulkCopy):

**This is the suggestion of SQL syntax.** 

_The table_ 
```sql
create table test
(
    id   bigint not null   constraint pk_test  primary key,
    name varchar(100),
    sequence_number bigint
);
```

_MERGE syntax_
```sql
INSERT INTO test (id, name, sequence_number)
    VALUES
           (1,'Name 2', 2),
           (2,'Name 1', 3),
           (3,'Name 3', 1)
ON CONFLICT (id) DO UPDATE
SET
    name =
        case when EXCLUDED.id = 1 then 'Name 2'
             when EXCLUDED.id = 2 then 'Name 1'
             when EXCLUDED.id = 3 then 'Name 3'
             else EXCLUDED.name end,
    sequence_number =
        case when EXCLUDED.id = 1 then 2
             when EXCLUDED.id = 2 then 3
             when EXCLUDED.id = 3 then 1
             else EXCLUDED.sequence_number end
```

I understand this suggestion has a disadvantage: the text of SQL can have a very big text, because of the multiplication of the number of columns to the number of merged rows.
But this is the implementation of merge...
What do you think?

**Comment by MaceWindu** [comment] 2020-06-14 14:06
Gonna close it as duplicate of #1480

**Closed by MaceWindu** 2020-06-14 14:06 UTC
Labels: epic: merge, type: feature
