### ISSUE TITLE
Failure on testing process

### ISSUE THREAD

**Issue by alfcas** [linq2db/linq2db#145] opened 2014-11-11 10:20 UTC
Hi, first of all, thanks for this great project .. 
second :-( 
I compiled everything with sharpdevelop against net 4.5 successfully, but once I did the test I had too many failure notices (sqlce, access, sqlite)

**Comment by igor-tkachev** [comment] 2015-01-06 02:39
How can I reproduce the problem?

**Comment by VoiceOfWisdom** [comment] 2015-03-05 03:41
@igor-tkachev, I think this issue could be resolved with the creation of a `contributing.md` file that details getting up and running with basic testing. New contributors currently have to look around quite a bit for the different config settings that need to be changed to get the tests running in their environment.

**Comment by sdanyliv** [comment] 2017-02-27 19:54
@xavierzwirtz, it is still an issue?

**Comment by xavierzwirtz** [comment] 2017-02-27 23:03
To be honest I have not used this project since I made that comment. If I remember correctly my issue stemmed from not having an easy way to just start running tests. I would suggest correcting that if its still an issue, or making a guide on how to get tests running.

**Comment by ili** [comment] 2017-02-28 04:08
Yes, guide is needed

**Comment by ili** [comment] 2017-02-28 04:11
About culture issues, most of them are fixed for now. There are problems with informix, I do keep them in mind

**Comment by MaceWindu** [comment] 2017-08-16 20:30
Informix culture issues will be fixed with changes from #686. Only issues, caused by #730 will remain.

**Closed** 2017-08-17 07:17 UTC
Labels: documentation
