### ISSUE TITLE
Wrong T4 generation for ColumnAttribute when table name is "DataType" 

### ISSUE THREAD

**Issue by Drapondur** [linq2db/linq2db#2168] opened 2020-04-07 09:34 UTC
linq2db version: 2.9.7 (and earlier, I guess)

When there's a **table** named "DataType" the T4 generation creates wrong code for the ColumnAttribute attribute because _DataType_ is not fully qualified as _LinqToDB.DataType_.

Generated wrong code:
`[Column(DbType="uniqueidentifier", DataType=DataType.Guid)    , PrimaryKey, NotNull]`
Compiler error: 'DataType' does not contain a definition for 'Guid'

Right code should be:
`[Column(DbType="uniqueidentifier", DataType=LinqToDB.DataType.Guid)    , PrimaryKey, NotNull]`

There's already a fix in _LinqToDB.ttinclude_, line 283 where there's a check if one of the columns is named "DataType".
`var dataTypePrefix = t.Columns.Values.Any  (c => c.MemberName == "DataType") ? "LinqToDB." : ""`

I could fix the problem by changing that line to 
`var dataTypePrefix = t.Columns.Values.Any  (c => c.MemberName == "DataType") || Tables.Values.Any(tbl => tbl.Name == "DataType") ? "LinqToDB." : "";`

Proposal: Please integrate this (or a similar fix).

**Comment by MaceWindu** [comment] 2020-04-07 13:01
Duplicate of #1586

**Comment by MaceWindu** [comment] 2020-07-08 16:01
Closing as duplicate

**Closed** 2020-10-27 20:57 UTC
Labels: area: T4, type: bug
