### ISSUE TITLE
PersonalDataAttribute

### ISSUE THREAD

**Issue by tb-mtg** [linq2db/linq2db#1842] opened 2019-08-01 16:46 UTC
Microsoft uses the code below in its EntityTypeBuilder for properties with  the PersonalDataAttribute. How can this be done in LinqToDB?

```
      var encryptPersonalData = storeOptions?.ProtectPersonalData ?? false;
      if (encryptPersonalData) {
        var personalDataProps = typeof(T).GetProperties().Where(prop => Attribute.IsDefined(prop, typeof(ProtectedPersonalDataAttribute)));
        foreach (var p in personalDataProps) {
          if (p.PropertyType != typeof(string)) {
            throw new InvalidOperationException(Resources.CanOnlyProtectStrings);
          }
          builder.Property(typeof(string), p.Name).HasConversion(personalDataConverter);
        }
      }
```

**Comment by MaceWindu** [comment] 2019-08-02 07:31
Moved to linq2db as it is not Identity-specific question

**Comment by MaceWindu** [comment] 2019-08-02 07:34
Duplicate of #1837

**Closed by MaceWindu** 2019-08-02 07:34 UTC
