### ISSUE TITLE
Conditional operator exception

### ISSUE THREAD

**Issue by igor-tkachev** [linq2db/linq2db#1840] opened 2019-08-02 01:56 UTC
Conditional operator generates an exception.

### Steps to reproduce

Breaking commit - e41d05e8567995f5a9d691485e947c88dc6d38f3

```c#
[Test]
public void Test([IncludeDataSources(
	ProviderName.SqlCe, ProviderName.SqlServer2012, ProviderName.SqlServer2014)] string context)
{
	using (var db = GetDataContext(context))
	{
		var query =
			from p in db.Parent
			from c in db.Child.Take(1).DefaultIfEmpty()
			select new
			{
				a = p.ParentID == 1 ? c != null ? "1" : "2" : "3"
			};

		_ = query.ToList();
	}
}
```

### Environment details
linq2db version: *2.7.1*

**Comment by sdanyliv** [comment] 2019-08-02 13:34
Duplicate of #1838

**Closed** 2019-08-02 16:25 UTC
