### ISSUE TITLE
[QUESTION] QueryProc<T> and out parameters

### ISSUE THREAD

**Issue by RoyC-Retail-Assist** [linq2db/linq2db#926] opened 2017-11-23 09:07 UTC
I have a stored procedure which returns a filtered dataset (page X of Y) plus an OUT parameter of the total rows available.  I use QueryProc<T>("spName", parameters[]).

I can get the returned values from the underlying Command object but only if I read, or start to read, the returned IEnumerable e.g. ToList() as it is this which actually triggers the running of the SP.

Is there any way of triggering execution SP so that I can get the out values but still have the IEnumerable<T> without reading the full results?

**Comment by sdanyliv** [comment] 2017-11-23 14:50
As i know, from version 1.10.0 it should run procedure exactly after QueryProc execution.
Fixed in https://github.com/linq2db/linq2db/pull/884

**Comment by RoyC-Retail-Assist** [comment] 2017-11-23 19:57
I'm using v1.10.0 

The following doesn't populate the tot value until results.First() is called (or anything that starts to enumerate the result).  I'd like to be able to get the total value out without having to enumerate the result.

            var provider = new LinqToDB.DataProvider.SqlServer.SqlServerDataProvider("test", SqlServerVersion.v2012);
            var con = new SqlConnection(connectionString);
            var ctx = new DataConnection(provider, con);
            var tot = new DataParameter("total", null, DataType.Int32) {Direction = ParameterDirection.Output};
            var results = ctx.QueryProc<string>("Test", tot);
            var p = ctx.Command.Parameters["total"] as DbParameter;

            // at this point p.Value == null. I'd expect it to be 3

            results.First();

            // having read the results p.Value == 3 as expected

The SP being called

    create PROCEDURE [dbo].[RoyTest] 
    (
        @total int out
    )
    AS
    BEGIN
	SET NOCOUNT ON;

	set @total = 3;
		
	select 'resultset'
    END

**Comment by sdanyliv** [comment] 2017-12-18 20:10
@RoyC-Retail-Assist, it as designed with SQL Server.
According to https://msdn.microsoft.com/en-us/library/ms971497
You have to read all records and close datareader. Only then you can read output parameters.

> **Managing Return Value and OUTPUT Parameters**
> If you want to capture the integer passed back by the RETURN statement in TSQL or your stored procedure's OUTPUT parameters, you're going to have to take another few minutes to setup a Command object to capture these values from the resultset. Again, and I can't emphasis this enough, these values are not made available until you've processed all rowsets in each resultset (if there are any). Yes, a stored procedure can return several resultsets, **but the RETURN value and OUTPUT parameters are not populated until all queries have been completed and all rowsets transmitted back to the client**.

**Comment by sdanyliv** [comment] 2018-01-16 15:09
Closing. Looks like it is already answered.

**Closed by sdanyliv** 2018-01-16 15:09 UTC
