### ISSUE TITLE
Can not find root sequence

### ISSUE THREAD

**Issue by Marka83** [linq2db/linq2db#2195] opened 2020-04-27 08:14 UTC
I have these two assignments in my Select statement:

```cs
Datum = _context.Raspored
   .Where(y => y.RadnikId == r.Radnik.RadnikId && y.OrganizacijaId == r.Radnik.OrganizacijaId)
      .Min(y => y.DatumRasporeda), Godina=Sql.DatePart(Sql.DateParts.Year, _context.Raspored.Where(y => y.RadnikId == r.Radnik.RadnikId && y.OrganizacijaId == r.Radnik.OrganizacijaId).Min(y => y.DatumRasporeda))
```
First property is projected correctly, but if I include second, it throws:
"Can not find root sequence".
Same thing happens if I use .Value.Year instead of Sql.DatePart

### Environment details
linq2db version: 3.0.0.preview2
Database Server: SqlServer
Database Provider: MicrosoftDataSqlClient
Operating system: Windows 10
.NET Framework: .Net Core 3.1.3

**Comment by sdanyliv** [comment] 2020-04-27 08:33
Trying to reformat query, but it is difficult :)
Please post your models `Raspored` and `Radnik`. Also If you explain what you are trying to achieve, I will help you to write performant LINQ query.

**Comment by Marka83** [comment] 2020-04-27 08:39
Radnik -> Employee
Raspored -> Organizational assignment
DatumRasporeda->Assignment start date

I want to find date of first assignment based on assignment start date and then also get month and year part of the date.
It's not my query and I'll try to change it, but it should work even as it is now.
It used to work on EF.

**Comment by sdanyliv** [comment] 2020-04-27 08:41
Which SQL query is generated?

**Comment by Marka83** [comment] 2020-04-27 08:43
Query is not generated. It throws exception in parsing stage.
I'll send you full test case.

**Comment by Marka83** [comment] 2020-04-27 09:17
This is part of bigger query. When I try to create test case it works.
Must be some problem when combined with rest of the query.
I'll try to simplify the query before trying anything else.

**Comment by Marka83** [comment] 2020-04-27 13:14
I did manage to reproduce bug.
These are classes:

```

[Table("Employee")]
public class Employee
{
    [Column]
    [PrimaryKey(0)]
    public int? OrganizationId { get; set; }

    [Column]
    [PrimaryKey(1)]
    public int? EmployeeId { get; set; }

    [Column]
    public string Name { get; set; }

    public int? DummyId { get; set; }
    [Association(ThisKey =nameof(DummyId),OtherKey =nameof(DummyId))]
    public Dummy Dummy { get; set; }

    [Column]
    public DateTime? StartDate { get; set; }
}

[Table("Assignment")]
public class Assignment
{
    [Column]
    [PrimaryKey(0)]
    public int? OrganizationId { get; set; }

    [Column]
    [PrimaryKey(1)]
    public int? EmployeeId { get; set; }

    [Column]
    [PrimaryKey(2)]
    public int? AssignmentId { get; set; }

    [Column]
    public DateTime? StartDate { get; set; }

    [Column]
    public DateTime? EndDate { get; set; }
}

[Table("Dummy")]
public class Dummy
{
    [Column]
    [PrimaryKey]
    public int DummyId { get; set; }

}
```
And this is problematic query:
```

var assignments = _context.GetTable<Assignment>()
                .GroupBy(g => new { g.OrganizationId, g.EmployeeId })
                .Select(g => new
                {
                    g.Key.OrganizationId,
                    g.Key.EmployeeId,
                    StartDate = g.Min(a => a.StartDate),
                    TestDate= Sql.DatePart(Sql.DateParts.Year,g.Min(a => a.StartDate))
                });

            var intermediate = from e in _context.GetTable<Employee>()
                               join a in assignments on new { e.OrganizationId, e.EmployeeId } equals new { a.OrganizationId, a.EmployeeId } into eat
                               from ea in eat.DefaultIfEmpty()
                               select new
                               {
                                   OrganizationId = e.OrganizationId,
                                   EmployeeId = e.EmployeeId,
                                   Name = e.Name,
                                   DummyId=e.DummyId,
                                   StartDate = Sql.DatePart(Sql.DateParts.Year, ea.StartDate)
                               };
            var result=from m in intermediate
                       join d in _context.GetTable<Dummy>() on m.DummyId equals d.DummyId into mdt
                       from md in mdt.DefaultIfEmpty()
                       select new
                       {
                           OrganizationId = m.OrganizationId,
                           EmployeeId = m.EmployeeId,
                           Name = m.Name,
                           DummyId = m.DummyId,
                           Dummy=md,
                           StartDate = m.StartDate
                       };
```
Problem is with last query. If I don't use Sql.DatePart in 'intermediate' everything works fine.
Unfortunately, I have to use query in this way because it is used as a source to another component, so I can't merge 'intermediate' and 'result' query.

**Comment by Marka83** [comment] 2020-04-28 06:31
Or even more concise:
```

var assignments = _context.GetTable<Assignment>()
                .GroupBy(g => new { g.OrganizationId, g.EmployeeId })
                .Select(g => new
                {
                    g.Key.OrganizationId,
                    g.Key.EmployeeId,
                    StartDate = g.Min(a => a.StartDate),
                    TestDate= Sql.DatePart(Sql.DateParts.Year,g.Min(a => a.StartDate))
                });

            var intermediate = from e in _context.GetTable<Employee>()
                               join a in assignments on new { e.OrganizationId, e.EmployeeId } equals new { a.OrganizationId, a.EmployeeId } into eat
                               from ea in eat.DefaultIfEmpty()
                               select new
                               {
                                   OrganizationId = e.OrganizationId,
                                   EmployeeId = e.EmployeeId,
                                   Name = e.Name,
                                   DummyId=e.DummyId,
                                   TestDate=ea.TestDate,
                                   StartDate = Sql.DatePart(Sql.DateParts.Year, ea.StartDate)
                               };
```
It's enough to use previously projected column with  Sql.DatePart ('TestDate') in another query.

**Comment by sdanyliv** [comment] 2020-04-28 06:39
I see. Will fix that in next release. 
Can you find workaround now without waiting for fix?

**Comment by Marka83** [comment] 2020-04-28 07:29
I dont know. Maybe to manually map function, but I'm still inexperienced in Linq2Sql so I don't know how to write DatePart function:

```
[Sql.Expression("DatePart({0},{1})", PreferServerSide = true)]
        public static int DatePart(DateParts datePart, DateTime? dateTime)
        {
            throw new NotImplementedException();
        }
```
This generates:
DatePart(0,Min([t1].[StartDate])).

If I set datePart to be string it generates:
DatePart(N'Year',Min([t1].[StartDate]))

How can I send Year?
Would this manual function mapping even solve problem?

**Comment by Marka83** [comment] 2020-04-28 07:31
I can wait for next version if it will be soon. I'm currently migrating other parts of application, so I can leave this for now.

**Comment by sdanyliv** [comment] 2020-04-28 08:12
Better to create DatePartYear function. I think root of the problem how we build Sql.Datepart function.

**Comment by sdanyliv** [comment] 2020-04-28 10:33
Strange it is not reproducible on current sources. Could you please check lates master build:
There is Nuget feed on Azure:
https://dev.azure.com/linq2db/linq2db/_packaging?_a=feed&feed=linq2db

**Comment by sdanyliv** [comment] 2020-04-28 10:34
Generated SQL is:
```sql
SELECT
	[e].[OrganizationId],
	[e].[EmployeeId],
	[e].[Name],
	[e].[DummyId],
	[eat].[TestDate],
	[eat].[StartDate]
FROM
	[Employee] [e]
		LEFT JOIN (
			SELECT
				[t1].[OrganizationId],
				[t1].[EmployeeId],
				DatePart(year, Min([t1].[StartDate])) as [TestDate],
				Min([t1].[StartDate]) as [StartDate]
			FROM
				[Assignment] [t1]
			GROUP BY
				[t1].[OrganizationId],
				[t1].[EmployeeId]
		) [eat] ON [e].[OrganizationId] = [eat].[OrganizationId] AND [e].[EmployeeId] = [eat].[EmployeeId]
```

**Comment by Marka83** [comment] 2020-04-28 11:02
I'll try!

**Comment by Marka83** [comment] 2020-04-28 11:07
I was using linq2db.entityframeworkcore.
Maybe that is the problem. Although, 3.0.0 should be using 3.0.0.preview2 of Linq2Db.

**Comment by Marka83** [comment] 2020-04-28 11:35
I've removed linq2db.entityframeworkcore and used  3.0.0-rc.1984 instead, but the result is same.
A can try to create sample solution.

**Comment by Marka83** [comment] 2020-04-28 11:54
On clean project works ok.
Maybe its something with my IMetadataReader.
I'll check.

**Comment by sdanyliv** [comment] 2020-04-28 12:01
Check columns. `DummyId` was not mapped in your sample.

**Comment by Marka83** [comment] 2020-04-28 12:06
It was problem with IMetadataReader.
I copied this code from AttributeReader into my implementation:
```

var attrs = memberInfo.GetCustomAttributes(typeof(T), inherit);
			if (attrs.Length > 0)
			{
				var arr = new T[attrs.Length];

				for (var i = 0; i < attrs.Length; i++)
					arr[i] = (T)attrs[i];

				return arr;
			}

```
If I comment this everything is fine.
I see that you concatenate readers and use:
`return _readers.SelectMany(r => r.GetAttributes<T>(type, inherit)).ToArray();`

Maybe there is some incorrect behavior when there is same attribute from different readers?

**Comment by Marka83** [comment] 2020-04-28 12:20
Oh, and one more question, not related to this.
Why are you generating left join with subquery?
For example, query from ticket 2199:

```
var man1 = from e in _context.GetTable<Manufacturer>()
                       join c in _context.GetTable<Country>() on e.CountryCode equals c.Code into ce
                       from co in ce.DefaultIfEmpty()
                       where e.ManufacturerId == 1
                       select new Manufacturer { ManufacturerId = e.ManufacturerId, CountryCode = e.CountryCode, Name = e.Name, CountryEntity = co };
```
Generates:
```

SELECT
	[e].[ManufacturerId],
	[e].[CountryCode],
	[e].[Name],
	[t1].[co],
	[t1].[Name],
	[t1].[c1]
FROM
	[Manufacturer] [e]
		LEFT JOIN (
			SELECT
				[ce].[Code] as [co],
				1 as [c1],
				[ce].[Name]
			FROM
				[Country] [ce]
		) [t1] ON ([e].[CountryCode] IS NULL AND [t1].[co] IS NULL OR [e].[CountryCode] = [t1].[co])
WHERE
	[e].[ManufacturerId] = 1
```
Why the need to name all the columns?
Wouldn't be better to just use:
```

SELECT
	[e].[ManufacturerId],
	[e].[CountryCode],
	[e].[Name],
	[t1].[Code] as [co],
	[t1].[Name],
	1 as [c1]
FROM
	[Manufacturer] [e]
		LEFT JOIN [Country] [t1] ON ([e].[CountryCode] IS NULL AND [t1].[Code] IS NULL OR [e].[CountryCode] = [t1].[Code]) 
WHERE
	[e].[ManufacturerId] = 1
```

We have queries with 30 joins, so query is huuuuuuuuge, but it doesn't have to be.
I can specify this as separate feature request, if you're interested in implementing it.

**Comment by Marka83** [comment] 2020-04-28 12:22
Maybe I'm wrong, but if I remember correctly, this wasn't the case in 2.9.8?

**Comment by sdanyliv** [comment] 2020-04-28 12:28
Looks like regression. I’m working on huge refactoring PR with associations, it will be fixed together. So next version will optimize this better.

**Comment by Marka83** [comment] 2020-04-28 12:33
Ok.
As far as I'm concerned this ticket can be closed.

**Closed** 2020-04-28 13:27 UTC
Labels: area: linq
