### ISSUE TITLE
Incorrect result using LeftJoin and ternary operator in select clause

### ISSUE THREAD

**Issue by afkos** [linq2db/linq2db#1815] opened 2019-07-19 06:31 UTC
The query returns wrong result for columns MinQuantity, MaxQuantity when using LeftJoin and ternary operator in a sub query.
It works if change LeftJoin to linq join syntax. 

// StLink: InId = 1, InMinQuantity = 1, InMaxQuantity = 2
// EdtLinks: empty
The query2 returns null for InMinQuantity and InMaxQuantity columns as if it used columns from joined table.
```c#
var query1 = from l in stLinks
             //join j in edtLinks on l.InId equals j.InId into j
             //from e in j.DefaultIfEmpty()
             from e in edtLinks.LeftJoin(j => l.InId == j.InId)
             select new
             {
                 LinkId = l.InId,
                 MinQuantity = e == null ? l.InMinQuantity : e.InMinQuantity,
                 MaxQuantity = e == null ? l.InMaxQuantity : e.InMaxQuantity,
             };

var query2 = from q in query1
             select new
             {
                 q.LinkId,
                 q.MinQuantity,
                 q.MaxQuantity,
             };
```
Generated sql looks fine:
```sql
SELECT
	[x].[InId],
	[j].[InId],
	[j].[InMaxQuantity],
	[j].[InMinQuantity],
	[x].[InMinQuantity],
	[x].[InMaxQuantity]
FROM
	[#stLinks] [x]
		LEFT JOIN [#edtLinks] [j] ON [x].[InId] = [j].[InId]
WHERE
	[x].[InId] = 1
```

I expected when-case statement in the sql query, is there a reason for fetching multiple columns instead of computing on the server side?
It's not a problem though.

### Steps to reproduce
```c#
[Table]
public class StLink
{
    [Column, PrimaryKey, Identity] public int InId { get; set; }
    [Column, Nullable] public double? InMaxQuantity { get; set; }
    [Column, Nullable] public double? InMinQuantity { get; set; }
}

[Table]
public class EdtLink
{
    [Column, PrimaryKey, NotNull] public int InId { get; set; }
    [Column, Nullable] public double? InMaxQuantity { get; set; }
    [Column, Nullable] public double? InMinQuantity { get; set; }
}

[TestClass]
public class UnitTest1
{
    [TestMethod]
    public void TestMethod1()
    {
        using (var db = new DataConnection(new SqlServerDataProvider("", SqlServerVersion.v2008), "Data Source=ak-52;Initial Catalog=Demo2018r2;Integrated Security=True"))
        {
            var stLinks = db.CreateTempTable(new[]
            {
                new StLink { InId = 1, InMinQuantity = 1, InMaxQuantity = 2 },
                new StLink { InId = 2, InMinQuantity = null, InMaxQuantity = null }
            }, tableName: "#stLinks");

            var edtLinks = db.CreateTempTable(new[]
            {
                new EdtLink { InId = 2, InMinQuantity = 3, InMaxQuantity = 4}
            }, tableName: "#edtLinks");

            var query1 = from l in stLinks
                         //join j in edtLinks on l.InId equals j.InId into j
                         //from e in j.DefaultIfEmpty()
                         from e in edtLinks.LeftJoin(j => l.InId == j.InId)
                         select new
                         {
                             LinkId = l.InId,
                             MinQuantity = e == null ? l.InMinQuantity : e.InMinQuantity,
                             MaxQuantity = e == null ? l.InMaxQuantity : e.InMaxQuantity,
                         };

            var query2 = from q in query1
                         select new
                         {
                             q.LinkId,
                             q.MinQuantity,
                             q.MaxQuantity,
                         };

            var r = query2.SingleOrDefault(x => x.LinkId == 1);
            Assert.IsNotNull(r);
            Assert.AreEqual(1, r.MinQuantity); // actual: null
            Assert.AreEqual(2, r.MaxQuantity); // actual: null

            var r2 = query2.SingleOrDefault(x => x.LinkId == 2);
            Assert.IsNotNull(r2);
            Assert.AreEqual(3, r2.MinQuantity); // it's ok
            Assert.AreEqual(4, r2.MaxQuantity); // it's ok
        }
    }
```

### Environment details
linq2db version: 2.7.4
Database Server: Microsoft SQL Server 2017
Database Provider: SqlServerDataProvider
Operating system: Windows 10
.NET Framework: 4.7.2

**Comment by MaceWindu** [comment] 2019-07-19 07:07
should be duplicate of #1773

As for select with client-side evaluation - linq2db do it quite aggresively for select expressions, and to force server side evaluation you can try to use `Sql.AsSql` wrapper function

**Comment by MaceWindu** [comment] 2019-07-19 08:08
Confirmed fixed. Check `Issue1815WithServerEvaluation` tests [here](https://github.com/linq2db/linq2db/commit/6124f8af9d84d81b62167c87e9ffc9952b77346f#diff-e9a362b3218ff2f5cd63b3fe9b81a7e0R2585) to see how make conditional fields evaluated on server

**Closed by MaceWindu** 2019-07-19 08:08 UTC
Labels: type: bug
